Repository directus/directus, pull requests merged in 2022-05, with the labels that each got.

#13076 Use older Oracle optimizer for faster first execution
  packages/schema/src/dialects/oracledb.ts
Labels: API, DB: Oracle, Improvement

#13073 collections broken link fix
  docs/getting-started/quickstart.md
Labels: Bug, Documentation

#13072 Spelling
  .eslintrc.js
  api/README.md
  api/tests/database/migrations/run.test.ts
  app/src/components/transition/bounce/transition-bounce.vue
  app/src/composables/groupable/readme.md
  app/src/interfaces/_system/system-folder/folder.vue
  app/src/interfaces/readme.md
  app/src/interfaces/tags/tags.vue
  app/src/lang/translations/en-US.yaml
  app/src/modules/insights/components/panel.vue
  app/src/stores/presets.ts
  app/src/utils/readable-mime-type/types.json
  app/src/views/private/components/notification-item/readme.md
  app/vite.config.js
  changelog.md
  docker-compose.yml
  docs/app/file-library.md
  docs/app/layouts.md
  docs/app/settings.md
  docs/cloud/accounts.md
  docs/cloud/teams.md
  docs/configuration/config-options.md
  docs/configuration/sso-examples.md
  docs/extensions/creating-extensions.md
  docs/extensions/modules.md
  docs/getting-started/installation/plesk.md
  docs/reference/system/permissions.md
  packages/format-title/README.md
  packages/specs/src/paths/activity/activity-comment.yaml
  tests/api/items/filters.test.ts
  tests/docker-compose.yml
Labels: Documentation, Optimization

#13088 New Crowdin updates
  app/src/lang/translations/da-DK.yaml
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#13091 spelling: extensionentrypoints
  app/vite.config.js
Labels: Optimization

#13051 Update knex to version 2.0.0
  api/package.json
  api/src/services/items.ts
  api/src/services/utils.ts
  package-lock.json
  package.json
Labels: API, Optimization

#13015 Fix graphql schema for m2o fields without permissions to related collection
  api/src/utils/reduce-schema.ts
  tests/api/items/many-to-many.test.ts
  tests/api/items/many-to-one.test.ts
  tests/setup/seeds/02_directus_relations.js
  tests/setup/seeds/06_directus_permissions.js
  tests/setup/seeds/07_tests_flow.js
  tests/setup/seeds/08_schema_date_types.js
Labels: Bug, GraphQL

#13099 Add local export capability
  app/package.json
  app/src/displays/collection/index.ts
  app/src/displays/datetime/index.ts
  app/src/displays/filesize/index.ts
  app/src/displays/formatted-json-value/index.ts
  app/src/displays/formatted-value/index.ts
  app/src/displays/labels/index.ts
  app/src/displays/mime-type/index.ts
  app/src/displays/user/index.ts
  app/src/lang/translations/en-US.yaml
  app/src/layouts/calendar/index.ts
  app/src/layouts/cards/index.ts
  app/src/layouts/map/index.ts
  app/src/layouts/tabular/index.ts
  app/src/modules/content/routes/collection.vue
  app/src/utils/save-as-csv.ts
  app/src/views/private/components/export-sidebar-detail.vue
  app/vite.config.js
  package-lock.json
  packages/shared/src/types/displays.ts
Labels: App, New Feature

#13110 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#13112 Fix slug not turning pasted value with spaces to separators
  app/src/components/v-input/v-input.vue
Labels: App, Bug

#13103 Show collection key instead of name in Data Model
  app/src/modules/settings/routes/data-model/collections/components/collection-item.vue
  app/src/modules/settings/routes/roles/item/components/permissions-overview-row.vue
Labels: App, Improvement

#13102 Fix auto generated field keys not being reset
  app/src/modules/settings/routes/data-model/field-detail/field-detail-simple/field-configuration.vue
  app/src/modules/settings/routes/data-model/field-detail/field-detail-simple/field-detail-simple.vue
Labels: App, Bug

#13123 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
Labels: Automerge

#13127 New Crowdin updates
  app/src/lang/translations/zh-TW.yaml
Labels: Automerge

#13134 New Crowdin updates
  app/src/lang/translations/uk-UA.yaml
Labels: Automerge

#13156 New Crowdin updates
  app/src/lang/translations/es-ES.yaml
Labels: Automerge

#13175 New Crowdin updates
  app/src/lang/translations/fr-FR.yaml
Labels: Automerge

#13176 New Crowdin updates
  app/src/lang/translations/fr-FR.yaml
Labels: Automerge

#13177 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
Labels: Automerge

#13178 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
Labels: Automerge

#13182 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#13189 Reset refresh promise after catch
  packages/sdk/src/base/auth.ts
Labels: Bug, Package: sdk

#13190 Update gatsby-* subpackages in gatsby-source-directus
  package-lock.json
  packages/gatsby-source-directus/package.json
Labels: Dependencies

#13158 fixes nested groups filtering out its parents values
  app/src/components/v-form/v-form.vue
Labels: App, Bug

#13147 Fix WYSIWYG being disabled due to loading
  app/src/composables/use-relation/use-relation-multiple.ts
Labels: App, Bug

#13191 Use JSON.parse wrapper function to prevent pollution attacks
  api/src/auth/drivers/oauth2.ts
  api/src/auth/drivers/openid.ts
  api/src/cli/commands/schema/apply.ts
  api/src/controllers/assets.ts
  api/src/database/migrations/20210225A-add-relations-sort-field.ts
  api/src/database/migrations/20210506A-rename-interfaces.ts
  api/src/database/migrations/20210802A-replace-groups.ts
  api/src/database/migrations/20210805A-update-groups.ts
  api/src/database/migrations/20210805B-change-image-metadata-structure.ts
  api/src/database/migrations/20211007A-update-presets.ts
  api/src/env.ts
  api/src/middleware/graphql.ts
  api/src/services/import-export.ts
  api/src/services/payload.ts
  api/src/utils/get-default-value.ts
  api/src/utils/get-permissions.ts
  api/src/utils/get-schema.ts
  api/src/utils/parse-json.ts
  api/src/utils/sanitize-query.ts
  api/tests/utils/parse-json.test.ts
Labels: API, Optimization

#13184 Display error message on OAuth errors
  api/src/auth/drivers/oauth2.ts
  api/src/auth/drivers/openid.ts
  api/src/exceptions/index.ts
  api/src/exceptions/invalid-provider.ts
  api/src/services/authentication.ts
  app/src/lang/translations/en-US.yaml
  app/src/routes/login/components/sso-links.vue
Labels: API, Improvement

#13193 New Crowdin updates
  app/src/lang/translations/es-419.yaml
  app/src/lang/translations/es-CL.yaml
  app/src/lang/translations/fr-CA.yaml
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#13133 fix sort field not updating in export sidebar
  app/src/views/private/components/export-sidebar-detail.vue
Labels: App, Bug

#13121 Added emitEvents option to write operation
  api/src/operations/write/index.ts
  app/src/lang/translations/en-US.yaml
  app/src/operations/write/index.ts
  package-lock.json
Labels: API, App, Improvement

#13151 fetching id's for nested relations in the o2m interface
  app/src/interfaces/list-m2m/list-m2m.vue
  app/src/interfaces/list-o2m-tree-view/list-o2m-tree-view.vue
  app/src/interfaces/list-o2m/list-o2m.vue
Labels: App, Bug

#13126 Hide import if create is not allowed
  app/src/views/private/components/export-sidebar-detail.vue
Labels: App, Improvement

#13120 fixes saving interface option values for field conditions
  app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-conditions.vue
Labels: App, Bug

#13115 Fix incorrect bindings in postgres dialect
  packages/schema/src/dialects/postgres.ts
Labels: API, Bug, DB: Postgres

#12198 Fix Invalid foreign key when applying schema snapshot
  api/src/utils/apply-snapshot.ts
  docs/app/content.md
  docs/app/layouts.md
  docs/configuration/config-options.md
  docs/configuration/sso-examples.md
  docs/extensions/creating-extensions.md
Labels: API, Bug

#13204 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#13207 Show edit drawer as preview for disabled many to one
  app/src/interfaces/select-dropdown-m2o/select-dropdown-m2o.vue
Labels: App, Improvement

#13214 Improve type definitions for o2m item queries involving deep, filter or sort
  packages/sdk/src/items.ts
Labels: Improvement, Package: sdk

#13220 Fix limit/filter/search reactivity for export sidebar
  app/src/views/private/components/export-sidebar-detail.vue
Labels: App, Bug

#13231 Prevent inputs in deeply nested groups being duplicated
  app/src/components/v-form/v-form.vue
Labels: App, Bug

#13223 Form fields in a group unable to reset to default or undo changes
  app/src/components/v-form/v-form.vue
Labels: App, Bug

#13222 Delete field only after foreign key constraints are removed
  api/src/services/fields.ts
Labels: API, Bug

#13238 New Crowdin updates
  app/src/lang/translations/cs-CZ.yaml
Labels: Automerge

#13241 New Crowdin updates
  app/src/lang/translations/af-ZA.yaml
Labels: Automerge

#13242 Init count of soft limit in wysiwyg on first render
  app/src/interfaces/input-rich-text-html/input-rich-text-html.vue
Labels: App, Bug

#13259 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#13263 Add string-export support for related-values and translations display
  app/src/displays/related-values/index.ts
  app/src/displays/translations/index.ts
  app/src/utils/save-as-csv.ts
  packages/shared/src/types/displays.ts
Labels: App, Improvement

#13264 fix: AUTH_PROVIDER ibmid should display as IBMid
  packages/format-title/src/special-case.ts
Labels: App, Improvement

#13266 New Crowdin updates
  app/src/lang/translations/sv-SE.yaml
Labels: Automerge

#13267 New Crowdin updates
  app/src/lang/translations/sv-SE.yaml
Labels: Automerge

#13268 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#13269 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#13275 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
Labels: Automerge

#13279 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#13280 New Crowdin updates
  app/src/lang/translations/nl-NL.yaml
Labels: Automerge

#13285 re-edited support doc
  docs/getting-started/support.md
Labels: Documentation

#13272 Creating corresponding relational field for file fields throws errors
  app/src/modules/settings/routes/data-model/field-detail/store/alterations/file.ts
Labels: App, Bug

#13310 New Crowdin updates
  app/src/lang/translations/fr-FR.yaml
Labels: Automerge

#13324 New Crowdin updates
  app/src/lang/translations/ja-JP.yaml
Labels: Automerge

#13325 New Crowdin updates
  app/src/lang/translations/ca-ES.yaml
Labels: Automerge

#13316 Fix app docs collection & item page
  app/src/modules/docs/components/links.yaml
Labels: App, Bug

#13307 Stalling Sqlite when using cascading foreign contraints
  api/src/services/items.ts
Labels: API, Bug

#13309 Prevent changing active status of the only active admin user
  api/src/services/users.ts
Labels: API, Improvement

#13330 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#13332 New Crowdin updates
  app/src/lang/translations/ca-ES.yaml
Labels: Automerge

#13335 New Crowdin updates
  app/src/lang/translations/ca-ES.yaml
Labels: Automerge

#13270 Fix docs homepage sidebar
  docs/.vuepress/styles/colors.styl
  docs/.vuepress/styles/palette.styl
  docs/.vuepress/theme/layouts/Homepage.vue
Labels: Documentation

#13250 Fix inconsistent revisions after batch update
  api/src/services/items.ts
  api/tests/services/items.test.ts
Labels: API, Bug

#13340 New Crowdin updates
  app/src/lang/translations/fr-FR.yaml
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#13367 Update hooks.md - Add `query` object to `items.read` filter meta documentation
  docs/extensions/hooks.md
Labels: Documentation

#13375 Fix user update going through status check even when the payload does not have `status` in it
  api/src/services/users.ts
Labels: API, Bug

#11737 Add support to insensitive case operators
  api/src/utils/apply-query/index.ts
  api/src/utils/apply-query/operators/between.operator.ts
  api/src/utils/apply-query/operators/contains.operator.ts
  api/src/utils/apply-query/operators/ends-with.operator.ts
  api/src/utils/apply-query/operators/equals.operator.ts
  api/src/utils/apply-query/operators/greather-than-equals.operator.ts
  api/src/utils/apply-query/operators/greather-than.operator.ts
  api/src/utils/apply-query/operators/in.operator.ts
  api/src/utils/apply-query/operators/index.ts
  api/src/utils/apply-query/operators/insensitive-contains.operator.ts
  api/src/utils/apply-query/operators/insensitive-ends-with.operator.ts
  api/src/utils/apply-query/operators/insensitive-equals.operator.ts
  api/src/utils/apply-query/operators/insensitive-not-contains.operator.ts
  api/src/utils/apply-query/operators/insensitive-not-ends-with.operator.ts
  api/src/utils/apply-query/operators/insensitive-not-equals.operator.ts
  api/src/utils/apply-query/operators/insensitive-not-starts-with.operator.ts
  api/src/utils/apply-query/operators/insensitive-starts-with.operator.ts
  api/src/utils/apply-query/operators/intersects-bbox.operator.ts
  api/src/utils/apply-query/operators/intersects.operator.ts
  api/src/utils/apply-query/operators/is-empty.operator.ts
  api/src/utils/apply-query/operators/is-not-empty.operator.ts
  api/src/utils/apply-query/operators/is-not-null.operator.ts
  api/src/utils/apply-query/operators/is-null.operator.ts
  api/src/utils/apply-query/operators/less-than-equals.operator.ts
  api/src/utils/apply-query/operators/less-than.operator.ts
  api/src/utils/apply-query/operators/not-between.operator.ts
  api/src/utils/apply-query/operators/not-contains.operator.ts
  api/src/utils/apply-query/operators/not-ends-with.operator.ts
  api/src/utils/apply-query/operators/not-equals.operator.ts
  api/src/utils/apply-query/operators/not-in.operator.ts
  api/src/utils/apply-query/operators/not-intersects-bbox.operator.ts
  api/src/utils/apply-query/operators/not-intersects.operator.ts
  api/src/utils/apply-query/operators/not-starts-with.operator.ts
  api/src/utils/apply-query/operators/operator-register.ts
  api/src/utils/apply-query/operators/starts-with.operator.ts
  app/src/interfaces/_system/system-filter/input-group.vue
  app/src/lang/translations/en-US.yaml
  app/src/utils/generate-joi/index.ts
  packages/shared/src/types/filter.ts
  packages/shared/src/utils/get-filter-operators-for-type.test.ts
  packages/shared/src/utils/get-filter-operators-for-type.ts
  tests/api/items/filters.test.ts
Labels: API, App, New Feature

#13384 New Crowdin updates
  app/src/lang/translations/fr-CA.yaml
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#13385 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#13388 Fix compareValue check for _null and _empty type of operators
  api/src/utils/apply-query/operators/is-empty.operator.ts
  api/src/utils/apply-query/operators/is-not-empty.operator.ts
  api/src/utils/apply-query/operators/is-not-null.operator.ts
  api/src/utils/apply-query/operators/is-null.operator.ts
  packages/shared/src/types/filter.ts
Labels: API, Bug

#13400 New Crowdin updates
  app/src/lang/translations/en-GB.yaml
Labels: Automerge

#13410 Fix parsing of time and dates when filtering in SQLite
  api/src/database/helpers/date/dialects/sqlite.ts
Labels: API, Bug, DB: SQLite

#13409 Hide Save as Copy when creating new item
  app/src/modules/content/routes/item.vue
Labels: App, Bug

#13420 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#13432 New Crowdin updates
  app/src/lang/translations/fr-FR.yaml
Labels: Automerge

#13429 Add cast-timestamp field flag to system tables
  api/src/database/system-data/fields/activity.yaml
  api/src/database/system-data/fields/dashboards.yaml
  api/src/database/system-data/fields/notifications.yaml
  api/src/database/system-data/fields/panels.yaml
  api/src/database/system-data/fields/shares.yaml
Labels: API, Bug, DB: SQLite

#13474 Fix field conditions when null
  app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-conditions.vue
Labels: App, Bug

#13453 Adds _none and _some operators
  api/src/utils/apply-query/index.ts
Labels: API, Bug

#13486 docs: clarified data, schema, and permissions caching
  docs/configuration/config-options.md
Labels: Documentation

#13479 Allow selecting primary key when aggregating count in time series panel
  app/src/panels/time-series/index.ts
Labels: App, Bug

#13462 Improve dashboard saving experience
  app/src/composables/use-edits-guard/use-edits-guard.ts
  app/src/modules/insights/routes/dashboard.vue
Labels: App, Improvement

#13499 New Crowdin updates
  app/src/lang/translations/fa-IR.yaml
Labels: Automerge

#13276 Validate type of items' primary keys
  api/src/services/items.ts
  api/src/utils/validate-keys.ts
  api/tests/services/items.test.ts
  api/tests/utils/validate-keys.test.ts
  tests/api/items/no-relations.test.ts
Labels: API, Bug

#13501 Add empty state for Translation Strings page
  app/src/lang/translations/en-US.yaml
  app/src/modules/settings/routes/translation-strings/collection.vue
Labels: App, Improvement

#13517 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#13424 Docs: re-edited user-directory + users-roles-permissions
  docs/app/content/data-sharing.md
  docs/app/insights.md
  docs/app/user-directory.md
  docs/configuration/users-roles-permissions.md
  docs/getting-started/glossary.md
  docs/reference/authentication.md
  docs/reference/cli.md
Labels: Documentation

#13274 Environment variable with _FILE suffix containing invalid path throws error on start
  api/src/env.ts
Labels: API, Improvement

#13523 Remove unnecessary ampersand from URLs in filter tests
  tests/api/items/filters.test.ts
Labels: Optimization

#13524 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#13528 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#13541 New Crowdin updates
  app/src/lang/translations/cs-CZ.yaml
Labels: Automerge

#13545 New Crowdin updates
  app/src/lang/translations/cs-CZ.yaml
Labels: Automerge

#13527 Fix metadata for directus_folders
  api/src/controllers/folders.ts
Labels: API, Bug

#13531 add `meta` to list responses for OAS
  packages/specs/src/openapi.yaml
  packages/specs/src/paths/activity/activities.yaml
  packages/specs/src/paths/files/files.yaml
  packages/specs/src/paths/folders/folders.yaml
  packages/specs/src/paths/items/items.yaml
  packages/specs/src/paths/permissions/permissions.yaml
  packages/specs/src/paths/presets/presets.yaml
  packages/specs/src/paths/revisions/revisions.yaml
  packages/specs/src/paths/roles/roles.yaml
  packages/specs/src/paths/users/users.yaml
Labels: Bug, Package: specs

#13532 Remove the paste value check on slug inputs
  app/src/components/v-input/v-input.vue
Labels: App, Bug

#13547 New Crowdin updates
  app/src/lang/translations/cs-CZ.yaml
Labels: Automerge

#13548 New Crowdin updates
  app/src/lang/translations/cs-CZ.yaml
Labels: Automerge

#13539 Added missing "DB_SSL_*_FILE" to the "_FILE" allow list.
  api/src/env.ts
Labels: API, Bug

#13455 Remove workaround in release flow
  .github/workflows/release.yml
Labels: Optimization

#13444 Remove npmrc files which prevent lockfile creation in workspaces
  api/.npmrc
  app/.npmrc
  docs/.npmrc
  package.json
  packages/cli/.npmrc
  packages/create-directus-extension/.npmrc
  packages/create-directus-project/.npmrc
  packages/drive-azure/.npmrc
  packages/drive-gcs/.npmrc
  packages/drive-s3/.npmrc
  packages/drive/.npmrc
  packages/extensions-sdk/.npmrc
  packages/format-title/.npmrc
  packages/gatsby-source-directus/.npmrc
  packages/schema/.npmrc
  packages/sdk/.npmrc
  packages/shared/.npmrc
  packages/specs/.npmrc
Labels: Optimization

#13389 Don't consider SIGN_OUT an SSO error
  app/src/routes/login/components/sso-links.vue
Labels: App, Improvement

#13363 Improve translation for require_value_to_be_set
  app/src/lang/translations/en-CA.yaml
  app/src/lang/translations/en-GB.yaml
  app/src/lang/translations/en-US.yaml
  app/src/lang/translations/nl-NL.yaml
Labels: App, Improvement

#13563 Fix field conditions optionDefaults computed property
  app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-conditions.vue
Labels: App, Bug

#13577 `last_page` type was `date` instead of `str`
  docs/reference/system/users.md
Labels: Bug, Documentation

#13580 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#11141 Allow authentication using MSSQL azure-active-directory-service-principal-secret
  api/src/database/index.ts
Labels: API, Improvement

#13549 Add System token interface
  api/src/database/system-data/fields/users.yaml
  app/src/interfaces/_system/system-token/index.ts
  app/src/interfaces/_system/system-token/system-token.vue
  app/src/lang/translations/en-US.yaml
Labels: API, App, Improvement, Notice

#13586 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/ca-ES.yaml
  app/src/lang/translations/cs-CZ.yaml
  app/src/lang/translations/da-DK.yaml
  app/src/lang/translations/de-DE.yaml
  app/src/lang/translations/en-CA.yaml
  app/src/lang/translations/en-GB.yaml
  app/src/lang/translations/es-419.yaml
  app/src/lang/translations/es-CL.yaml
  app/src/lang/translations/es-ES.yaml
  app/src/lang/translations/et-EE.yaml
  app/src/lang/translations/fi-FI.yaml
  app/src/lang/translations/fr-CA.yaml
  app/src/lang/translations/fr-FR.yaml
  app/src/lang/translations/hr-HR.yaml
  app/src/lang/translations/hu-HU.yaml
  app/src/lang/translations/id-ID.yaml
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/ja-JP.yaml
  app/src/lang/translations/nl-NL.yaml
  app/src/lang/translations/pl-PL.yaml
  app/src/lang/translations/pt-BR.yaml
  app/src/lang/translations/pt-PT.yaml
  app/src/lang/translations/ro-RO.yaml
  app/src/lang/translations/ru-RU.yaml
  app/src/lang/translations/sl-SI.yaml
  app/src/lang/translations/sr-CS.yaml
  app/src/lang/translations/sv-SE.yaml
  app/src/lang/translations/th-TH.yaml
  app/src/lang/translations/tr-TR.yaml
  app/src/lang/translations/uk-UA.yaml
  app/src/lang/translations/zh-CN.yaml
Labels: Automerge

#12033 Add projectUrl to defaultTemplateData
  api/src/services/mail/index.ts
Labels: API, Improvement

#13005 Docs: Self-Hosted Section + Updated Quickstart Guide
  docs/.vuepress/config.js
  docs/getting-started/quickstart.md
  docs/self-hosted/installation.md
  docs/self-hosted/installation/aws.md
  docs/self-hosted/installation/cli.md
  docs/self-hosted/installation/cloudron.md
  docs/self-hosted/installation/digitalocean-app-platform.md
  docs/self-hosted/installation/docker.md
  docs/self-hosted/installation/gcp.md
  docs/self-hosted/installation/iis.md
  docs/self-hosted/installation/manual.md
  docs/self-hosted/installation/plesk.md
  docs/self-hosted/installation/ubuntu.md
  docs/self-hosted/quickstart.md
Labels: Documentation

#13597 New Crowdin updates
  app/src/lang/translations/nl-NL.yaml
Labels: Automerge

#13601 Docs: fix wrong url paths for self-hosted installation guides
  docs/self-hosted/installation.md
Labels: Documentation

#13612 New Crowdin updates
  app/src/lang/translations/cs-CZ.yaml
Labels: Automerge

#13613 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#13629 Remove BASIC acronym
  packages/format-title/src/acronyms.ts
Labels: Improvement, Package: format-title

#13622 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/ru-RU.yaml
Labels: Automerge

#13623 Field permissions and relational interfaces
  api/src/services/authorization.ts
  tests/api/items/many-to-many.test.ts
  tests/setup/seeds/03_directus_roles.js
  tests/setup/seeds/04_directus_users.js
  tests/setup/seeds/06_directus_permissions.js
Labels: API, Bug

#13639 Translations: Make password reset notice clearer
  app/src/lang/translations/en-US.yaml
Labels: App, Improvement

#13641 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#13352 Add comments to the .env file stub
  api/example.env
  api/package.json
  api/src/cli/utils/create-env/env-stub.liquid
  api/src/env.ts
Labels: API, Improvement

#13642 Quickstart fix
  docs/getting-started/quickstart.md
Labels: Documentation

#13646 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge
