Repository directus/directus, pull requests merged in 2022-03, with the labels that each got.

#11904 Fix access to public role permissions
  app/src/modules/settings/routes/roles/collection.vue
Labels: App, Bug

#11246 Replace union query approach with updated table scan
  api/src/database/run-ast.ts
  api/src/env.ts
  api/src/utils/apply-query.ts
  docs/configuration/config-options.md
  packages/shared/src/types/query.ts
Labels: API, Bug

#11925 add style to links in notice
  api/src/utils/apply-query.ts
  app/src/interfaces/presentation-notice/presentation-notice.vue
Labels: App, Improvement

#11924 add number to prop type for radio and dropdown
  app/src/components/v-radio/v-radio.vue
  app/src/interfaces/select-dropdown/select-dropdown.vue
  app/src/interfaces/select-radio/select-radio.vue
Labels: App

#11942 Add `authenticate` hook to implement custom auth checks against current request
  .eslintrc.js
  .github/codeql/codeql-config.yaml
  .github/workflows/codeql-analysis.yml
  api/package.json
  api/src/__mocks__/cache.ts
  api/src/middleware/authenticate.ts
  api/src/utils/is-directus-jwt.ts
  api/src/utils/jwt.ts
  api/tests/cli/index.test.ts
  api/tests/database/migrations/run.test.ts
  api/tests/integration/middleware/cache.test.ts
  api/tests/middleware/authenticate.test.ts
  api/tests/middleware/extract-token.test.ts
  api/tests/services/items.test.ts
  api/tests/services/payload.test.ts
  api/tests/unit/middleware/extract-token.test.ts
  api/tests/utils/get-cache-key.test.ts
  api/tests/utils/is-directus-jwt.test.ts
  api/tests/utils/jwt.test.ts
  api/tests/utils/merge-permissions.test.ts
  docs/extensions/hooks.md
  jest.config.js
  package-lock.json
  package.json
Labels: API, New Feature

#11945 Enable editing of Geometry types from the raw value modal
  app/src/utils/get-js-type.ts
Labels: App, Bug

#11944 Resizable navigation panel
  app/src/composables/use-local-storage.ts
  app/src/lang/translations/en-US.yaml
  app/src/views/private/private-view.vue
Labels: App, Improvement

#11768 Add check for filterPath length when not having m2o/a2o relation
  api/src/utils/apply-query.ts
Labels: API, Bug

#10418 Fix "Save as Copy" for relational fields
  app/src/composables/use-item/use-item.ts
  app/src/modules/content/routes/item.vue
Labels: App, Bug

#11954 Add "items.sort" event
  api/src/services/utils.ts
  docs/extensions/hooks.md
  docs/getting-started/installation/plesk.md
  readme.md
Labels: API, Improvement

#11955 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#11959 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11960 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11961 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11962 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11964 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11965 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11966 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11967 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11968 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11970 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11971 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11972 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11973 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11974 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11975 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11978 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11979 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11980 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11981 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11982 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11983 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11984 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11986 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11987 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11988 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11993 New Crowdin updates
  app/src/lang/translations/ro-RO.yaml
Labels: Automerge

#11994 New Crowdin updates
  app/src/lang/translations/ro-RO.yaml
Labels: Automerge

#11995 New Crowdin updates
  app/src/lang/translations/ro-RO.yaml
Labels: Automerge

#11996 New Crowdin updates
  app/src/lang/translations/ro-RO.yaml
Labels: Automerge

#11997 New Crowdin updates
  app/src/lang/translations/ro-RO.yaml
Labels: Automerge

#11999 New Crowdin updates
  app/src/lang/translations/de-DE.yaml
Labels: Automerge

#12000 New Crowdin updates
  app/src/lang/translations/pt-BR.yaml
Labels: Automerge

#12011 Fix query limit -1 for o2m queries
  api/src/database/run-ast.ts
Labels: API, Bug

#12006 add --dry-run flag to `schema apply` CLI command
  api/src/cli/commands/schema/apply.ts
  api/src/cli/index.ts
  docs/reference/cli.md
Labels: API, New Feature

#12020 Allow configuring /assets endpoint CSP separately
  api/src/controllers/assets.ts
  docs/configuration/config-options.md
Labels: API, Improvement

#12022 Default CORS to disabled
  api/src/env.ts
  docs/configuration/config-options.md
Labels: API, Notice

#12024 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#12025 Add support for import ip deny list
  api/src/env.ts
  api/src/services/files.ts
  docs/configuration/config-options.md
Labels: API, New Feature

#11330 Docs: Filters
  docs/.vuepress/config.js
  docs/.vuepress/theme/components/SidebarLinks.vue
  docs/app/filters.md
  docs/configuration/filter-rules.md
Labels: Documentation

#12034 Hide raw value copy paste button if unsupported by browser
  app/src/components/v-form/form-field-menu.vue
Labels: App, Bug

#12050 Hide nav resize handle when it is not open
  app/src/views/private/private-view.vue
Labels: App, Improvement

#12059 New Crowdin updates
  app/src/lang/translations/de-DE.yaml
  app/src/lang/translations/hr-HR.yaml
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/ro-RO.yaml
Labels: Automerge

#12060 Fix cropper aspect ratio not activating crop
  app/src/views/private/components/image-editor/image-editor.vue
Labels: App, Bug

#12047 Fix user info sidebar last access timestamp
  app/src/modules/users/components/user-info-sidebar-detail.vue
Labels: App, Bug

#12062 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#12001 Form error validation improvements
  app/src/components/v-detail/v-detail.vue
  app/src/components/v-form/v-form.vue
  app/src/components/v-form/validation-errors.vue
  app/src/composables/use-item/use-item.ts
  app/src/interfaces/group-accordion/accordion-section.vue
  app/src/interfaces/group-accordion/group-accordion.vue
  app/src/interfaces/group-detail/group-detail.vue
  app/src/interfaces/group-raw/group-raw.vue
  app/src/lang/translations/en-US.yaml
  app/src/utils/validate-item.ts
  app/src/views/private/components/drawer-item/drawer-item.vue
  packages/shared/src/composables/use-collection.ts
  packages/shared/src/types/fields.ts
Labels: App, Improvement

#12063 New Crowdin updates
  app/src/lang/translations/ar-SA.yaml
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/br-FR.yaml
  app/src/lang/translations/ca-ES.yaml
  app/src/lang/translations/cs-CZ.yaml
  app/src/lang/translations/da-DK.yaml
  app/src/lang/translations/de-DE.yaml
  app/src/lang/translations/en-CA.yaml
  app/src/lang/translations/en-GB.yaml
  app/src/lang/translations/es-419.yaml
  app/src/lang/translations/es-CL.yaml
  app/src/lang/translations/es-ES.yaml
  app/src/lang/translations/et-EE.yaml
  app/src/lang/translations/fa-IR.yaml
  app/src/lang/translations/fi-FI.yaml
  app/src/lang/translations/fr-CA.yaml
  app/src/lang/translations/fr-FR.yaml
  app/src/lang/translations/hi-IN.yaml
  app/src/lang/translations/hr-HR.yaml
  app/src/lang/translations/hu-HU.yaml
  app/src/lang/translations/id-ID.yaml
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/lt-LT.yaml
  app/src/lang/translations/nl-NL.yaml
  app/src/lang/translations/no-NO.yaml
  app/src/lang/translations/pl-PL.yaml
  app/src/lang/translations/pt-BR.yaml
  app/src/lang/translations/pt-PT.yaml
  app/src/lang/translations/ro-RO.yaml
  app/src/lang/translations/ru-RU.yaml
  app/src/lang/translations/sl-SI.yaml
  app/src/lang/translations/sr-CS.yaml
  app/src/lang/translations/sv-SE.yaml
  app/src/lang/translations/th-TH.yaml
  app/src/lang/translations/tr-TR.yaml
  app/src/lang/translations/uk-UA.yaml
  app/src/lang/translations/vi-VN.yaml
  app/src/lang/translations/zh-CN.yaml
  app/src/lang/translations/zh-TW.yaml
Labels: Automerge

#12072 New Crowdin updates
  app/src/lang/translations/ja-JP.yaml
Labels: Automerge

#12075 New Crowdin updates
  app/src/lang/translations/ja-JP.yaml
Labels: Automerge

#12076 Fix deep relational offset
  api/src/database/run-ast.ts
  tests/api/items/offset.test.ts
  tests/setup/seeds/05_directus_fields.js
Labels: API, Bug

#12038 Docs: Settings
  docs/app/settings.md
Labels: Documentation

#11728 Docs: User Directory
  docs/app/user-directory.md
Labels: Documentation

#12079 New Crowdin updates
  app/src/lang/translations/fr-FR.yaml
Labels: Automerge

#12081 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#12085 Add Croatian to available-languages.yaml
  app/src/lang/available-languages.yaml
Labels: App, Improvement

#12087 Make sure mysql error extraction won't error on slice
  api/src/exceptions/database/dialects/mysql.ts
Labels: API, Bug

#12095 New Crowdin updates
  app/src/lang/translations/fa-IR.yaml
Labels: Automerge

#12096 New Crowdin updates
  app/src/lang/translations/fa-IR.yaml
Labels: Automerge

#12088 Allow configuring overrides for the openid-client
  api/src/auth/drivers/oauth2.ts
  api/src/auth/drivers/openid.ts
Labels: API, New Feature

#12092 Remove outline prop from v-icons
  app/src/modules/insights/routes/overview.vue
  app/src/modules/settings/components/navigation.vue
  app/src/modules/settings/routes/data-model/collections/components/collection-options.vue
  app/src/modules/settings/routes/data-model/fields/components/field-select-menu.vue
  app/src/modules/settings/routes/data-model/fields/fields.vue
  app/src/modules/settings/routes/presets/collection/collection.vue
  app/src/modules/settings/routes/presets/item.vue
  app/src/modules/settings/routes/roles/collection.vue
  app/src/modules/settings/routes/roles/item/components/permissions-overview-header.vue
  app/src/modules/settings/routes/roles/item/item.vue
  app/src/modules/settings/routes/webhooks/collection.vue
  app/src/modules/settings/routes/webhooks/item.vue
  app/src/modules/users/components/navigation-role.vue
  app/src/modules/users/components/navigation.vue
  app/src/modules/users/routes/collection.vue
  app/src/modules/users/routes/item.vue
  app/src/views/private/components/comments-sidebar-detail/comment-item-header.vue
  app/src/views/private/components/header-bar-actions/header-bar-actions.vue
  app/src/views/private/components/module-bar-avatar/module-bar-avatar.vue
  app/src/views/private/components/module-bar.vue
  app/src/views/private/components/sidebar-button/sidebar-button.vue
  app/src/views/private/components/sidebar-detail/sidebar-detail.vue
  app/src/views/private/components/user-popover/user-popover.vue
  docs/getting-started/glossary.md
Labels: App, Optimization

#12097 New Crowdin updates
  app/src/lang/translations/fa-IR.yaml
Labels: Automerge

#12100 New Crowdin updates
  app/src/lang/translations/fa-IR.yaml
Labels: Automerge

#12101 New Crowdin updates
  app/src/lang/translations/fa-IR.yaml
Labels: Automerge

#12102 New Crowdin updates
  app/src/lang/translations/fa-IR.yaml
Labels: Automerge

#12103 New Crowdin updates
  app/src/lang/translations/fa-IR.yaml
Labels: Automerge

#12104 New Crowdin updates
  app/src/lang/translations/fa-IR.yaml
Labels: Automerge

#12105 New Crowdin updates
  app/src/lang/translations/fa-IR.yaml
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#12108 New Crowdin updates
  app/src/lang/translations/fa-IR.yaml
Labels: Automerge

#12122 New Crowdin updates
  app/src/lang/translations/fa-IR.yaml
Labels: Automerge

#12123 New Crowdin updates
  app/src/lang/translations/fa-IR.yaml
Labels: Automerge

#12124 New Crowdin updates
  app/src/lang/translations/fa-IR.yaml
Labels: Automerge

#12125 New Crowdin updates
  app/src/lang/translations/fa-IR.yaml
Labels: Automerge

#12126 New Crowdin updates
  app/src/lang/translations/fa-IR.yaml
Labels: Automerge

#12149 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#12150 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#12154 Upgrade table layout
  app/src/components/register.ts
  app/src/components/v-field-list/v-field-list-item.vue
  app/src/components/v-field-list/v-field-list.vue
  app/src/components/v-field-select/index.ts
  app/src/components/v-field-select/v-field-select.vue
  app/src/components/v-table/table-header.vue
  app/src/components/v-table/table-header/index.ts
  app/src/components/v-table/table-header/table-header.vue
  app/src/components/v-table/table-row.vue
  app/src/components/v-table/table-row/index.ts
  app/src/components/v-table/types.ts
  app/src/components/v-table/v-table.vue
  app/src/displays/formatted-value/formatted-value.vue
  app/src/lang/translations/en-US.yaml
  app/src/layouts/tabular/index.ts
  app/src/layouts/tabular/options.vue
  app/src/layouts/tabular/tabular.vue
  app/src/layouts/tabular/types.ts
  app/stub/empty.d.ts
  app/tsconfig.json
  vetur.config.js
Labels: App, New Feature

#12155 New Crowdin updates
  app/src/lang/translations/ar-SA.yaml
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/br-FR.yaml
  app/src/lang/translations/ca-ES.yaml
  app/src/lang/translations/cs-CZ.yaml
  app/src/lang/translations/da-DK.yaml
  app/src/lang/translations/de-DE.yaml
  app/src/lang/translations/en-CA.yaml
  app/src/lang/translations/en-GB.yaml
  app/src/lang/translations/es-419.yaml
  app/src/lang/translations/es-CL.yaml
  app/src/lang/translations/es-ES.yaml
  app/src/lang/translations/et-EE.yaml
  app/src/lang/translations/fa-IR.yaml
  app/src/lang/translations/fi-FI.yaml
  app/src/lang/translations/fr-CA.yaml
  app/src/lang/translations/fr-FR.yaml
  app/src/lang/translations/he-IL.yaml
  app/src/lang/translations/hr-HR.yaml
  app/src/lang/translations/hu-HU.yaml
  app/src/lang/translations/id-ID.yaml
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/ja-JP.yaml
  app/src/lang/translations/ms-MY.yaml
  app/src/lang/translations/nl-NL.yaml
  app/src/lang/translations/no-NO.yaml
  app/src/lang/translations/pl-PL.yaml
  app/src/lang/translations/pt-BR.yaml
  app/src/lang/translations/ro-RO.yaml
  app/src/lang/translations/ru-RU.yaml
  app/src/lang/translations/sl-SI.yaml
  app/src/lang/translations/sr-CS.yaml
  app/src/lang/translations/sv-SE.yaml
  app/src/lang/translations/th-TH.yaml
  app/src/lang/translations/tr-TR.yaml
  app/src/lang/translations/uk-UA.yaml
  app/src/lang/translations/vi-VN.yaml
  app/src/lang/translations/zh-CN.yaml
  app/src/lang/translations/zh-TW.yaml
Labels: Automerge

#11950 Docs: File Library
  docs/.vuepress/theme/styles/index.styl
  docs/app/file-library.md
Labels: Documentation

#12168 New Crowdin updates
  app/src/lang/translations/de-DE.yaml
Labels: Automerge

#12169 M2A interface collection name layout fix
  app/src/interfaces/list-m2a/list-m2a.vue
Labels: App, Bug

#12162 Prevent null field/collection translations from being merged
  app/src/stores/collections.ts
  app/src/stores/fields.ts
Labels: App, Bug

#12192 use type json for select-color presets options field
  app/src/interfaces/select-color/index.ts
Labels: App, Bug

#12157 Group groups in field select, add search when number of fields exceeds 20
  app/src/components/v-field-list/v-field-list-item.vue
  app/src/components/v-field-list/v-field-list.vue
  app/src/components/v-form/v-form.vue
  app/src/components/v-input/v-input.vue
  app/src/composables/use-field-tree.ts
  app/src/layouts/tabular/tabular.vue
  app/src/stores/fields.ts
  app/src/utils/get-with-arrays.ts
Labels: App, Improvement

#12194 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#12208 Export authorization service
  api/src/services/index.ts
Labels: API, Bug

#12217 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#12201 Add new export experience
  api/package.json
  api/src/controllers/utils.ts
  api/src/env.ts
  api/src/middleware/respond.ts
  api/src/services/import-export.ts
  api/src/services/import.ts
  api/src/services/index.ts
  api/src/utils/get-date-formatted.ts
  app/src/interfaces/_system/system-fields/index.ts
  app/src/interfaces/_system/system-fields/system-fields.vue
  app/src/lang/translations/en-US.yaml
  app/src/modules/content/routes/collection.vue
  app/src/modules/files/components/navigation-folder.vue
  app/src/modules/files/routes/collection.vue
  app/src/modules/files/routes/item.vue
  app/src/modules/users/routes/collection.vue
  app/src/views/private/components/export-sidebar-detail.vue
  app/src/views/private/components/folder-picker/folder-picker-list-item.vue
  app/src/views/private/components/folder-picker/folder-picker.vue
  docs/configuration/config-options.md
  docs/reference/system/utilities.md
  package-lock.json
  packages/shared/src/composables/use-collection.ts
  packages/shared/src/types/collection.ts
  packages/shared/src/types/notifications.ts
Labels: API, App, New Feature

#12219 New Crowdin updates
  app/src/lang/translations/ar-SA.yaml
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/br-FR.yaml
  app/src/lang/translations/ca-ES.yaml
  app/src/lang/translations/da-DK.yaml
  app/src/lang/translations/de-DE.yaml
  app/src/lang/translations/en-CA.yaml
  app/src/lang/translations/en-GB.yaml
  app/src/lang/translations/es-419.yaml
  app/src/lang/translations/es-CL.yaml
  app/src/lang/translations/es-ES.yaml
  app/src/lang/translations/et-EE.yaml
  app/src/lang/translations/fa-IR.yaml
  app/src/lang/translations/fi-FI.yaml
  app/src/lang/translations/fr-CA.yaml
  app/src/lang/translations/fr-FR.yaml
  app/src/lang/translations/hr-HR.yaml
  app/src/lang/translations/hu-HU.yaml
  app/src/lang/translations/id-ID.yaml
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/lt-LT.yaml
  app/src/lang/translations/nl-NL.yaml
  app/src/lang/translations/no-NO.yaml
  app/src/lang/translations/pl-PL.yaml
  app/src/lang/translations/pt-BR.yaml
  app/src/lang/translations/pt-PT.yaml
  app/src/lang/translations/ro-RO.yaml
  app/src/lang/translations/ru-RU.yaml
  app/src/lang/translations/sl-SI.yaml
  app/src/lang/translations/sr-CS.yaml
  app/src/lang/translations/sv-SE.yaml
  app/src/lang/translations/th-TH.yaml
  app/src/lang/translations/tr-TR.yaml
  app/src/lang/translations/uk-UA.yaml
  app/src/lang/translations/zh-CN.yaml
  app/src/lang/translations/zh-TW.yaml
Labels: Automerge

#12220 Add direct download option to files interface
  app/src/interfaces/files/files.vue
  app/src/lang/translations/en-US.yaml
Labels: App, Improvement

#12226 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#12227 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#12222 fix number input step up/down when undefined
  app/src/components/v-input/v-input.vue
  app/src/interfaces/input/input.vue
Labels: App, Bug

#12218 Fix WYSIWYG link keyboard shortcut and add parent anchor tag detection
  app/src/interfaces/input-rich-text-html/input-rich-text-html.vue
  app/src/interfaces/input-rich-text-html/useLink.ts
Labels: App, Bug

#12223 Tweak tags placeholder for clarity
  app/src/lang/translations/en-US.yaml
Labels: App, Improvement

#12228 New Crowdin updates
  app/src/lang/translations/ar-SA.yaml
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/br-FR.yaml
  app/src/lang/translations/ca-ES.yaml
  app/src/lang/translations/da-DK.yaml
  app/src/lang/translations/de-DE.yaml
  app/src/lang/translations/en-CA.yaml
  app/src/lang/translations/en-GB.yaml
  app/src/lang/translations/es-419.yaml
  app/src/lang/translations/es-CL.yaml
  app/src/lang/translations/es-ES.yaml
  app/src/lang/translations/et-EE.yaml
  app/src/lang/translations/fa-IR.yaml
  app/src/lang/translations/fi-FI.yaml
  app/src/lang/translations/fr-CA.yaml
  app/src/lang/translations/fr-FR.yaml
  app/src/lang/translations/hr-HR.yaml
  app/src/lang/translations/hu-HU.yaml
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/lt-LT.yaml
  app/src/lang/translations/nl-NL.yaml
  app/src/lang/translations/pl-PL.yaml
  app/src/lang/translations/pt-BR.yaml
  app/src/lang/translations/ro-RO.yaml
  app/src/lang/translations/ru-RU.yaml
  app/src/lang/translations/sl-SI.yaml
  app/src/lang/translations/sr-CS.yaml
  app/src/lang/translations/sv-SE.yaml
  app/src/lang/translations/th-TH.yaml
  app/src/lang/translations/tr-TR.yaml
  app/src/lang/translations/zh-CN.yaml
  app/src/lang/translations/zh-TW.yaml
Labels: Automerge

#12229 Style updates
  app/src/components/v-badge/v-badge.vue
  app/src/components/v-button/v-button.vue
  app/src/components/v-checkbox/v-checkbox.vue
  app/src/components/v-date-picker/flatpickr-overrides.css
  app/src/components/v-input/v-input.vue
  app/src/components/v-notice/v-notice.vue
  app/src/components/v-slider/v-slider.vue
  app/src/components/v-textarea/v-textarea.vue
  app/src/interfaces/datetime/datetime.vue
  app/src/interfaces/input-rich-text-html/tinymce-overrides.css
  app/src/interfaces/select-color/select-color.vue
  app/src/lang/translations/en-US.yaml
  app/src/layouts/cards/components/card.vue
  app/src/modules/settings/routes/data-model/collections/collections.vue
  app/src/modules/settings/routes/data-model/new-collection.vue
  app/src/styles/_colors.scss
  app/src/styles/lib/_codemirror.scss
  app/src/styles/themes/_dark.scss
  app/src/views/private/components/file-preview/file-preview.vue
Labels: App, Improvement

#12232 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#12216 Improvements to WYSIWYG interface
  app/src/components/v-form/v-form.vue
  app/src/interfaces/input-rich-text-html/input-rich-text-html.vue
  app/src/interfaces/input-rich-text-html/useImage.ts
  app/src/interfaces/input-rich-text-html/useLink.ts
  app/src/interfaces/input-rich-text-html/useMedia.ts
  app/src/interfaces/input-rich-text-html/useSourceCode.ts
Labels: API, Bug

#12017 Add lock for system cache
  api/src/cache.ts
  api/src/controllers/utils.ts
  api/src/services/collections.ts
  api/src/services/fields.ts
  api/src/services/graphql.ts
  api/src/services/permissions.ts
  api/src/services/relations.ts
  api/src/utils/get-permissions.ts
  api/src/utils/get-schema.ts
Labels: API, Bug

#12235 Fix nested relational limit for m2o fetching
  api/src/database/run-ast.ts
Labels: API, Bug

#12241 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
Labels: Automerge

#12242 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
Labels: Automerge

#12243 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
Labels: Automerge

#12260 Fix being able to export a relational field that is within a group
  app/src/composables/use-field-tree.ts
Labels: App, Bug

#12276 Fix field preview background color
  app/src/styles/themes/_dark.scss
Labels: App, Improvement

#12279 Fix color translation keys
  app/src/interfaces/select-color/select-color.vue
Labels: App, Bug

#12280 Fix start setting of detail group
  app/src/interfaces/group-detail/group-detail.vue
Labels: App, Bug

#11836 Prevent errors when using string filters with empty values
  packages/shared/src/utils/generate-joi.test.ts
  packages/shared/src/utils/generate-joi.ts
Labels: App, Bug, Package: shared

#12190 Add query filter validation with permissions
  api/src/services/authorization.ts
  api/tests/__test-utils__/items-utils.ts
  api/tests/__test-utils__/schemas.ts
  api/tests/services/items.test.ts
Labels: API, Bug

#12130 Fix incorrect order of migrations when reverting
  api/src/database/migrations/run.ts
Labels: API, Bug

#12284 Fix groups in v-field-template
  app/src/components/v-field-template/field-list-item.vue
  app/src/components/v-field-template/types.ts
  app/src/components/v-field-template/v-field-template.vue
  app/src/composables/use-field-tree.ts
Labels: App, Bug

#12141 Prefix existing field typecasting flags with "cast-"
  api/src/database/migrations/20220322A-rename-field-typecast-flags.ts
  api/src/database/system-data/fields/collections.yaml
  api/src/database/system-data/fields/fields.yaml
  api/src/database/system-data/fields/files.yaml
  api/src/database/system-data/fields/panels.yaml
  api/src/database/system-data/fields/permissions.yaml
  api/src/database/system-data/fields/presets.yaml
  api/src/database/system-data/fields/relations.yaml
  api/src/database/system-data/fields/revisions.yaml
  api/src/database/system-data/fields/roles.yaml
  api/src/database/system-data/fields/settings.yaml
  api/src/database/system-data/fields/users.yaml
  api/src/database/system-data/fields/webhooks.yaml
  api/src/services/payload.ts
  api/src/utils/get-local-type.ts
  api/tests/services/payload.test.ts
  app/src/modules/settings/routes/data-model/field-detail/store/alterations/standard.ts
Labels: API, Improvement

#12300 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/fr-CA.yaml
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#12309 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#12311 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#12314 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/zh-CN.yaml
Labels: Automerge

#12315 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/zh-CN.yaml
Labels: Automerge

#12328 Fix inconsistent delete action payload
  api/src/services/items.ts
Labels: API, Bug

#12324 Add shortcut from data model to collection content
  app/src/lang/translations/de-DE.yaml
  app/src/lang/translations/en-CA.yaml
  app/src/lang/translations/en-GB.yaml
  app/src/lang/translations/en-US.yaml
  app/src/modules/settings/routes/data-model/collections/components/collection-options.vue
Labels: App, Improvement

#12310 Save last accessed collection in Content Module
  app/src/modules/content/index.ts
  app/src/modules/content/routes/collection-or-item.vue
Labels: App, Improvement

#12312 Prevent M2M item edits without permission via app
  app/src/interfaces/list-m2m/list-m2m.vue
  app/src/interfaces/list-m2m/use-permissions.ts
Labels: App, Bug

#12316 Disable dashboard/panel actions based on permissions
  app/src/components/v-button/v-button.vue
  app/src/modules/insights/routes/dashboard.vue
  app/src/modules/insights/routes/overview.vue
Labels: App, Bug

#12330 Fix auto-casting of array like values in env
  api/src/env.ts
Labels: API, Bug

#12332 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#12349 fix: cast translation strings as json
  api/src/database/system-data/fields/settings.yaml
Labels: API, Bug

#12351 Fix activity fields using invalid display
  api/src/database/system-data/fields/activity.yaml
Labels: API, Bug

#12353 Fix translation drawer delete button hover style
  app/src/modules/settings/routes/translation-strings/translation-strings-drawer.vue
Labels: App, Bug

#12342 fix LOGGER_LEVELS array being split as string
  api/src/logger.ts
  api/tests/env.test.ts
  api/tests/utils/get-config-from-env.test.ts
Labels: API, Bug

#12362 Docs dark mode
  docs/.vuepress/styles/colors.styl
  docs/.vuepress/theme/styles/code.styl
Labels: Documentation

#12371 Fix action for updateAllowed in M2M usePermissions
  app/src/interfaces/list-m2m/use-permissions.ts
Labels: App, Bug

#12374 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
Labels: Automerge

#12375 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/uk-UA.yaml
Labels: Automerge

#12376 New Crowdin updates
  app/src/lang/translations/uk-UA.yaml
Labels: Automerge

#12378 New Crowdin updates
  app/src/lang/translations/uk-UA.yaml
Labels: Automerge

#12379 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/uk-UA.yaml
Labels: Automerge

#12381 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
Labels: Automerge

#12385 Fix deep _limit -1 not resolving all items
  api/src/database/run-ast.ts
Labels: API, Bug

#12372 Fix typecast migration array
  api/src/database/migrations/20220322A-rename-field-typecast-flags.ts
  api/src/database/migrations/20220325A-fix-typecast-flags.ts
Labels: API, Bug

#12320 Update system-filter interface to use v-field-list
  app/src/components/v-field-list/v-field-list.vue
  app/src/interfaces/_system/system-filter/nodes.vue
  app/src/interfaces/_system/system-filter/system-filter.vue
Labels: App, Bug
