Repository directus/directus, pull requests merged in 2022-02, with the labels that each got.

#11370 New Crowdin updates
  app/src/lang/translations/ro-RO.yaml
Labels: Automerge

#11371 New Crowdin updates
  app/src/lang/translations/ro-RO.yaml
Labels: Automerge

#11372 New Crowdin updates
  app/src/lang/translations/ro-RO.yaml
Labels: Automerge

#11373 New Crowdin updates
  app/src/lang/translations/ro-RO.yaml
  app/src/lang/translations/ru-RU.yaml
Labels: Automerge

#11375 New Crowdin updates
  app/src/lang/translations/ro-RO.yaml
Labels: Automerge

#11377 New Crowdin updates
  app/src/lang/translations/ro-RO.yaml
Labels: Automerge

#11381 Add a few missing DefinitelyTyped dependencies
  api/package.json
  api/src/utils/md.ts
  package-lock.json
  packages/cli/package.json
  packages/cli/src/core/output/ui.ts
Labels: Optimization

#11329 Mark shared as side effects free
  packages/shared/package.json
Labels: Bug, Extensions, Package: shared

#11390 New Crowdin updates
  app/src/lang/translations/pt-BR.yaml
Labels: Automerge

#11391 New Crowdin updates
  app/src/lang/translations/pt-BR.yaml
Labels: Automerge

#11393 New Crowdin updates
  app/src/lang/translations/pt-BR.yaml
Labels: Automerge

#11394 New Crowdin updates
  app/src/lang/translations/pt-BR.yaml
Labels: Automerge

#11396 New Crowdin updates
  app/src/lang/translations/pt-BR.yaml
Labels: Automerge

#11397 New Crowdin updates
  app/src/lang/translations/pt-BR.yaml
Labels: Automerge

#11402 New Crowdin updates
  app/src/lang/translations/es-419.yaml
Labels: Automerge

#11403 New Crowdin updates
  app/src/lang/translations/es-419.yaml
Labels: Automerge

#11404 New Crowdin updates
  app/src/lang/translations/pt-BR.yaml
Labels: Automerge

#11405 New Crowdin updates
  app/src/lang/translations/pt-BR.yaml
Labels: Automerge

#11406 New Crowdin updates
  app/src/lang/translations/pt-BR.yaml
Labels: Automerge

#11407 New Crowdin updates
  app/src/lang/translations/pt-BR.yaml
Labels: Automerge

#11412 Fix performance drop in stacked drawer when many layers
  app/src/styles/_stacked-drawers.scss
Labels: App, Improvement

#11415 Add missing error translations
  app/src/lang/translations/en-US.yaml
Labels: App, Improvement

#11416 New Crowdin updates
  app/src/lang/translations/de-DE.yaml
  app/src/lang/translations/fr-CA.yaml
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/pl-PL.yaml
  app/src/lang/translations/ro-RO.yaml
Labels: Automerge

#11419 New Crowdin updates
  app/src/lang/translations/ko-KR.yaml
Labels: Automerge

#10828 Add strings to accepted fields for Insights Panel "Metrics"
  app/src/modules/insights/components/panel.vue
  app/src/modules/insights/components/workspace.vue
  app/src/modules/insights/routes/dashboard.vue
  app/src/modules/insights/routes/panel-configuration.vue
  app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-display.vue
  app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-interface.vue
  app/src/modules/settings/routes/data-model/field-detail/field-detail-simple/field-configuration.vue
  app/src/modules/settings/routes/data-model/field-detail/shared/extension-options.vue
  app/src/panels/index.ts
  app/src/panels/metric/index.ts
  app/src/panels/metric/metric.vue
  app/src/types/insights.ts
  packages/shared/src/types/panels.ts
Labels: App, Improvement

#9421 Fix translations layout
  app/src/displays/translations/index.ts
  app/src/displays/translations/translations.vue
Labels: App, Bug, Improvement

#11069 Prevent MySQL collation errors
  api/src/database/index.ts
Labels: API, Bug, DB: MySQL, Improvement, Notice

#11336 Added / amended env vars in docs example for Google Cloud Logging
  docs/getting-started/installation/gcp.md
Labels: Documentation

#11423 Don't parse preset object as filter structure
  api/src/utils/get-permissions.ts
  packages/shared/src/utils/parse-filter.ts
Labels: API, Bug

#11279 Resolve transaction unreliability issues in schema alterations
  api/src/services/collections.ts
  api/src/services/fields.ts
  tests/api/collections.test.ts
  tests/api/ping.test.ts
  tests/config.ts
  tests/schema.png
Labels: API, Bug, Improvement

#11428 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#11431 Fix items not loaded in relational modal
  app/src/interfaces/translations/translations.vue
Labels: App, Bug

#10882 fix fields validation to include field presets
  app/src/composables/use-item/use-item.ts
Labels: App, Bug

#11432 Fix not being able to delete folder in data-model
  api/src/services/collections.ts
  tests/api/collections.test.ts
Labels: API, Bug

#11438 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
Labels: Automerge

#11455 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#11454 Fix Metrics type panel creation
  app/src/panels/metric/index.ts
Labels: App, Bug

#11493 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#11485 Fix GCP Kubernetes Engine typo
  docs/getting-started/installation/gcp.md
Labels: Documentation

#11488 Fixes reference to documentation about environment variables.
  docs/getting-started/installation/docker.md
Labels: Documentation

#11494 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#11495 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#11496 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#11497 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#11498 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#11499 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#11433 Fix text when deleting data-model folder
  app/src/lang/translations/en-US.yaml
  app/src/modules/settings/routes/data-model/collections/components/collection-options.vue
Labels: App, Improvement

#11500 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#11505 New Crowdin updates
  app/src/lang/translations/en-GB.yaml
Labels: Automerge

#11508 New Crowdin updates
  app/src/lang/translations/en-GB.yaml
Labels: Automerge

#11511 New Crowdin updates
  app/src/lang/translations/da-DK.yaml
Labels: Automerge

#11519 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#11523 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#11520 Fix o2m interface selection issues
  app/src/interfaces/list-o2m/list-o2m.vue
Labels: App, Bug

#11524 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#11526 Fix soft limit overflowing
  app/src/interfaces/input-multiline/input-multiline.vue
  app/src/interfaces/input-rich-text-html/input-rich-text-html.vue
  app/src/interfaces/input-rich-text-md/input-rich-text-md.vue
Labels: App, Bug

#11525 fix directus_notifications default app access permissions fields not returning as array
  api/src/database/system-data/app-access-permissions/app-access-permissions.yaml
Labels: API, Bug

#11527 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#11528 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#11529 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#11530 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#11539 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#11561 Add delete share translation
  app/src/lang/translations/en-US.yaml
  app/src/views/private/components/shares-sidebar-detail/shares-sidebar-detail.vue
Labels: App, Improvement

#11560 Add shares to app access minimum permissions
  api/src/database/system-data/app-access-permissions/app-access-permissions.yaml
  app/src/modules/settings/routes/roles/app-permissions.ts
Labels: API, Bug

#11562 New Crowdin updates
  app/src/lang/translations/en-GB.yaml
  app/src/lang/translations/hr-HR.yaml
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#11564 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#11569 Fix share items hidden by adblockers
  app/src/views/private/components/shares-sidebar-detail/share-item.vue
Labels: App, Bug

#11570 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#11573 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
Labels: Automerge

#11578 New Crowdin updates
  app/src/lang/translations/de-DE.yaml
Labels: Automerge

#11583 minor typo in google cloud documentation
  docs/getting-started/installation/gcp.md
Labels: Documentation

#11598 New Crowdin updates
  app/src/lang/translations/zh-CN.yaml
Labels: Automerge

#11639 New Crowdin updates
  app/src/lang/translations/nl-NL.yaml
Labels: Automerge

#11644 New Crowdin updates
  app/src/lang/translations/nl-NL.yaml
Labels: Automerge

#11647 New Crowdin updates
  app/src/lang/translations/nl-NL.yaml
Labels: Automerge

#11656 Merge token claims and userinfo in openid flow
  api/src/auth/drivers/openid.ts
Labels: API, Improvement

#11670 Emit value before unmounting datepicker
  app/src/components/v-date-picker/v-date-picker.vue
Labels: App, Bug

#11640 Add required field indicators to accordion group
  app/src/interfaces/group-accordion/accordion-section.vue
Labels: App, Improvement

#11286 Fix notifications position when sidebar is open
  app/src/views/private/components/notifications-group/notifications-group.vue
  app/src/views/private/private-view.vue
Labels: App, Improvement

#11599 Auto fill display text when adding link in WYSIWYG
  app/src/interfaces/input-rich-text-html/useLink.ts
Labels: App, Improvement

#11584 Remove relation from store when translations field is deleted
  app/src/stores/fields.ts
Labels: App, Bug

#11582 Fix nested M2O field breaking parent M2O preview
  app/src/interfaces/select-dropdown-m2o/select-dropdown-m2o.vue
Labels: App, Bug

#11503 Prevent filter's datepicker closing on month nav
  app/src/interfaces/_system/system-filter/input-component.vue
Labels: App, Bug

#11501 Fix roles in users module navigation not updating
  app/src/modules/users/composables/use-navigation.ts
Labels: App, Bug

#11482 Prevent literal interpolation on null translations & apply to collection translations
  app/src/stores/collections.ts
  app/src/stores/fields.ts
Labels: App, Bug

#11469 Fix translations interface divider's margin top
  app/src/interfaces/translations/translations.vue
Labels: App, Bug

#11444 Prevent selection of Foreign Keys for collection sort
  api/src/database/system-data/fields/collections.yaml
  app/src/interfaces/_system/system-field/system-field.vue
Labels: API, Bug

#11567 Fix m2o interface display issues
  app/src/interfaces/select-dropdown-m2o/select-dropdown-m2o.vue
Labels: App, Bug

#11204 SDK: split `readMany` into itself and `readByQuery`
  docs/reference/sdk.md
  packages/cli/src/cli/commands/items/read/many.ts
  packages/sdk/jest.config.js
  packages/sdk/src/base/items.ts
  packages/sdk/src/items.ts
  packages/sdk/tests/items.test.ts
Labels: Improvement, Package: sdk, Notice

#11441 Prevent creation of relationships on primary keys
  api/src/services/relations.ts
Labels: API, Bug

#11672 Add nested translations support
  app/src/interfaces/translations/translations.vue
Labels: App, Bug

#10548 Remove access token from asset url when unnecessary
  app/src/interfaces/input-rich-text-html/get-editor-styles.ts
  app/src/interfaces/input-rich-text-html/input-rich-text-html.vue
  app/src/interfaces/input-rich-text-html/useImage.ts
  app/src/interfaces/input-rich-text-html/useLink.ts
  app/src/interfaces/input-rich-text-html/useMedia.ts
  app/src/interfaces/input-rich-text-html/useSourceCode.ts
  app/src/interfaces/input-rich-text-md/input-rich-text-md.vue
  app/src/lang/translations/en-US.yaml
Labels: App, Bug

#11675 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#11685 Fix alias fields not showing up in permissions
  app/src/composables/use-field-tree.ts
  app/src/stores/fields.ts
Labels: App, Bug

#11682 validate first user email during installation
  api/src/cli/commands/init/index.ts
Labels: API, Bug

#11681 Fix context menu directive's deactivate event
  app/src/directives/context-menu/context-menu.ts
  app/src/directives/context-menu/readme.md
  app/src/modules/files/components/navigation-folder.vue
Labels: App, Bug

#11687 Update docs: plesk document_root
  docs/assets/guides/installation/plesk-screenshot.png
  docs/getting-started/installation/plesk.md
Labels: Documentation

#11690 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#11691 New Crowdin updates
  app/src/lang/translations/es-ES.yaml
Labels: Automerge

#11705 add "press enter to close" for time inputs
  app/src/components/v-date-picker/v-date-picker.vue
  app/src/interfaces/_system/system-filter/input-component.vue
  app/src/interfaces/datetime/datetime.vue
Labels: App, Improvement

#11703 Align displayed time for 24 hours format
  app/src/interfaces/datetime/datetime.vue
  app/src/lang/translations/en-US.yaml
Labels: App, Improvement

#11698 CLI docs Tip: Create date based snapshots
  docs/reference/cli.md
Labels: Documentation

#11708 New Crowdin updates
  app/src/lang/translations/es-419.yaml
  app/src/lang/translations/es-CL.yaml
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#11709 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#11702 Show collection notes
  app/src/lang/translations/en-US.yaml
  app/src/modules/settings/routes/data-model/collections/collections.vue
  app/src/modules/settings/routes/data-model/collections/components/collection-item.vue
Labels: App, Improvement

#11689 Update rollup-plugin-styles to v4
  api/package.json
  docs/getting-started/installation/plesk.md
  docs/reference/cli.md
  package-lock.json
  packages/extensions-sdk/package.json
  packages/format-title/package.json
  packages/sdk/package.json
Labels: Dependencies

#11712 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#11715 New Crowdin updates
  app/src/lang/translations/ru-RU.yaml
Labels: Automerge

#11718 New Crowdin updates
  app/src/lang/translations/ru-RU.yaml
Labels: Automerge

#11741 New Crowdin updates
  app/src/lang/translations/es-ES.yaml
Labels: Automerge

#11744 New Crowdin updates
  app/src/lang/translations/ro-RO.yaml
Labels: Automerge

#11745 New Crowdin updates
  app/src/lang/translations/ro-RO.yaml
Labels: Automerge

#11746 Fix translations resetting for new records
  app/src/interfaces/translations/translations.vue
Labels: App, Bug

#11763 New Crowdin updates
  app/src/lang/translations/id-ID.yaml
Labels: Automerge

#11764 New Crowdin updates
  app/src/lang/translations/id-ID.yaml
Labels: Automerge

#11767 Chinese translation optimization: item → 条目 not 项目
  app/src/lang/translations/zh-CN.yaml
Labels: App, Improvement

#11761 Show errors for Save as Copy action
  app/src/composables/use-item/use-item.ts
Labels: App, Bug

#11762 Hide certain save options for users without create permission
  app/src/composables/use-permissions.ts
  app/src/modules/content/routes/item.vue
  app/src/modules/files/routes/item.vue
  app/src/modules/users/routes/item.vue
Labels: App, Bug

#11769 fix copy/paste for readonly code interface
  app/src/interfaces/input-code/input-code.vue
Labels: App, Bug

#11771 fix permission for field functions
  api/src/services/authorization.ts
Labels: API, Bug

#11634 Docs: update CSS and pics
  .stylelintignore
  docs/.vuepress/config.js
  docs/.vuepress/public/favicon.svg
  docs/.vuepress/public/manifest.json
  docs/.vuepress/styles/colors.styl
  docs/.vuepress/theme/components/AlgoliaSearchBox.vue
  docs/.vuepress/theme/components/NavLinks.vue
  docs/.vuepress/theme/components/Navbar.vue
  docs/.vuepress/theme/components/SidebarLink.vue
  docs/.vuepress/theme/layouts/Homepage.vue
  docs/.vuepress/theme/styles/code.styl
  docs/.vuepress/theme/styles/custom-blocks.styl
  docs/.vuepress/theme/styles/index.styl
  docs/app/content.md
  docs/app/file-library.md
  docs/app/insights.md
  docs/app/user-directory.md
  docs/assets/app-overview.svg
  docs/configuration/relationships.md
  docs/getting-started/quickstart.md
  docs/reference/files.md
  package.json
Labels: Documentation

#11780 New Crowdin updates
  app/src/lang/translations/hr-HR.yaml
Labels: Automerge

#11781 Fix dark mode for docs
  docs/.vuepress/styles/colors.styl
  docs/.vuepress/theme/styles/code.styl
Labels: Documentation

#11782 Docs dark mode fix v2
  docs/.vuepress/styles/colors.styl
  docs/.vuepress/theme/components/header-background/Dark.vue
  docs/.vuepress/theme/components/header-background/Light.vue
  docs/.vuepress/theme/layouts/Homepage.vue
Labels: Documentation

#11662 Fixed readByQuery's sort parameter in custom API endpoint example
  docs/extensions/endpoints.md
Labels: Documentation

#11784 Fix video size within in-app docs
  app/src/views/private/components/docs-wrapper/docs-wrapper.vue
Labels: App, Bug

#11796 fix map interface extension options
  app/src/modules/settings/routes/data-model/field-detail/shared/extension-options.vue
Labels: App, Bug

#11815 add missing directus_shares note
  app/src/lang/translations/en-US.yaml
Labels: App, Bug

#11816 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/es-CL.yaml
  app/src/lang/translations/hr-HR.yaml
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/pl-PL.yaml
  app/src/lang/translations/ro-RO.yaml
  app/src/lang/translations/zh-CN.yaml
Labels: Automerge

#11820 New Crowdin updates
  app/src/lang/translations/de-DE.yaml
Labels: Automerge

#11822 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#11750 Fix anonymous binding ldap
  api/src/auth/drivers/ldap.ts
  docs/configuration/config-options.md
Labels: API, Improvement

#11799 LDAP handle posix groups
  api/src/auth/drivers/ldap.ts
Labels: API, Improvement

#11819 Update plesk docs: Create / apply snapshots
  docs/getting-started/installation/plesk.md
Labels: Documentation

#11831 New Crowdin updates
  app/src/lang/translations/de-DE.yaml
  app/src/lang/translations/zh-CN.yaml
Labels: Automerge

#11833 New Crowdin updates
  app/src/lang/translations/zh-CN.yaml
Labels: Automerge

#11855 Clarify default role ID format for SSO
  docs/configuration/sso.md
Labels: Documentation

#11854 Close date picker on select
  app/src/components/v-date-picker/v-date-picker.vue
Labels: App, Improvement

#11872 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#11876 New Crowdin updates
  app/src/lang/translations/mn-MN.yaml
Labels: Automerge

#11874 Update available-languages.yaml
  app/src/lang/available-languages.yaml
Labels: App, New Feature

#11882 Redirect to page not found for collections that do not exist
  app/src/modules/settings/index.ts
Labels: App, Bug

#11787 Allow target="_blank" in markdown sanitization
  app/src/utils/md.ts
Labels: App, Improvement

#11783 Datetime interface improvements
  app/src/interfaces/datetime/datetime.vue
Labels: App, Improvement

#11617 Avoid get database when authenticate with JWT
  api/src/middleware/authenticate.ts
Labels: API, Improvement

#11686 Adds Deploy with Koyeb.
  readme.md
Labels: Documentation

#11465 Support listen parameter
  api/example.env
  api/src/cli/utils/create-env/env-stub.liquid
  api/src/env.ts
  api/src/server.ts
  docs/configuration/config-options.md
Labels: API, New Feature

#11516 Docker: Add support for changing the timezone
  docker/Dockerfile
Labels: Docker, New Feature
