Repository directus/directus, pull requests merged in 2022-01, with the labels that each got.

#10802 New Crowdin updates
  app/src/lang/translations/id-ID.yaml
Labels: Automerge

#10803 New Crowdin updates
  app/src/lang/translations/id-ID.yaml
Labels: Automerge

#10805 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#10807 Add Deploy with Cleavr to Readme
  readme.md
Labels: Documentation

#10811 Add LinkedIn to special case list
  packages/format-title/src/special-case.ts
Labels: Package: format-title

#10814 add translations for project descriptor & shares fields
  app/src/lang/translations/en-US.yaml
Labels: App, Bug

#10815 New Crowdin updates
  app/src/lang/translations/af-ZA.yaml
  app/src/lang/translations/ar-SA.yaml
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/br-FR.yaml
  app/src/lang/translations/ca-ES.yaml
  app/src/lang/translations/cs-CZ.yaml
  app/src/lang/translations/da-DK.yaml
  app/src/lang/translations/de-DE.yaml
  app/src/lang/translations/el-GR.yaml
  app/src/lang/translations/en-GB.yaml
  app/src/lang/translations/es-419.yaml
  app/src/lang/translations/es-CL.yaml
  app/src/lang/translations/es-ES.yaml
  app/src/lang/translations/et-EE.yaml
  app/src/lang/translations/fa-IR.yaml
  app/src/lang/translations/fi-FI.yaml
  app/src/lang/translations/fr-FR.yaml
  app/src/lang/translations/he-IL.yaml
  app/src/lang/translations/hi-IN.yaml
  app/src/lang/translations/hu-HU.yaml
  app/src/lang/translations/id-ID.yaml
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/ja-JP.yaml
  app/src/lang/translations/ka-GE.yaml
  app/src/lang/translations/lt-LT.yaml
  app/src/lang/translations/ms-MY.yaml
  app/src/lang/translations/nl-NL.yaml
  app/src/lang/translations/no-NO.yaml
  app/src/lang/translations/pl-PL.yaml
  app/src/lang/translations/pt-BR.yaml
  app/src/lang/translations/pt-PT.yaml
  app/src/lang/translations/ro-RO.yaml
  app/src/lang/translations/ru-RU.yaml
  app/src/lang/translations/sk-SK.yaml
  app/src/lang/translations/sl-SI.yaml
  app/src/lang/translations/sr-CS.yaml
  app/src/lang/translations/sr-SP.yaml
  app/src/lang/translations/sv-SE.yaml
  app/src/lang/translations/th-TH.yaml
  app/src/lang/translations/tr-TR.yaml
  app/src/lang/translations/uk-UA.yaml
  app/src/lang/translations/vi-VN.yaml
  app/src/lang/translations/zh-CN.yaml
  app/src/lang/translations/zh-TW.yaml
Labels: Automerge

#10816 minor fix for form closing tag in file upload example
  docs/reference/sdk.md
Labels: Documentation

#10817 New Crowdin updates
  app/src/lang/translations/zh-CN.yaml
Labels: Automerge

#10818 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
Labels: Automerge

#10820 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#10823 New Crowdin updates
  app/src/lang/translations/fa-IR.yaml
Labels: Automerge

#10812 prevent icons from being searchable
  app/src/components/v-icon/v-icon.vue
Labels: App, Bug

#10813 update docs on descriptor in project settings
  docs/configuration/project-settings.md
  docs/reference/system/settings.md
Labels: Documentation

#10827 Docs(SDK): use top level await upload
  docs/reference/sdk.md
Labels: Documentation

#10819 Fix logo url in shared view
  app/src/views/shared/shared-view.vue
Labels: App, Bug

#10821 fix file local type for displaysForType
  api/src/utils/get-local-type.ts
Labels: API, Bug

#10830 Default to upgrade-insecure-requests turned off
  api/src/app.ts
Labels: API, Improvement

#10837 Api (Assets): fix UUID verification
  api/src/services/assets.ts
Labels: API, Bug

#10836 Left Join-ing on roles to allow users without roles to login
  api/src/database/migrations/run.ts
  api/src/services/authentication.ts
  tests/e2e/api/auth/login.test.ts
  tests/e2e/setup/seeds/04_directus_users.js
Labels: API, Bug

#10848 New Crowdin updates
  app/src/lang/translations/es-ES.yaml
Labels: Automerge

#10847 Fix running migrations in dev mode
  api/src/database/migrations/run.ts
Labels: API, Bug

#10846 Fix reloading hooks with schedule events
  api/src/extensions.ts
  package-lock.json
Labels: API, Bug

#10861 New Crowdin updates
  app/src/lang/translations/no-NO.yaml
Labels: Automerge

#10849 Make registered extensions accessible from extensions
  app/src/composables/use-system.ts
  packages/extensions-sdk/src/index.ts
  packages/shared/src/composables/use-system.ts
  packages/shared/src/constants/injection.ts
  packages/shared/src/types/extensions.ts
Labels: Extensions, New Feature

#10852 Add CSP directives for MapLibre to work
  api/src/app.ts
Labels: API, Bug

#10870 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#10850 Move useLayout composable to shared and expose it through extensions-sdk
  app/src/modules/activity/routes/collection.vue
  app/src/modules/content/routes/collection.vue
  app/src/modules/files/routes/collection.vue
  app/src/modules/settings/routes/presets/item.vue
  app/src/modules/settings/routes/webhooks/collection.vue
  app/src/modules/users/routes/collection.vue
  app/src/views/private/components/drawer-collection/drawer-collection.vue
  packages/extensions-sdk/src/index.ts
  packages/shared/src/composables/index.ts
  packages/shared/src/composables/use-layout.ts
Labels: Extensions, Improvement

#10873 New Crowdin updates
  app/src/lang/translations/de-DE.yaml
Labels: Automerge

#10872 Use new date picker in filter, allow manual input
  app/src/interfaces/_system/system-filter/input-component.vue
Labels: App, Improvement

#10875 Fix refresh token payload structure on shared refresh
  api/src/services/authentication.ts
Labels: API, Bug

#10877 New Crowdin updates
  app/src/lang/translations/de-DE.yaml
Labels: Automerge

#10879 Handle broken images more gracefully
  app/src/interfaces/file/file.vue
  app/src/modules/users/routes/item.vue
  app/src/views/private/components/module-bar-avatar/module-bar-avatar.vue
Labels: App, Improvement

#10891 Clarify case rules for storage env vars
  docs/configuration/config-options.md
Labels: Documentation

#10881 Add extension auto reloading to the API
  api/package.json
  api/src/cli/index.ts
  api/src/controllers/extensions.ts
  api/src/env.ts
  api/src/extensions.ts
  api/src/services/graphql.ts
  package-lock.json
Labels: API, Extensions, New Feature

#10895 Fix color width inconsistency
  app/src/interfaces/select-color/select-color.vue
Labels: App, Bug

#10903 Fix user info sidebar watcher causing error
  app/src/modules/users/components/user-info-sidebar-detail.vue
Labels: App, Bug

#10926 New Crowdin updates
  app/src/lang/translations/ro-RO.yaml
Labels: Automerge

#10937 New Crowdin updates
  app/src/lang/translations/fr-FR.yaml
Labels: Automerge

#10943 fix Read By Query example code
  docs/reference/sdk.md
Labels: Documentation

#10946 New Crowdin updates
  app/src/lang/translations/zh-CN.yaml
Labels: Automerge

#10922 Add documentation for EXTENSIONS_AUTO_RELOAD
  docs/configuration/config-options.md
  docs/extensions/creating-extensions.md
Labels: Documentation, Extensions

#10955 Delete required hooks only once
  api/src/extensions.ts
  package-lock.json
Labels: API, Optimization

#10951 Filter UI tweaks
  app/src/interfaces/_system/system-filter/nodes.vue
  app/src/interfaces/_system/system-filter/system-filter.vue
  app/src/lang/translations/en-US.yaml
Labels: App, Improvement

#10945 App (Presets): Fix delete reactivity
  app/src/modules/content/components/navigation-bookmark.vue
  app/src/modules/settings/routes/presets/collection/collection.vue
  app/src/modules/settings/routes/presets/item.vue
  app/src/stores/presets.ts
Labels: App, Bug

#10957 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/de-DE.yaml
  app/src/lang/translations/es-419.yaml
  app/src/lang/translations/es-CL.yaml
  app/src/lang/translations/fr-FR.yaml
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#10944 add last_page to minimal permissions on app side
  app/src/modules/settings/routes/roles/app-permissions.ts
Labels: App, Improvement

#10959 Use consistent background color on image interface
  app/src/interfaces/file-image/file-image.vue
Labels: App, Bug

#10961 New Crowdin updates
  app/src/lang/translations/es-419.yaml
Labels: Automerge

#10960 Allow passing 'version' to Knex
  api/src/database/index.ts
  docs/configuration/config-options.md
Labels: API, Improvement

#10962 New Crowdin updates
  app/src/lang/translations/es-419.yaml
Labels: Automerge

#10963 New Crowdin updates
  app/src/lang/translations/es-419.yaml
Labels: Automerge

#10965 New Crowdin updates
  app/src/lang/translations/fa-IR.yaml
Labels: Automerge

#10977 Fix project name overflow
  app/src/components/v-text-overflow.vue
  app/src/directives/tooltip/tooltip.ts
  app/src/stores/user.ts
  app/src/views/private/components/project-info/project-info.vue
Labels: App, Bug

#10970 show items without archive value in all items view
  app/src/modules/content/routes/collection.vue
Labels: App, Bug

#10982 New Crowdin updates
  app/src/lang/translations/en-CA.yaml
  app/src/lang/translations/fr-CA.yaml
Labels: Automerge

#10983 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#10984 New Crowdin updates
  app/src/lang/translations/en-CA.yaml
  app/src/lang/translations/fr-CA.yaml
Labels: Automerge

#10985 Add relations tab for file type fields
  app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-tabs.vue
Labels: App, Improvement

#10994 New Crowdin updates
  app/src/lang/translations/es-419.yaml
Labels: Automerge

#10993 Set minimum value for string field length to 1
  app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-schema.vue
Labels: App, Bug

#10991 Improve Width for Search Input & Filters
  app/src/interfaces/_system/system-filter/nodes.vue
  app/src/interfaces/_system/system-filter/system-filter.vue
  app/src/views/private/components/search-input/search-input.vue
Labels: App, Improvement

#10936 Installation guide for Google Cloud Platform
  docs/.vuepress/config.js
  docs/getting-started/installation.md
  docs/getting-started/installation/gcp.md
  docs/getting-started/installation/manual.md
  docs/reference/cli.md
  docs/reference/system/server.md
  readme.md
Labels: Documentation

#10911 Adds possible extra pino logger options through env vars
  api/src/logger.ts
  docs/configuration/config-options.md
Labels: API, Documentation, New Feature

#10998 New Crowdin updates
  app/src/lang/translations/es-419.yaml
  app/src/lang/translations/fr-CA.yaml
  app/src/lang/translations/fr-FR.yaml
Labels: Automerge

#10999 New Crowdin updates
  app/src/lang/translations/es-419.yaml
Labels: Automerge

#11004 New Crowdin updates
  app/src/lang/translations/es-419.yaml
Labels: Automerge

#11005 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/es-419.yaml
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#11006 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#11019 New Crowdin updates
  app/src/lang/translations/id-ID.yaml
Labels: Automerge

#11020 New Crowdin updates
  app/src/lang/translations/vi-VN.yaml
Labels: Automerge

#11016 `has-edits` as part of `use-item`
  app/src/composables/use-item/use-item.ts
  app/src/modules/content/routes/item.vue
  app/src/modules/files/routes/item.vue
  app/src/modules/settings/routes/roles/item/item.vue
  app/src/modules/settings/routes/webhooks/item.vue
  app/src/modules/users/routes/item.vue
Labels: App, Improvement

#11015 Minor Shares UX Improvements
  app/src/lang/translations/en-US.yaml
  app/src/views/private/components/shares-sidebar-detail/share-item.vue
  app/src/views/private/components/shares-sidebar-detail/shares-sidebar-detail.vue
Labels: App, Improvement

#11027 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/fr-CA.yaml
  app/src/lang/translations/fr-FR.yaml
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#11014 Move danger styling to field-select-menu component
  app/src/modules/settings/routes/data-model/fields/components/field-select-menu.vue
  app/src/modules/settings/routes/data-model/fields/components/field-select.vue
Labels: App, Improvement

#11018 App: `use-edits-guard`
  app/src/composables/unsaved-changes/index.ts
  app/src/composables/unsaved-changes/unsaved-changes.ts
  app/src/composables/use-edits-guard/index.ts
  app/src/composables/use-edits-guard/use-edits-guard.ts
  app/src/modules/content/routes/item.vue
  app/src/modules/files/routes/item.vue
  app/src/modules/settings/routes/data-model/fields/fields.vue
  app/src/modules/settings/routes/presets/item.vue
  app/src/modules/settings/routes/project/project.vue
  app/src/modules/settings/routes/roles/item/item.vue
  app/src/modules/settings/routes/webhooks/item.vue
  app/src/modules/users/routes/item.vue
Labels: App, Improvement

#11030 New Crowdin updates
  app/src/lang/translations/ku-TR.yaml
Labels: Automerge

#11031 New Crowdin updates
  app/src/lang/translations/ku-TR.yaml
Labels: Automerge

#11033 New Crowdin updates
  app/src/lang/translations/ku-TR.yaml
Labels: Automerge

#11038 Update Running Locally docs to have correct paths in commands
  docs/contributing/running-locally.md
Labels: Documentation, Tests

#11053 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#11070 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11071 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11072 New Crowdin updates
  app/src/lang/translations/tr-TR.yaml
Labels: Automerge

#11073 New Crowdin updates
  app/src/lang/translations/id-ID.yaml
Labels: Automerge

#11074 New Crowdin updates
  app/src/lang/translations/vi-VN.yaml
Labels: Automerge

#11085 break word for code tags in custom blocks
  docs/.vuepress/theme/styles/custom-blocks.styl
Labels: Documentation

#11100 Always inline dynamic imports when bundling extensions
  packages/extensions-sdk/src/cli/commands/build.ts
Labels: Extensions, Improvement

#11103 Make email_notifications column a translated name
  app/src/lang/translations/en-US.yaml
Labels: App, Improvement

#11096 Add Unsupported Media Type Exception
  api/src/controllers/files.ts
  api/src/controllers/utils.ts
  api/src/exceptions/index.ts
  api/src/exceptions/unsupported-media-type.ts
  api/src/services/import.ts
  docs/reference/introduction.md
Labels: API, Bug, Improvement

#11104 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
Labels: Automerge

#11091 Fix missing/removed translations
  app/src/lang/translations/af-ZA.yaml
  app/src/lang/translations/ar-SA.yaml
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/br-FR.yaml
  app/src/lang/translations/ca-ES.yaml
  app/src/lang/translations/cs-CZ.yaml
  app/src/lang/translations/da-DK.yaml
  app/src/lang/translations/de-DE.yaml
  app/src/lang/translations/el-GR.yaml
  app/src/lang/translations/en-CA.yaml
  app/src/lang/translations/en-GB.yaml
  app/src/lang/translations/en-US.yaml
  app/src/lang/translations/es-419.yaml
  app/src/lang/translations/es-CL.yaml
  app/src/lang/translations/es-ES.yaml
  app/src/lang/translations/et-EE.yaml
  app/src/lang/translations/fa-IR.yaml
  app/src/lang/translations/fi-FI.yaml
  app/src/lang/translations/fr-CA.yaml
  app/src/lang/translations/fr-FR.yaml
  app/src/lang/translations/hu-HU.yaml
  app/src/lang/translations/id-ID.yaml
  app/src/lang/translations/ja-JP.yaml
  app/src/lang/translations/ka-GE.yaml
  app/src/lang/translations/lt-LT.yaml
  app/src/lang/translations/ms-MY.yaml
  app/src/lang/translations/nl-NL.yaml
  app/src/lang/translations/no-NO.yaml
  app/src/lang/translations/pt-BR.yaml
  app/src/lang/translations/pt-PT.yaml
  app/src/lang/translations/ro-RO.yaml
  app/src/lang/translations/ru-RU.yaml
  app/src/lang/translations/sl-SI.yaml
  app/src/lang/translations/sr-CS.yaml
  app/src/lang/translations/sr-SP.yaml
  app/src/lang/translations/sv-SE.yaml
  app/src/lang/translations/th-TH.yaml
  app/src/lang/translations/uk-UA.yaml
  app/src/lang/translations/vi-VN.yaml
  app/src/lang/translations/zh-CN.yaml
  app/src/lang/translations/zh-TW.yaml
Labels: App

#11099 Remove extensions-sdk and axios from the list of shared deps
  packages/shared/src/constants/extensions.ts
Labels: Extensions, Improvement

#11107 New Crowdin updates
  app/src/lang/translations/af-ZA.yaml
  app/src/lang/translations/ar-SA.yaml
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/br-FR.yaml
  app/src/lang/translations/ca-ES.yaml
  app/src/lang/translations/cs-CZ.yaml
  app/src/lang/translations/da-DK.yaml
  app/src/lang/translations/de-DE.yaml
  app/src/lang/translations/el-GR.yaml
  app/src/lang/translations/en-CA.yaml
  app/src/lang/translations/en-GB.yaml
  app/src/lang/translations/es-419.yaml
  app/src/lang/translations/es-CL.yaml
  app/src/lang/translations/es-ES.yaml
  app/src/lang/translations/et-EE.yaml
  app/src/lang/translations/fa-IR.yaml
  app/src/lang/translations/fi-FI.yaml
  app/src/lang/translations/fr-CA.yaml
  app/src/lang/translations/fr-FR.yaml
  app/src/lang/translations/hu-HU.yaml
  app/src/lang/translations/id-ID.yaml
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/ja-JP.yaml
  app/src/lang/translations/ka-GE.yaml
  app/src/lang/translations/lt-LT.yaml
  app/src/lang/translations/ms-MY.yaml
  app/src/lang/translations/nl-NL.yaml
  app/src/lang/translations/no-NO.yaml
  app/src/lang/translations/pl-PL.yaml
  app/src/lang/translations/pt-BR.yaml
  app/src/lang/translations/pt-PT.yaml
  app/src/lang/translations/ro-RO.yaml
  app/src/lang/translations/ru-RU.yaml
  app/src/lang/translations/sl-SI.yaml
  app/src/lang/translations/sr-CS.yaml
  app/src/lang/translations/sr-SP.yaml
  app/src/lang/translations/sv-SE.yaml
  app/src/lang/translations/th-TH.yaml
  app/src/lang/translations/tr-TR.yaml
  app/src/lang/translations/uk-UA.yaml
  app/src/lang/translations/vi-VN.yaml
  app/src/lang/translations/zh-CN.yaml
  app/src/lang/translations/zh-TW.yaml
Labels: Automerge

#11111 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#11112 Handle errors while pre-bundling App extensions more gracefully
  api/src/extensions.ts
Labels: API, Bug

#11113 Only watch entrypoints of local extensions for changes
  api/src/extensions.ts
Labels: API, Improvement

#11081 Make skipping of workflows work again
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/lint.yml
  .github/workflows/unit-tests.yml
Labels: Bug, Tests

#11106 Rename sourceMaps flag to sourcemap to align with other tools and add no-minify flag to the extensions-sdk CLI
  packages/extensions-sdk/src/cli/commands/build.ts
  packages/extensions-sdk/src/cli/run.ts
Labels: Extensions, Improvement, Notice

#11108 Add alert about nested alias
  docs/reference/query.md
Labels: Documentation

#11084 Fix collection options menu clicks
  app/src/modules/settings/routes/data-model/collections/components/collection-item.vue
  app/src/modules/settings/routes/data-model/collections/components/collection-options.vue
Labels: App, Bug

#11079 Removed OpenID token fetching from OAuth flow
  api/src/auth/drivers/oauth2.ts
  api/src/auth/drivers/openid.ts
Labels: API, Improvement

#11077 Fixed broken auth SQL on Oracle
  api/src/services/authentication.ts
Labels: API, Bug, DB: Oracle

#11118 Upgrade dependencies
  app/package.json
  app/src/utils/md.ts
  package-lock.json
  packages/cli/package.json
Labels: App, Dependencies, Package: cli

#11121 New Crowdin updates
  app/src/lang/translations/id-ID.yaml
Labels: Automerge

#11123 New Crowdin updates
  app/src/lang/translations/id-ID.yaml
Labels: Automerge

#11126 New Crowdin updates
  app/src/lang/translations/id-ID.yaml
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#11128 New Crowdin updates
  app/src/lang/translations/id-ID.yaml
Labels: Automerge

#11130 New Crowdin updates
  app/src/lang/translations/id-ID.yaml
Labels: Automerge

#11131 New Crowdin updates
  app/src/lang/translations/id-ID.yaml
Labels: Automerge

#11133 New Crowdin updates
  app/src/lang/translations/id-ID.yaml
Labels: Automerge

#11134 New Crowdin updates
  app/src/lang/translations/id-ID.yaml
Labels: Automerge

#11144 New Crowdin updates
  app/src/lang/translations/de-DE.yaml
Labels: Automerge

#11145 New Crowdin updates
  app/src/lang/translations/de-DE.yaml
Labels: Automerge

#11129 Fix auth refresh issue
  api/src/services/authentication.ts
Labels: API, Bug

#11164 Only render project descriptor if it is set
  app/src/views/private/components/project-info/project-info.vue
Labels: App, Improvement

#11094 Enable end-to-end tests for Oracle and SQLite
  .github/workflows/ci.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/lint.yml
  .github/workflows/unit-tests.yml
  package-lock.json
  package.json
  tests/e2e/api/items/many-to-many.test.ts
  tests/e2e/api/items/no-relations.test.ts
  tests/e2e/config.ts
  tests/e2e/get-dbs-to-test.ts
  tests/e2e/setup/migrations/20211016054403_create_base_tables.js
  tests/e2e/setup/setup.ts
  tests/e2e/setup/utils/await-connection.ts
  tests/e2e/setup/utils/factories.ts
Labels: DB: Oracle, DB: SQLite, New Feature, Tests

#11162 Added the 4 "_starts/ends_with" filter operators to type defs in SDK
  packages/sdk/src/items.ts
Labels: Improvement, Package: sdk

#11163 Clean up emitting "items" events
  api/src/emitter.ts
  api/src/services/items.ts
Labels: API, Optimization

#11167 Removed unused session data type
  api/src/types/auth.ts
Labels: Optimization

#11169 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
Labels: Automerge

#11170 Only trigger edits guard if there are edits
  app/src/composables/use-edits-guard/use-edits-guard.ts
  app/src/modules/content/routes/item.vue
  app/src/modules/files/routes/item.vue
  app/src/modules/settings/routes/data-model/fields/fields.vue
  app/src/modules/settings/routes/presets/item.vue
  app/src/modules/settings/routes/project/project.vue
  app/src/modules/settings/routes/roles/item/item.vue
  app/src/modules/settings/routes/webhooks/item.vue
  app/src/modules/users/routes/item.vue
Labels: App, Bug

#11116 Disable login form when AUTH_DISABLE_DEFAULT is enabled
  app/src/routes/login/login.vue
Labels: App, Improvement

#11171 Fix a prop type check in the advanced schema drawer
  app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-schema.vue
Labels: App, Optimization

#11174 Improve end-to-end test displayed results
  tests/e2e/api/auth/login.test.ts
  tests/e2e/api/items/filters.test.ts
  tests/e2e/api/items/many-to-many.test.ts
  tests/e2e/api/items/no-relations.test.ts
  tests/e2e/api/items/one-to-many.test.ts
  tests/e2e/api/ping.test.ts
Labels: Improvement, Tests

#8467 Remove marginTop option from presentation divider
  app/src/components/v-form/v-form.vue
  app/src/interfaces/presentation-divider/index.ts
  app/src/interfaces/presentation-divider/presentation-divider.vue
Labels: App, Bug

#11041 moved sso doc over to configurations
  docs/.vuepress/config.js
  docs/configuration/sso.md
Labels: Bug, Documentation

#11183 New Crowdin updates
  app/src/lang/translations/zh-CN.yaml
Labels: Automerge

#11184 New Crowdin updates
  app/src/lang/translations/zh-CN.yaml
Labels: Automerge

#11179 Moving schema and relation types into shared package
  api/src/auth/auth.ts
  api/src/cli/commands/bootstrap/index.ts
  api/src/database/migrations/20210518A-add-foreign-key-constraints.ts
  api/src/database/run-ast.ts
  api/src/database/system-data/relations/index.ts
  api/src/services/authentication.ts
  api/src/services/authorization.ts
  api/src/services/collections.ts
  api/src/services/fields.ts
  api/src/services/graphql.ts
  api/src/services/import.ts
  api/src/services/items.ts
  api/src/services/mail/index.ts
  api/src/services/meta.ts
  api/src/services/payload.ts
  api/src/services/relations.ts
  api/src/services/server.ts
  api/src/services/specifications.ts
  api/src/services/users.ts
  api/src/services/utils.ts
  api/src/types/ast.ts
  api/src/types/auth.ts
  api/src/types/extensions.ts
  api/src/types/index.ts
  api/src/types/relation.ts
  api/src/types/services.ts
  api/src/types/snapshot.ts
  api/src/utils/apply-query.ts
  api/src/utils/apply-snapshot.ts
  api/src/utils/get-ast-from-query.ts
  api/src/utils/get-permissions.ts
  api/src/utils/get-relation-type.ts
  api/src/utils/get-schema.ts
  api/src/utils/get-snapshot.ts
  api/src/utils/merge-permissions-for-share.ts
  api/src/utils/reduce-schema.ts
  packages/shared/src/types/extensions.ts
  packages/shared/src/types/index.ts
  packages/shared/src/types/relations.ts
  packages/shared/src/types/schema.ts
Labels: API, Optimization

#10113 Implement CockroachDB support
  api/example.env
  api/package.json
  api/src/cli/commands/init/questions.ts
  api/src/cli/utils/create-db-connection.ts
  api/src/cli/utils/drivers.ts
  api/src/database/helpers/date/index.ts
  api/src/database/helpers/geometry/index.ts
  api/src/database/helpers/index.ts
  api/src/database/helpers/schema/dialects/cockroachdb.ts
  api/src/database/helpers/schema/dialects/default.ts
  api/src/database/helpers/schema/dialects/oracle.ts
  api/src/database/helpers/schema/index.ts
  api/src/database/helpers/schema/types.ts
  api/src/database/index.ts
  api/src/database/migrations/20201105B-change-webhook-url-type.ts
  api/src/database/migrations/20210312A-webhooks-collections-text.ts
  api/src/database/migrations/20210415A-make-filesize-nullable.ts
  api/src/database/migrations/20210510A-restructure-relations.ts
  api/src/database/migrations/20210525A-add-insights.ts
  api/src/database/migrations/20210626A-change-filesize-bigint.ts
  api/src/database/migrations/20210903A-add-auth-provider.ts
  api/src/database/migrations/20210907A-webhooks-collections-not-null.ts
  api/src/database/migrations/20210920A-webhooks-url-not-null.ts
  api/src/database/migrations/20211211A-add-shares.ts
  api/src/database/seeds/01-collections.yaml
  api/src/database/seeds/02-roles.yaml
  api/src/database/seeds/03-users.yaml
  api/src/exceptions/database/translate.ts
  api/src/services/collections.ts
  api/src/services/fields.ts
  docker-compose.yml
  package-lock.json
  packages/schema/package.json
  packages/schema/src/index.ts
  tests/docker-compose.yml
  tests/e2e/api/items/many-to-many.test.ts
  tests/e2e/api/items/no-relations.test.ts
  tests/e2e/config.ts
  tests/e2e/get-dbs-to-test.ts
  tests/e2e/setup/migrations/20211016054403_create_base_tables.js
  tests/e2e/setup/utils/factories.test.ts
  tests/readme.md
Labels: API, Package: schema

#11188 Align readMany and readByQuery in SDK
  docs/reference/sdk.md
Labels: Documentation

#11009 Add soft character limit to various inputs
  app/jest.config.js
  app/package.json
  app/src/interfaces/input-multiline/index.ts
  app/src/interfaces/input-multiline/input-multiline.vue
  app/src/interfaces/input-rich-text-html/index.ts
  app/src/interfaces/input-rich-text-html/input-rich-text-html.vue
  app/src/interfaces/input-rich-text-md/index.ts
  app/src/interfaces/input-rich-text-md/input-rich-text-md.vue
  app/src/interfaces/input/index.ts
  app/src/interfaces/input/input.vue
  app/src/lang/translations/en-US.yaml
  app/src/utils/percentage.ts
  app/tests/utils/percentage.test.ts
  app/tsconfig.json
  package-lock.json
Labels: App, New Feature

#11189 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/de-DE.yaml
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#11050 Add CSV/JSON Import capability via App
  api/src/services/import.ts
  app/src/components/register.ts
  app/src/lang/translations/en-US.yaml
  app/src/modules/content/routes/collection.vue
  app/src/views/private/components/export-sidebar-detail.vue
  app/src/views/private/components/export-sidebar-detail/export-sidebar-detail.vue
  app/src/views/private/components/export-sidebar-detail/index.ts
  docs/app/content-collections.md
Labels: App, New Feature

#11190 New Crowdin updates
  app/src/lang/translations/ar-SA.yaml
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/br-FR.yaml
  app/src/lang/translations/ca-ES.yaml
  app/src/lang/translations/cs-CZ.yaml
  app/src/lang/translations/da-DK.yaml
  app/src/lang/translations/de-DE.yaml
  app/src/lang/translations/en-CA.yaml
  app/src/lang/translations/en-GB.yaml
  app/src/lang/translations/es-419.yaml
  app/src/lang/translations/es-CL.yaml
  app/src/lang/translations/es-ES.yaml
  app/src/lang/translations/et-EE.yaml
  app/src/lang/translations/fa-IR.yaml
  app/src/lang/translations/fi-FI.yaml
  app/src/lang/translations/fr-CA.yaml
  app/src/lang/translations/fr-FR.yaml
  app/src/lang/translations/hu-HU.yaml
  app/src/lang/translations/id-ID.yaml
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/ko-KR.yaml
  app/src/lang/translations/lt-LT.yaml
  app/src/lang/translations/nl-NL.yaml
  app/src/lang/translations/no-NO.yaml
  app/src/lang/translations/pl-PL.yaml
  app/src/lang/translations/pt-BR.yaml
  app/src/lang/translations/pt-PT.yaml
  app/src/lang/translations/ru-RU.yaml
  app/src/lang/translations/sl-SI.yaml
  app/src/lang/translations/sr-CS.yaml
  app/src/lang/translations/sv-SE.yaml
  app/src/lang/translations/th-TH.yaml
  app/src/lang/translations/tr-TR.yaml
  app/src/lang/translations/uk-UA.yaml
  app/src/lang/translations/vi-VN.yaml
  app/src/lang/translations/zh-CN.yaml
  app/src/lang/translations/zh-TW.yaml
Labels: Automerge

#11191 Remove API extension types from the API
  api/src/emitter.ts
  api/src/extensions.ts
  api/src/types/extensions.ts
  api/src/types/index.ts
  api/src/webhooks.ts
  packages/shared/src/types/events.ts
  packages/shared/src/types/hooks.ts
  packages/shared/src/types/index.ts
Labels: API, Optimization

#11193 Set CRDB options to avoid inconsistencies between vendors
  api/src/cli/utils/create-db-connection.ts
  api/src/database/index.ts
  packages/schema/src/dialects/postgres.ts
  tests/e2e/config.ts
Labels: API, Bug

#11198 New Crowdin updates
  app/src/lang/translations/fr-FR.yaml
Labels: Automerge

#11201 New Crowdin updates
  app/src/lang/translations/hi-IN.yaml
Labels: Automerge

#11203 Update knex-schema-inspector
  api/package.json
  package-lock.json
  packages/schema/package.json
Labels: Dependencies

#11205 New Crowdin updates
  app/src/lang/translations/it-IT.yaml
Labels: Automerge

#11208 Integration tests for ItemsService user tables
  api/tests/__test-utils__/items-utils.ts
  api/tests/__test-utils__/schemas.ts
  api/tests/services/ItemsService.test.ts
  api/tests/services/items.test.ts
Labels: API, Tests

#11214 New Crowdin updates
  app/src/lang/translations/ru-RU.yaml
Labels: Automerge

#11215 New Crowdin updates
  app/src/lang/translations/ru-RU.yaml
Labels: Automerge

#11216 New Crowdin updates
  app/src/lang/translations/pl-PL.yaml
Labels: Automerge

#11235 New Crowdin updates
  app/src/lang/translations/bg-BG.yaml
Labels: Automerge

#11232 Remove no-break space characters with regular spaces
  .github/workflows/ci.yml
  api/README.md
  api/src/database/migrations/20210506A-rename-interfaces.ts
  app/src/stores/presets.ts
  docker/Dockerfile
  docs/extensions/endpoints.md
Labels: Optimization

#11224 Change "register" for "handler" in the example
  docs/extensions/endpoints.md
Labels: Documentation

#11227 Fix nested transactions on SQLite
  api/src/services/collections.ts
  api/src/services/fields.ts
  tests/e2e/config.ts
Labels: API, Bug
