Repository directus/directus, pull requests merged in 2024-10, with the labels that each got.

#23774 Fix defaults reactivity in kanban layout
  .changeset/moody-dogs-attack.md
  app/src/layouts/kanban/index.ts
Labels: Bug

#23821 Fix health check for cloudinary driver
  .changeset/pretty-birds-agree.md
  packages/storage-driver-cloudinary/src/index.ts
Labels: Bug, ⚠️ Enterprise

#23639 Cache bust image when generating previews
  .changeset/cold-cheetahs-double.md
  api/src/services/assets.ts
  packages/storage-driver-azure/src/index.test.ts
  packages/storage-driver-azure/src/index.ts
  packages/storage-driver-cloudinary/src/index.test.ts
  packages/storage-driver-cloudinary/src/index.ts
  packages/storage-driver-gcs/src/index.test.ts
  packages/storage-driver-gcs/src/index.ts
  packages/storage-driver-local/src/index.test.ts
  packages/storage-driver-local/src/index.ts
  packages/storage-driver-s3/src/index.test.ts
  packages/storage-driver-s3/src/index.ts
  packages/storage-driver-supabase/src/index.test.ts
  packages/storage-driver-supabase/src/index.ts
  packages/storage/src/index.ts
  pnpm-lock.yaml
Labels: Bug, ⚠️ Enterprise

#21241 Add support for batch editing on o2m & m2m tables
  .changeset/nervous-weeks-sing.md
  app/src/interfaces/list-m2m/list-m2m.vue
  app/src/interfaces/list-o2m/list-o2m.vue
  app/src/modules/content/routes/item.vue
  app/src/views/private/components/drawer-batch.vue
Labels: Feature

#23853 Properly quoted 'none' in the CSP
  api/src/controllers/assets.ts
Labels: Bug

#23851 Fix 16683 - Deletion fails for schema apply sometimes
  .changeset/brown-planes-jam.md
  api/src/utils/apply-diff.ts
Labels: Bug, ⚠️ Enterprise, Data Modeling

#22666 SDK: Throw errors when present in JSON responses
  .changeset/strange-kangaroos-roll.md
  sdk/src/utils/extract-data.ts
  sdk/src/utils/request.ts
Labels: Improvement

#23877 Fix SDK relation type
  .changeset/kind-bottles-share.md
  docs/reference/system/relations.md
  sdk/src/rest/commands/read/relations.ts
Labels: :cake: Improvement

#23888 Refresh the schema when creating new collections
  api/src/permissions/modules/validate-access/lib/validate-item-access.test.ts
  api/src/services/collections.ts
Labels: Bug, Regression

#23896 Add additional tests for `validateItemAccess`
  api/src/permissions/modules/validate-access/lib/validate-item-access.test.ts
Labels: :cake: Improvement
