Repository directus/directus, pull requests merged in 2024-04, with the labels that each got.

#22029 Fix randomUUID import in Webhooks deprecation migration
  api/src/database/migrations/20240311A-deprecate-webhooks.ts
Labels: :cake: Bug

#22035 Fix code in react real-time chat guide
  contributors.yml
  docs/guides/real-time/chat/react.md
Labels: :file_folder: Documentation

#22034 Fix marketplace pagination not allowing partial pages
  .changeset/weak-needles-film.md
  app/src/modules/settings/routes/marketplace/routes/registry/registry.vue
Labels: :cake: Bug, :file_folder: Marketplace

#21857 Fix migration for module bundle extensions
  .changeset/hip-books-smell.md
  api/src/database/migrations/20240204A-marketplace.ts
Labels: :cake: Bug, :file_folder: Extensions

#22002 Support _contains operation for CSV type
  .changeset/slimy-paws-cough.md
  packages/utils/shared/generate-joi.test.ts
  packages/utils/shared/generate-joi.ts
  packages/utils/shared/validate-payload.test.ts
Labels: :cake: Bug, :warning: Enterprise, :file_folder: Validation

#21792 Handle empty translations in translations test
  app/src/lang/translations.test.ts
Labels: :cake: Optimization, :cake: Chore

#22050 Fix initial values for boolean filter operators in search interface
  .changeset/tough-lobsters-poke.md
  app/src/interfaces/_system/system-filter/system-filter.vue
  packages/utils/shared/get-filter-operators-for-type.ts
Labels: :cake: Improvement, :warning: Enterprise, :file_folder: Filtering

#22053 Fix issue when duplicating an item (Save as Copy) with many relational items
  .changeset/small-socks-hug.md
  app/src/composables/use-item.ts
Labels: :cake: Optimization, :warning: Enterprise, :file_folder: Forms

#21786 Fix active state of Collections in navigation with Content Versions and Bookmarks
  .changeset/quiet-penguins-drop.md
  app/src/components/v-list-item.vue
  app/src/modules/content/components/navigation-item-content.vue
  app/src/modules/content/components/navigation-item.vue
  app/src/modules/content/index.ts
Labels: :cake: Optimization

#22064 Remove label for dependabot PRs
  .github/dependabot.yml
Labels: :cake: Chore

#22071 Override default label for dependabot PRs
  .github/dependabot.yml
Labels: :cake: Chore

#21824 Improve schema retrieval by caching the schema cache creation
  .changeset/shaggy-pens-try.md
  api/src/cache.ts
  api/src/utils/get-schema.ts
Labels: :cake: Improvement, :warning: Enterprise, :file_folder: Caching

#22096 Fix extensions breaking change in blackbox tests
  tests/blackbox/extensions/action-verify-create/index.mjs
  tests/blackbox/extensions/action-verify-create/package.json
  tests/blackbox/extensions/action-verify-schema/index.mjs
  tests/blackbox/extensions/action-verify-schema/package.json
Labels: :cake: Chore

#22106 Remove `v-image` deprecation notice
  docs/releases/breaking-changes.md
Labels: :file_folder: Documentation

#22027 Use Item/PrimaryKey from and move Alterations to `@directus/types`
  .changeset/stale-fishes-watch.md
  api/src/controllers/collections.ts
  api/src/controllers/dashboards.ts
  api/src/controllers/files.ts
  api/src/controllers/flows.ts
  api/src/controllers/folders.ts
  api/src/controllers/items.ts
  api/src/controllers/notifications.ts
  api/src/controllers/operations.ts
  api/src/controllers/panels.ts
  api/src/controllers/permissions.ts
  api/src/controllers/presets.ts
  api/src/controllers/roles.ts
  api/src/controllers/shares.ts
  api/src/controllers/translations.ts
  api/src/controllers/users.ts
  api/src/controllers/versions.ts
  api/src/operations/item-create/index.ts
  api/src/operations/item-read/index.ts
  api/src/operations/item-update/index.ts
  api/src/services/activity.ts
  api/src/services/authorization.ts
  api/src/services/files.ts
  api/src/services/flows.ts
  api/src/services/graphql/index.ts
  api/src/services/items.ts
  api/src/services/notifications.ts
  api/src/services/operations.ts
  api/src/services/payload.ts
  api/src/services/permissions/index.ts
  api/src/services/revisions.ts
  api/src/services/roles.ts
  api/src/services/shares.ts
  api/src/services/tfa.ts
  api/src/services/users.ts
  api/src/services/utils.ts
  api/src/services/webhooks.ts
  api/src/types/items.ts
  api/src/types/services.ts
  api/src/utils/merge-version-data.ts
  api/src/utils/validate-keys.ts
  app/src/views/private/components/drawer-item.vue
  packages/types/src/items.ts
Labels: :cake: Chore

#22123 Update TinyMCE (used for WYSIWYG) to v7
  .changeset/nice-windows-brush.md
  app/package.json
  app/src/interfaces/input-rich-text-html/input-rich-text-html.vue
  app/src/interfaces/input-rich-text-html/tinymce-overrides.css
  pnpm-lock.yaml
Labels: :cake: Optimization, :file_folder: Forms

#22112 Update Editor.js (used for Block Interface) to 2.29
  .changeset/shaggy-readers-approve.md
  app/package.json
  pnpm-lock.yaml
Labels: :cake: Optimization, :file_folder: Forms

#22141 Fix wrong trigger type `hook` to correct `event` in flows.md
  contributors.yml
  docs/reference/system/flows.md
Labels: :file_folder: Documentation

#22134 Omit `target` attribute when `newTab` is `false`
  .changeset/good-pumas-drop.md
  app/src/interfaces/input-rich-text-html/useLink.ts
  contributors.yml
Labels: :cake: Bug, :file_folder: Forms

#22155 Add env variables to configure PM2 log paths + documentation
  .changeset/lazy-bears-tan.md
  contributors.yml
  docs/self-hosted/config-options.md
  ecosystem.config.cjs
Labels: :cake: Improvement

#22162 Tweak default email in `init` cli command email_from config
  .changeset/yellow-baboons-walk.md
  api/src/cli/utils/create-env/env-stub.liquid
Labels: :cake: Improvement, :file_folder: Environment Variables, :file_folder: Email

#22170 Fix sample in Re-Usable Components guide
  docs/guides/headless-cms/reusable-components.md
Labels: :file_folder: Documentation

#22184 Api / Graphql : Allow `version` as singleton argument on singleton
  .changeset/khaki-pillows-collect.md
  api/src/services/graphql/index.ts
  docs/reference/items.md
Labels: :warning: Enterprise, :file_folder: GraphQL

#22175 Api / Assets: Prevent backpressure on sending big files
  .changeset/dirty-buttons-judge.md
  api/src/controllers/assets.ts
Labels: :warning: Enterprise, :file_folder: Assets

#22049 Fix nested queries with unlimited default limit
  .changeset/orange-crabs-work.md
  api/src/database/run-ast.ts
Labels: :cake: Bug, :file_folder: REST

#22203 Don't influence Cache-Control through `CACHE_AUTO_PURGE`
  .changeset/giant-laws-rhyme.md
  api/src/utils/get-cache-headers.test.ts
  api/src/utils/get-cache-headers.ts
Labels: :cake: Improvement, :warning: Enterprise, :file_folder: REST

#22204 Fix issue where background color of the search input did not match the navigation bar
  .changeset/dull-ants-relate.md
  app/src/modules/content/components/navigation.vue
Labels: :cake: Optimization

#22208 Fix pagination alignment in M2A builder interface
  .changeset/tough-bikes-sparkle.md
  app/src/interfaces/list-m2a/list-m2a.vue
Labels: :cake: Improvement

#22209 Fix visual inconsistency in filter interface
  .changeset/silent-buckets-care.md
  app/src/interfaces/_system/system-filter/input-group.vue
Labels: :cake: Improvement

#22230 API: Prevent endless loop on `get-schema`
  .changeset/afraid-cats-listen.md
  api/src/utils/get-schema.ts
  docs/self-hosted/config-options.md
  packages/env/src/constants/defaults.ts
  packages/env/src/constants/directus-variables.ts
  packages/env/src/constants/type-map.ts
  tests/blackbox/common/config.ts
Labels: :warning: Enterprise, :file_folder: Caching

#22231 Api: Bubble up the error to prevent `unhandledRejection`
  .changeset/lemon-cobras-draw.md
  api/src/utils/get-schema.ts
Labels: :cake: Bug, :warning: Enterprise, :file_folder: Caching

#22234 Api: Clear system cache only if specified on `/utils/cache/clear`
  .changeset/long-bottles-perform.md
  api/src/controllers/utils.ts
  api/src/services/utils.ts
  docs/reference/system/utilities.md
Labels: :cake: Improvement, :warning: Breaking Change, :warning: Enterprise, :file_folder: Caching

#22255 Fix live preview target URL with search parameters
  .changeset/long-toes-pull.md
  app/src/modules/content/routes/item.vue
Labels: :cake: Bug, :file_folder: Live Preview

#22248 Fix "Download Page as CSV" for related value display with empty template
  .changeset/selfish-sloths-double.md
  packages/utils/shared/get-fields-from-template.test.ts
  packages/utils/shared/get-fields-from-template.ts
Labels: :cake: Bug

#22257 [Docs] Update example credentials
  docs/guides/real-time/chat/react.md
Labels: :file_folder: Documentation

#22254 Fix caching for marketplace account / type extension listing
  .changeset/smooth-ears-buy.md
  api/src/controllers/extensions.ts
  app/src/modules/settings/routes/marketplace/routes/account/account.vue
  app/src/modules/settings/routes/marketplace/routes/registry/registry.vue
Labels: :cake: Bug, :file_folder: Marketplace, :file_folder: Caching

#22241 Fix Files interface with custom junction field
  .changeset/six-bags-play.md
  app/src/interfaces/files/files.vue
Labels: :cake: Bug

#22258 Fix small visual inconsistency in Files interface
  .changeset/six-tigers-pull.md
  app/src/interfaces/files/files.vue
  app/src/lang/translations/en-US.yaml
Labels: :cake: Optimization

#22224 Improve sorting UX in M2A
  .changeset/stupid-laws-jog.md
  app/src/composables/use-page-size.ts
  app/src/interfaces/list-m2a/list-m2a.vue
  app/src/lang/translations/en-US.yaml
Labels: :cake: Improvement, :warning: Enterprise

#22261 Add FMS and PIM to list of special cases for title formatter
  .changeset/quick-onions-beam.md
  packages/format-title/src/constants/special-case.ts
Labels: :cake: Optimization

#22263 Fix untranslated field meta data
  .changeset/stupid-singers-smash.md
  app/src/modules/settings/routes/data-model/fields/components/fields-management.vue
Labels: :cake: Bug

#22262 Fix ambiguous column SQL error for M2A relations
  .changeset/blue-lies-double.md
  api/src/utils/apply-query.ts
Labels: :cake: Bug, :file_folder: Data Modeling

#22260 Update pnpm to v9
  package.json
  pnpm-lock.yaml
Labels: :cake: Chore

#22281 Disable "Download Page as CSV" button if layout does not support it
  .changeset/big-kiwis-happen.md
  app/src/lang/translations/en-US.yaml
  app/src/modules/content/routes/collection.vue
  app/src/views/private/components/export-sidebar-detail.vue
Labels: :cake: Bug

#22280 Fix "Auto Refresh" for Kanban and Calendar layouts
  .changeset/twelve-owls-tickle.md
  app/src/layouts/calendar/calendar.vue
  app/src/layouts/calendar/index.ts
  app/src/layouts/cards/cards.vue
  app/src/layouts/kanban/index.ts
  app/src/layouts/kanban/kanban.vue
  app/src/layouts/map/map.vue
  app/src/layouts/tabular/tabular.vue
  app/src/modules/content/routes/collection.vue
Labels: :cake: Bug

#22286 Add search to Roles in Access Control
  .changeset/rude-carrots-confess.md
  app/src/components/v-highlight.vue
  app/src/interfaces/_system/system-filter/system-filter.vue
  app/src/lang/translations/en-US.yaml
  app/src/modules/insights/routes/overview.vue
  app/src/modules/settings/routes/data-model/collections/collections.vue
  app/src/modules/settings/routes/roles/collection.vue
  app/src/views/private/components/search-input.vue
Labels: :cake: Improvement

#22305 docs - add cache auto purge to compose
  docs/self-hosted/docker-guide.md
Labels: :file_folder: Documentation

#22300 Fix deselection of field permissions in access control settings
  .changeset/tough-rocks-do.md
  app/src/modules/settings/routes/roles/permissions-detail/components/fields.vue
Labels: :cake: Bug, :file_folder: Access Control

#22309 [SDK] Added "_icontains" string operator
  .changeset/rude-cougars-suffer.md
  sdk/src/types/filters.ts
Labels: :cake: Bug, :file_folder: SDK

#22060 Fix filter validation for field functions
  .changeset/strong-bulldogs-type.md
  api/src/database/run-ast.ts
  api/src/services/authorization.ts
  api/src/utils/apply-query.ts
  api/src/utils/parse-filter-key.test.ts
  api/src/utils/parse-filter-key.ts
  api/src/utils/strip-function.test.ts
  api/src/utils/strip-function.ts
Labels: :cake: Bug, :cake: Regression, :file_folder: REST, :file_folder: Filtering

#22113 Clean-up code in `useItem` composable
  app/src/composables/use-item.ts
Labels: :cake: Chore

#22307 Catch invalid HEIC images in the App
  .changeset/brave-chairs-switch.md
  app/src/interfaces/file-image/file-image.vue
Labels: :cake: Improvement, :file_folder: Forms

#22302 App: Add option to open image on block editor
  .changeset/curvy-fishes-work.md
  app/src/interfaces/input-block-editor/bus.ts
  app/src/interfaces/input-block-editor/editorjs-overrides.css
  app/src/interfaces/input-block-editor/input-block-editor.vue
  app/src/interfaces/input-block-editor/plugins.ts
Labels: :cake: Improvement, :warning: Enterprise

#22240 Client-side restart of failed transactions on CockroachDB
  .changeset/bright-mirrors-rush.md
  api/src/utils/transaction.ts
Labels: :cake: Bug, :kaaba: CockroachDB

#22313 [Docs] Prevent icon translation in components and markdown sources
  docs/.vitepress/components/Card.vue
  docs/.vitepress/components/Feedback.vue
  docs/.vitepress/config.ts
  docs/.vitepress/lib/markdown-plugins/material-icons-no-translate.ts
  docs/package.json
  pnpm-lock.yaml
Labels: :cake: Improvement, :file_folder: Documentation

#22316 Drop extension folder creation
  .changeset/warm-bees-glow.md
  packages/create-directus-project/lib/index.js
Labels: :cake: Bug

#22322 Fix Supabase storage driver `list` operation
  .changeset/seven-brooms-applaud.md
  packages/storage-driver-supabase/src/index.test.ts
  packages/storage-driver-supabase/src/index.ts
Labels: :cake: Bug

#22293 Fix failing file upload to Supabase
  .changeset/green-sloths-sparkle.md
  packages/storage-driver-supabase/src/index.test.ts
  packages/storage-driver-supabase/src/index.ts
Labels: :cake: Bug

#22339 Inject Content Version in Live Preview popout
  .changeset/shiny-avocados-eat.md
  app/src/modules/content/routes/item.vue
  app/src/modules/content/routes/preview.vue
Labels: :cake: Bug, :file_folder: Live Preview

#22340 Downgrade samlify to fix issue with allowCreate attribute
  .changeset/four-eggs-wait.md
  api/package.json
  pnpm-lock.yaml
Labels: :cake: Bug, :file_folder: Authentication

#22342 Add falsy fallback condition to search query
  .changeset/thick-chicken-swim.md
  api/src/utils/apply-query.test.ts
  api/src/utils/apply-query.ts
  docs/reference/query.md
Labels: :cake: Bug, :file_folder: Data Modeling

#22345 Fix large and real numbers in `search` query
  api/src/database/helpers/index.ts
  api/src/database/helpers/number/dialects/default.ts
  api/src/database/helpers/number/dialects/mssql.ts
  api/src/database/helpers/number/dialects/oracle.ts
  api/src/database/helpers/number/dialects/postgres.ts
  api/src/database/helpers/number/dialects/sqlite.ts
  api/src/database/helpers/number/index.ts
  api/src/database/helpers/number/types.ts
  api/src/database/helpers/number/utils/decimal-limit.ts
  api/src/database/helpers/number/utils/maybe-stringify-big-int.ts
  api/src/database/helpers/number/utils/number-in-range.ts
  api/src/services/fields.ts
  api/src/services/meta.ts
  api/src/utils/apply-query.test.ts
  api/src/utils/apply-query.ts
  api/src/utils/parse-numeric-string.ts
  packages/constants/src/fields.ts
  packages/constants/src/index.ts
  packages/constants/src/number.ts
  packages/types/src/fields.ts
Labels: :cake: Bug, :kaaba: Postgres, :kaaba: MS SQL Server, :warning: Enterprise
