Repository directus/directus, pull requests merged in 2024-07, with the labels that each got.

#22673 Add support for the TUS protocol
  api/package.json
  api/src/app.ts
  api/src/constants.ts
  api/src/controllers/tus.ts
  api/src/database/migrations/20240701A-add-tus-data.ts
  api/src/services/files.ts
  api/src/services/files/lib/extract-metadata.ts
  api/src/services/files/utils/get-metadata.ts
  api/src/services/files/utils/parse-image-metadata.ts
  api/src/services/server.ts
  api/src/services/tus/data-store.ts
  api/src/services/tus/index.ts
  api/src/services/tus/lockers.ts
  api/src/services/tus/server.ts
  api/src/services/tus/utils/wait-timeout.ts
  api/src/storage/register-locations.test.ts
  api/src/storage/register-locations.ts
  app/package.json
  app/src/components/v-progress-linear.vue
  app/src/components/v-upload.vue
  app/src/events.ts
  app/src/lang/translations/en-US.yaml
  app/src/modules/files/routes/add-new.vue
  app/src/modules/files/routes/collection.vue
  app/src/stores/server.ts
  app/src/utils/upload-file.ts
  app/src/utils/upload-files.ts
  app/src/views/private/components/file-preview-replace.vue
  docs/dictionary.txt
  docs/self-hosted/config-options.md
  packages/env/src/constants/defaults.ts
  packages/storage-driver-local/src/index.ts
  packages/storage-driver-s3/package.json
  packages/storage-driver-s3/src/index.ts
  packages/storage/src/index.ts
  packages/system-data/src/fields/files.yaml
  packages/types/src/files.ts
  pnpm-lock.yaml
Labels: :cake: Feature, :warning: Enterprise

#22875 minor grammar fix in data-model.md
  contributors.yml
  docs/app/data-model.md
Labels: :file_folder: Documentation

#22904 App: Support relative links on images on WYSIWYG
  app/src/interfaces/input-rich-text-html/useImage.ts
Labels: :warning: Enterprise

#22724 Allow to specify ADMIN_TOKEN in ENV (#22059)
  .changeset/silly-ladybugs-carry.md
  api/src/cli/commands/bootstrap/index.ts
  docs/contributing/running-locally.md
  docs/self-hosted/cli.md
  docs/self-hosted/config-options.md
  packages/env/src/constants/directus-variables.ts
Labels: :cake: Improvement, :cake: Feature

#22929 Only add `tus_id` filter if `TUS_ENABLED` is `true`
  .changeset/eight-clocks-attack.md
  api/src/services/files.ts
Labels: :cake: Regression

#22916 Fix `reduceSchema` to strip out collections without access
  .changeset/eighty-toys-clap.md
  api/src/utils/reduce-schema.ts
Labels: :cake: Bug, :cake: Regression, :file_folder: GraphQL, :star2: V11 RC

#22936 Fix filter creation in `fetchPolicies` for users without roles
  .changeset/pink-wolves-beg.md
  api/src/permissions/lib/fetch-policies.test.ts
  api/src/permissions/lib/fetch-policies.ts
Labels: :cake: Bug, :file_folder: Access Control, :star2: V11 RC

#22914 Fix `NotificationsService` for policies
  .changeset/twenty-yaks-live.md
  api/src/services/notifications.ts
Labels: :cake: Bug, :file_folder: Access Control, :star2: V11 RC

#22787 Fix truncating of results when sorted by relational field
  .changeset/dry-trees-enjoy.md
  api/src/database/run-ast.ts
  contributors.yml
Labels: :warning: Enterprise, :file_folder: Data Modeling

#22949 Remove trailing slash from vite base URL in development mode
  app/vite.config.js
Labels: :cake: Improvement

#22950 Patch websocket test with updated behaviour for handshake auth mode
  tests/blackbox/tests/db/websocket/auth.test.ts
Labels: :cake: Chore

#22915 Fix `flattenFilter` logic to account for not plain filter values
  .changeset/violet-numbers-retire.md
  api/src/permissions/modules/process-ast/utils/flatten-filter.test.ts
  api/src/permissions/modules/process-ast/utils/flatten-filter.ts
Labels: :cake: Bug, :cake: Regression, :file_folder: Access Control, :star2: V11 RC

#22872 Fix multi relational sort in query generation
  .changeset/three-teachers-destroy.md
  api/src/database/run-ast/lib/get-db-query.ts
Labels: :cake: Bug, :file_folder: Data Modeling, :star2: V11 RC

#22957 Fix parsing of byte values in environment variables
  .changeset/nice-bears-matter.md
  api/src/constants.ts
  api/src/controllers/files.ts
Labels: :cake: Bug, :cake: Improvement, :file_folder: Environment Variables

#22951 Add "SSO with Directus behind Proxy" guide
  docs/self-hosted/sso.md
Labels: :file_folder: Documentation

#22970 Ignore default DB_FILENAME option when using MySQL/MariaDB
  .changeset/ten-beds-pretend.md
  api/src/database/index.ts
  contributors.yml
Labels: :kaaba: MySQL, :cake: Optimization, :kaaba: MariaDB

#22989 Hide "Expand All/None" buttons under Data Model when there are no collections
  .changeset/seven-clocks-sit.md
  app/src/modules/settings/routes/data-model/collections/collections.vue
Labels: :cake: Optimization, :file_folder: Data Model

#22994 Add public registration to sso example
  docs/self-hosted/config-options.md
Labels: :file_folder: Documentation

#22991 Hide "Expand All/None" buttons under Data Model when there are no expandable collections
  .changeset/seven-clocks-sit.md
  app/src/modules/settings/routes/data-model/collections/collections.vue
  app/src/modules/settings/routes/data-model/collections/composables/use-expand-collapse.ts
Labels: :cake: Optimization, :file_folder: Data Model

#23020 Remove webhooks from docs
  docs/.vitepress/data/sidebar.ts
  docs/app/data-model/collections.md
  docs/app/webhooks.md
  docs/reference/system/webhooks.md
Labels: :cake: Bug, :file_folder: Documentation, :elevator: DX, :fire::fire:

#22967 Ensure policies are correctly prioritized
  .changeset/tasty-guests-fry.md
  api/src/permissions/lib/fetch-policies.test.ts
  api/src/permissions/lib/fetch-policies.ts
  api/src/permissions/modules/process-ast/types.ts
  api/src/permissions/utils/filter-policies-by-ip.ts
Labels: :cake: Bug, :file_folder: Access Control, :star2: V11 RC, :elevator: Server, :fire::fire:

#23007 Auto reset value when options updated on select dropdown interface
  .changeset/forty-seahorses-occur.md
  app/src/interfaces/select-dropdown/select-dropdown.vue
  contributors.yml
Labels: :cake: Improvement, :file_folder: Forms, :elevator: Web, :fire:

#23022 Fix `aggregate[count]=*` permission checking
  .changeset/proud-cameras-travel.md
  api/src/permissions/modules/process-ast/utils/extract-paths-from-query.test.ts
  api/src/permissions/modules/process-ast/utils/extract-paths-from-query.ts
Labels: :cake: Bug, :file_folder: Authentication, :star2: V11 RC, :elevator: Server, :fire::fire::fire:

#23030 Update logger import in error-handler test
  api/src/middleware/error-handler.test.ts
Labels: :cake: Chore, :elevator: Server, :file_folder: Engine Misc., :fire:

#23024 Api: Emit filter for `email.send`
  .changeset/stale-chicken-perform.md
  api/src/services/mail/index.ts
  app/src/modules/settings/routes/flows/triggers.ts
  docs/extensions/hooks.md
Labels: :cake: Feature, :warning: Enterprise, :file_folder: Email, :elevator: Server

#23023 Limit logs websocket to `strict` auth mode
  api/src/server.ts
  api/src/websocket/controllers/logs.ts
  docs/self-hosted/config-options.md
  packages/env/src/constants/defaults.ts
Labels: :cake: Improvement, :file_folder: WebSockets, :elevator: Server, :fire:

#23063 Show first and last pages on relationships
  .changeset/young-phones-shop.md
  app/src/interfaces/files/files.vue
  app/src/interfaces/list-m2a/list-m2a.vue
  app/src/interfaces/list-m2m/list-m2m.vue
  app/src/interfaces/list-o2m/list-o2m.vue
Labels: :cake: Improvement, :warning: Enterprise, :elevator: Web, :file_folder: Studio Misc., :fire::fire:

#23065 Disable websocket reconnection after manual disconnection
  .changeset/eighty-crabs-smile.md
  sdk/src/realtime/composable.ts
Labels: :cake: Bug, :file_folder: SDK, :elevator: Web, :fire::fire:

#23074 Docs: Update regions on Cloud list
  .changeset/moody-plums-smile.md
  docs/user-guide/cloud/glossary.md
Labels: :cake: Improvement, :file_folder: Documentation, :elevator: DX, :fire:

#23064 Apply consistent Sharp library configuration
  .changeset/silent-emus-rush.md
  api/src/services/assets.ts
  api/src/services/files/lib/get-sharp-instance.test.ts
  api/src/services/files/lib/get-sharp-instance.ts
  api/src/services/files/utils/get-metadata.ts
  contributors.yml
Labels: :cake: Bug, :file_folder: Assets, :elevator: Server, :fire::fire:

#23075 Don't prevent uploads on failure to extract file metadata
  .changeset/lucky-plants-drum.md
  api/src/services/files/utils/get-metadata.test.ts
  api/src/services/files/utils/get-metadata.ts
Labels: :cake: Bug, :file_folder: Assets, :elevator: Server, :fire::fire:

#23084 App: Fix SVG support on image interface
  .changeset/few-mayflies-smash.md
  app/src/interfaces/file-image/file-image.vue
  app/src/utils/readable-mime-type/extensions.json
  app/src/utils/readable-mime-type/types.json
Labels: :cake: Bug, :warning: Enterprise, :file_folder: Forms, :elevator: Web, :fire::fire:

#23035 Introduce `created_on` date field for files and adjust `uploaded_on` to be updated with every upload
  .changeset/fuzzy-jars-worry.md
  api/src/database/migrations/20240716A-update-files-date-fields.ts
  api/src/services/files.test.ts
  api/src/services/files.ts
  api/src/services/items.ts
  app/src/lang/translations/en-US.yaml
  app/src/modules/files/components/file-info-sidebar-detail.vue
  app/src/modules/files/routes/item.vue
  docs/reference/files.md
  docs/releases/breaking-changes.md
  packages/specs/src/components/file.yaml
  packages/system-data/src/fields/files.yaml
  packages/types/src/files.ts
Labels: :cake: Feature, :warning: Enterprise, :file_folder: Assets, :elevator: Server, :fire::fire::fire:

#23092 Fix select dropdown null choices display problem
  .changeset/clean-cameras-jump.md
  app/src/components/v-select/__snapshots__/v-select.test.ts.snap
  app/src/components/v-select/v-select.vue
  app/src/interfaces/select-dropdown/select-dropdown.vue
Labels: :cake: Bug, :file_folder: Forms, :elevator: Web, :fire::fire:

#23093 Simplify date generation for `uploaded_on` files field
  api/src/services/files.test.ts
  api/src/services/files.ts
Labels: :cake: Optimization, :file_folder: Assets, :elevator: Server, :star: Good First Issue, :fire:

#23086 Transmit `Directus-File-Id` when creating TUS upload
  .changeset/shy-chairs-return.md
  api/src/controllers/tus.ts
  api/src/services/tus/data-store.ts
  api/src/services/tus/server.ts
  app/src/components/v-upload.vue
  app/src/modules/files/routes/add-new.vue
  app/src/utils/upload-file.ts
  app/src/utils/upload-files.ts
  app/src/views/private/components/file-preview-replace.vue
Labels: :cake: Bug, :cake: Regression, :file_folder: Assets, :elevator: Web, :elevator: Server, :fire::fire::fire:

#23095 Fix query trace logger for failing queries
  .changeset/popular-files-teach.md
  api/src/database/index.ts
Labels: :cake: Bug, :kaaba: MySQL, :elevator: Server, :fire::fire:

#23094 Fix "Update Files Date Fields" migration for MySQL
  api/src/database/migrations/20240305A-change-useragent-type.ts
  api/src/database/migrations/20240716A-update-files-date-fields.ts
Labels: :kaaba: MySQL, :cake: Regression, :file_folder: Data Model, :elevator: Server, :fire::fire:

#23036 Fixes/optimizations in `system-permissions` interface
  .changeset/dull-rings-drive.md
  app/src/interfaces/_system/system-permissions/add-collection-row.vue
  app/src/interfaces/_system/system-permissions/permissions-row.vue
  app/src/interfaces/_system/system-permissions/system-permissions.vue
Labels: :cake: Bug, :cake: Optimization, :file_folder: Access Control, :star2: V11 RC, :elevator: Web, :fire::fire:

#22985 Fix permissions table interface for mobile
  .changeset/lucky-humans-carry.md
  app/src/interfaces/_system/system-permissions/permissions-header.vue
  app/src/interfaces/_system/system-permissions/permissions-row.vue
  app/src/interfaces/_system/system-permissions/system-permissions.vue
Labels: :cake: Bug, :file_folder: Access Control, :star2: V11 RC, :elevator: Web, :fire::fire:

#23098 Simplify schema caching
  .changeset/afraid-garlics-occur.md
  api/src/cache.ts
Labels: :cake: Optimization, :file_folder: Caching, :elevator: Server, :fire:

#19391 Cache foreign keys
  .changeset/four-falcons-remember.md
  api/src/services/relations.ts
Labels: :cake: Improvement, :elevator: Server, :file_folder: Querying, :fire:

#19480 Cache column info
  .changeset/dirty-rings-greet.md
  api/src/services/fields.ts
Labels: :cake: Improvement, :elevator: Server, :file_folder: Querying, :fire:

#23099 Fix group detail collapse on save and stay action
  .changeset/neat-pumas-ring.md
  app/src/interfaces/group-detail/group-detail.vue
Labels: :cake: Bug, :file_folder: Forms, :elevator: Web, :fire::fire:

#23141 API: Only prevent infinite loop if the schema is not cached
  .changeset/wild-squids-approve.md
  api/src/utils/get-schema.ts
Labels: :cake: Improvement, :warning: Enterprise, :file_folder: Caching, :elevator: Server, :fire::fire::fire:
