Repository directus/directus, pull requests merged in 2024-03, with the labels that each got.

#21634 default language for the system-input-translated-string
  .changeset/swift-buses-live.md
  app/src/interfaces/_system/system-input-translated-string/input-translated-string.vue
Labels: Package: @directus/app, Optimization

#21649 Enable JIT compiler for vue-i18n & disable legacy API
  .changeset/brown-masks-roll.md
  api/src/app.ts
  app/vite.config.js
Labels: Package: @directus/app, Optimization

#21648 Preserve translation strings when duplicating a field
  .changeset/tough-hotels-reflect.md
  app/src/modules/settings/routes/data-model/fields/components/fields-management.vue
Labels: Package: @directus/app, Bug

#21509 Fixed an issue that prevented saving of content versions featuring relational data
  .changeset/quick-cameras-kneel.md
  app/src/components/v-form/v-form.vue
Labels: Package: @directus/app, Bug

#21657 Drop TS Vue Plugin from VS Code recommended extensions
  .vscode/extensions.json
Labels: Chore

#21652 Preserve translation strings when duplicating a field immediately after field update
  app/src/modules/settings/routes/data-model/field-detail/store/index.ts
  app/src/modules/settings/routes/data-model/fields/components/fields-management.vue
Labels: Package: @directus/app, Bug

#21458 Marketplace Documentation
  .changeset/curvy-bees-eat.md
  docs/.vitepress/data/sidebar.ts
  docs/.vitepress/theme/overrides.css
  docs/dictionary.txt
  docs/extensions/creating-extensions.md
  docs/extensions/installing-extensions.md
  docs/extensions/marketplace/publishing.md
  docs/releases/breaking-changes.md
  docs/self-hosted/config-options.md
  docs/user-guide/marketplace/overview.md
Labels: Documentation

#21552 Clarified SAML warning if indentifier is not present in SAML response
  .changeset/famous-houses-glow.md
  api/src/auth/drivers/saml.ts
  api/src/middleware/error-handler.ts
  contributors.yml
Labels: Package: @directus/api, Optimization

#21662 Fix a few inaccuracies in auth provider docs
  docs/self-hosted/config-options.md
  docs/self-hosted/sso-examples.md
Labels: Documentation

#21667 Patch Happy Monday 🐸
  .changeset/metal-dryers-talk.md
  api/package.json
  api/src/request/agent-with-ip-validation.ts
  app/package.json
  docs/package.json
  package.json
  packages/components/package.json
  packages/composables/package.json
  packages/create-directus-project/lib/check-requirements.js
  packages/data-driver-postgres/package.json
  packages/data-sql/package.json
  packages/data/package.json
  packages/env/package.json
  packages/extensions-sdk/package.json
  packages/extensions/package.json
  packages/memory/package.json
  packages/random/package.json
  packages/release-notes-generator/package.json
  packages/storage-driver-cloudinary/package.json
  packages/storage-driver-local/package.json
  packages/storage-driver-s3/package.json
  packages/storage-driver-supabase/package.json
  packages/storage/package.json
  packages/stores/package.json
  packages/system-data/package.json
  packages/themes/package.json
  packages/types/package.json
  packages/update-check/package.json
  packages/utils/package.json
  pnpm-lock.yaml
Labels: Dependencies

#21238 Fix URL Redirection in OAuth2/OpenID/SAML
  .changeset/calm-tables-destroy.md
  api/src/auth/drivers/oauth2.ts
  api/src/auth/drivers/openid.ts
  api/src/auth/drivers/saml.ts
  api/src/utils/is-login-redirect-allowed.test.ts
  api/src/utils/is-login-redirect-allowed.ts
  api/src/utils/is-url-allowed.test.ts
  api/src/utils/is-url-allowed.ts
  docs/releases/breaking-changes.md
  docs/self-hosted/config-options.md
  packages/env/src/constants/directus-variables.ts
Labels: Package: @directus/api, Bug, Breaking Change

#21668 Happy Spellchecker
  docs/dictionary.txt
Labels: Documentation

#21672 Fix endpoint typo in Content Versions docs
  docs/reference/system/versions.md
Labels: Documentation

#21676 Removed sponsored work from docs
  docs/contributing/sponsor.md
  docs/getting-started/support.md
Labels: Documentation

#21677 Updated SSO docs for the new session token
  docs/self-hosted/sso.md
Labels: Documentation

#21679 Updated SSO docs for the new redirect allow list
  docs/self-hosted/sso.md
Labels: Documentation

#21670 Api / Services / Fields: Only `emitFilter` if `emitEvents` is not set to `false`
  .changeset/rude-crews-mix.md
  api/src/services/fields.ts
Labels: Package: @directus/api, Enterprise

#21683 API / Services / MAIL: Add `EMAIL_AWAIT_RESPONSE` option
  api/src/services/mail/index.ts
Labels: Package: @directus/api, Enterprise

#21691 Various Marketplace UI fixes & enhancements
  app/package.json
  app/src/components/v-pagination.test.ts
  app/src/components/v-pagination.vue
  app/src/directives/markdown.ts
  app/src/lang/translations/en-US.yaml
  app/src/modules/settings/routes/extensions/components/extension-item.vue
  app/src/modules/settings/routes/marketplace/components/extension-list-item.vue
  app/src/modules/settings/routes/marketplace/components/metadata-item.vue
  app/src/modules/settings/routes/marketplace/routes/account/components/account-banner.vue
  app/src/modules/settings/routes/marketplace/routes/account/components/account-metadata.vue
  app/src/modules/settings/routes/marketplace/routes/extension/components/extension-banner.vue
  app/src/modules/settings/routes/marketplace/routes/extension/components/extension-install.vue
  app/src/modules/settings/routes/marketplace/routes/extension/components/extension-metadata-author.vue
  app/src/modules/settings/routes/marketplace/routes/extension/components/extension-metadata-compatibility.vue
  app/src/modules/settings/routes/marketplace/routes/extension/components/extension-metadata-date.vue
  app/src/modules/settings/routes/marketplace/routes/extension/components/extension-metadata-downloads.vue
  app/src/modules/settings/routes/marketplace/routes/extension/components/extension-metadata-license.vue
  app/src/modules/settings/routes/marketplace/routes/extension/components/extension-metadata-size.vue
  app/src/modules/settings/routes/marketplace/routes/extension/components/extension-metadata-version.vue
  app/src/modules/settings/routes/marketplace/routes/extension/components/extension-metadata.vue
  app/src/modules/settings/routes/marketplace/routes/extension/components/extension-readme.vue
  app/src/modules/settings/routes/marketplace/routes/extension/extension.vue
  app/src/modules/settings/routes/marketplace/routes/registry/components/inline-filter.vue
  app/src/modules/settings/routes/marketplace/routes/registry/registry.vue
  app/src/styles/_markdown.scss
  app/src/styles/lib/_highlight.scss
  app/src/utils/md.ts
  pnpm-lock.yaml
Labels: Package: @directus/app

#21697 Fixed Incorrect docstring for `readGraphqlSdl`
  sdk/src/rest/commands/server/graphql.ts
Labels: Documentation

#21703 Fix marketplace pagination
  .changeset/dirty-hornets-yawn.md
  app/src/components/v-pagination.test.ts
  app/src/components/v-pagination.vue
  app/src/modules/settings/routes/marketplace/routes/registry/registry.vue
Labels: Package: @directus/app, Bug

#21702 Fix typed env defaults
  .changeset/giant-clocks-hang.md
  packages/env/src/lib/create-env.test.ts
  packages/env/src/lib/create-env.ts
Labels: Bug, Package: @directus/env

#21696 Clarified that extension type subdirectories must be removed
  .changeset/four-dingos-press.md
  docs/releases/breaking-changes.md
Labels: Documentation

#21698 Fix marketplace/extensions migration
  api/src/database/migrations/20240204A-marketplace.ts
  api/src/extensions/lib/get-extensions-settings.ts
  api/src/services/extensions.ts
Labels: Bug

#21704 Display missing extensions
  app/src/constants/extension-type-icon-map.ts
  app/src/lang/translations/en-US.yaml
  app/src/modules/settings/routes/extensions/components/extension-group-divider.vue
  app/src/modules/settings/routes/extensions/components/extension-item.vue
  app/src/modules/settings/routes/extensions/extensions.vue
Labels: Package: @directus/app, Optimization

#21705 Remove outdated hint about displayed npm info in marketplace docs
  docs/extensions/marketplace/publishing.md
Labels: Documentation

#21719 Docs: Move Migrations out of Extensions
  .changeset/beige-toys-serve.md
  docs/.vitepress/data/sidebar.ts
  docs/netlify.toml
  docs/releases/breaking-changes.md
  docs/self-hosted/migrations.md
Labels: Documentation

#21721 Fix unique constraint / alter statement issues in marketplace migration
  .changeset/healthy-masks-hang.md
  api/src/database/migrations/20240204A-marketplace.ts
Labels: Package: @directus/api, Bug

#21718 Fix email template loading
  .changeset/tough-pigs-beg.md
  packages/extensions/src/node/utils/get-extensions.ts
Labels: Package: @directus/api, Bug, Regression

#21729 Add support for `EMAIL_TEMPLATES_PATH`
  .changeset/nasty-lamps-tap.md
  api/src/app.test.ts
  api/src/services/mail/index.ts
  api/src/services/websocket.test.ts
  docs/.vitepress/data/sidebar.ts
  docs/netlify.toml
  docs/releases/breaking-changes.md
  docs/self-hosted/config-options.md
  docs/self-hosted/email-templates.md
  packages/env/src/constants/defaults.ts
  packages/env/src/constants/directus-variables.ts
Labels: Improvement

#21730 Use Directus version in `host` field of extensions manifest
  .changeset/chatty-donuts-begin.md
  packages/extensions-sdk/src/cli/commands/create.ts
  packages/extensions-sdk/src/constants/last-breaking.ts
  pnpm-lock.yaml
Labels: Bug, Package: @directus/extensions-sdk

#21746 Fix headers type check in Sandbox SDK request function
  .changeset/modern-keys-confess.md
  api/src/extensions/lib/sandbox/sdk/generators/request.ts
Labels: Package: @directus/api, Bug

#21751 Fix loading of Sandbox Operation Extensions
  .changeset/chilly-pumpkins-sin.md
  api/src/extensions/lib/sandbox/generate-api-extensions-sandbox-entrypoint.ts
  docs/extensions/sandbox/register.md
Labels: Package: @directus/api, Bug

#21741 Return send mail promise
  .changeset/perfect-colts-begin.md
  api/src/operations/mail/index.ts
  api/src/services/mail/index.ts
  api/src/services/notifications.ts
  api/src/services/shares.ts
  api/src/services/users.test.ts
  api/src/services/users.ts
  contributors.yml
Labels: Package: @directus/api, Bug

#21756 Ensure that v-list-items are displayed correctly throughout the app
  .changeset/pretty-sheep-hammer.md
  app/src/components/v-list-item.vue
  app/src/modules/settings/routes/marketplace/components/extension-list-item.vue
Labels: Package: @directus/app, Bug

#21759 docs: broken link on home page
  contributors.yml
  docs/index.md
Labels: Documentation

#21747 Fix extensions sync issue when `EXTENSIONS_LOCATION` is set
  .changeset/dry-crews-scream.md
  api/src/extensions/lib/sync-extensions.ts
  api/src/extensions/manager.ts
  api/src/lock/index.ts
  api/src/lock/lib/use-lock.test.ts
  api/src/lock/lib/use-lock.ts
  packages/memory/src/kv/types/class.ts
Labels: Bug

#21749 Clean-up and serialize errors thrown in async Sandbox SDK functions
  .changeset/lemon-ears-kick.md
  api/src/extensions/lib/sandbox/sdk/instantiate.ts
  api/src/extensions/lib/sandbox/sdk/utils/wrap.ts
Labels: :cake: Bug

#21782 Reduce schedule for lock threads workflow to a daily basis
  .github/workflows/lock-threads.yml
Labels: :cake: Optimization

#21779 Fix extensions auto reloading
  .changeset/soft-eyes-scream.md
  api/src/extensions/manager.ts
Labels: :cake: Bug, :file_folder: Extensions

#21781 Prevent error when reloading sandboxed extensions
  .changeset/chatty-yaks-shake.md
  api/src/extensions/manager.ts
Labels: :cake: Bug, :file_folder: Extensions

#21725 Update docker guide docs to persist extensions volume
  docs/self-hosted/docker-guide.md
  docs/self-hosted/quickstart.md
Labels: :file_folder: Documentation

#21793 Fix logout SDK auth composable to include auth mode
  .changeset/nine-coins-pull.md
  sdk/src/auth/composable.ts
Labels: :cake: Bug, :file_folder: REST

#21789 Return payload of sandboxed operation extensions
  .changeset/perfect-stingrays-scream.md
  api/src/extensions/lib/sandbox/register/operation.ts
Labels: :cake: Bug, :file_folder: Extensions

#21809 Add `REDIS_ENABLED` env var
  .changeset/weak-rings-film.md
  api/src/redis/utils/redis-config-available.test.ts
  api/src/redis/utils/redis-config-available.ts
  docs/self-hosted/config-options.md
  packages/env/src/constants/directus-variables.ts
  packages/env/src/constants/type-map.ts
Labels: :cake: Improvement

#21783 Add LRU cache to GraphQLSchema generation
  .changeset/green-dots-sparkle.md
  api/package.json
  api/src/services/graphql/index.ts
  api/src/services/graphql/schema-cache.ts
  docs/self-hosted/config-options.md
  packages/env/src/constants/directus-variables.ts
  pnpm-lock.yaml
Labels: :cake: Improvement, :warning: Enterprise, :file_folder: GraphQL

#21802 Correct the type of filter query parameter in OAS
  .changeset/quick-seals-cheer.md
  packages/specs/src/parameters/filter.yaml
Labels: :cake: Bug, :file_folder: REST

#21821 Add scope in gql schema cache key
  .changeset/tame-grapes-mix.md
  api/src/services/graphql/index.ts
Labels: :cake: Bug, :file_folder: GraphQL

#21791 Optimize error messages in docs newsletter form
  docs/.vitepress/components/Newsletter.vue
Labels: :cake: Optimization, :file_folder: Documentation

#21804 Add breaking change note for Send Email operation
  docs/releases/breaking-changes.md
Labels: :file_folder: Documentation

#21174 Add the ability to configure the error, bug and feature URLs
  .changeset/tender-timers-develop.md
  api/src/database/migrations/20240122A-add-report-url-fields.ts
  app/src/components/register.ts
  app/src/components/v-collection-field-template.vue
  app/src/components/v-field-template/v-field-template.vue
  app/src/composables/use-field-tree.ts
  app/src/constants.ts
  app/src/interfaces/_system/system-display-template/system-display-template.vue
  app/src/lang/translations/en-US.yaml
  app/src/layouts/calendar/options.test.ts
  app/src/layouts/calendar/options.vue
  app/src/layouts/cards/options.vue
  app/src/layouts/map/options.vue
  app/src/modules/settings/components/navigation.vue
  app/src/stores/settings.test.ts
  app/src/views/private/components/notification-dialogs.vue
  docs/reference/system/settings.md
  packages/system-data/src/fields/settings.yaml
  packages/types/src/settings.ts
  sdk/src/schema/settings.ts
Labels: :cake: Improvement

#21839 Fix content module warnings
  app/src/components/use-datetime.vue
  app/src/views/private/components/search-input.vue
Labels: :cake: Chore

#21840 Fix search filter input & border state
  .changeset/real-spiders-destroy.md
  app/src/views/private/components/search-input.vue
Labels: :cake: Bug, :cake: Regression, :file_folder: Filtering

#21818 Optimise multi-field update operations
  .changeset/khaki-owls-rest.md
  api/src/controllers/fields.ts
  api/src/services/fields.ts
Labels: :cake: Improvement, :warning: Enterprise, :file_folder: Data Modeling

#21835 chore: remove repetitive words
  api/src/utils/apply-snapshot.test.ts
  api/src/utils/get-ast-from-query.ts
  contributors.yml
  packages/data/src/types/abstract-query/modifiers/filters/quantifier.ts
Labels: :cake: Chore

#21827 Add missing page titles
  .changeset/chilly-needles-trade.md
  app/src/routes/accept-invite.vue
  app/src/routes/login/login.vue
  app/src/routes/private-not-found.vue
  app/src/routes/reset-password/request.vue
  app/src/routes/reset-password/reset-password.vue
  app/src/routes/reset-password/reset.vue
  app/src/routes/shared/shared.vue
  app/src/routes/tfa-setup.vue
Labels: :cake: Bug

#21847 Move `@directus/format-title` into the monorepo
  .changeset/ninety-dolphins-worry.md
  api/package.json
  app/package.json
  docs/.typedocs/options.json
  docs/contributing/codebase-overview.md
  docs/package.json
  packages/format-title/license
  packages/format-title/package.json
  packages/format-title/readme.md
  packages/format-title/src/constants/acronyms.ts
  packages/format-title/src/constants/articles.ts
  packages/format-title/src/constants/conjunctions.ts
  packages/format-title/src/constants/prepositions.ts
  packages/format-title/src/constants/special-case.ts
  packages/format-title/src/index.test.ts
  packages/format-title/src/index.ts
  packages/format-title/src/utils/capitalize.test.ts
  packages/format-title/src/utils/capitalize.ts
  packages/format-title/src/utils/combine.test.ts
  packages/format-title/src/utils/combine.ts
  packages/format-title/src/utils/decamelize.test.ts
  packages/format-title/src/utils/decamelize.ts
  packages/format-title/src/utils/handle-special-words.test.ts
  packages/format-title/src/utils/handle-special-words.ts
  packages/format-title/tsconfig.json
  pnpm-lock.yaml
Labels: :cake: Optimization, :cake: Chore

#21850 SDK Custom Endpoint Helper
  .changeset/old-apples-refuse.md
  docs/guides/sdk/getting-started.md
  sdk/src/rest/helpers/custom-endpoint.ts
  sdk/src/rest/helpers/index.ts
Labels: :cake: Improvement, :file_folder: SDK

#21855 Fix value not being properly tracked in `v-collection-field-template`
  app/src/components/v-collection-field-template.vue
Labels: :cake: Bug

#21870 Fix/update components playground
  app/package.json
  app/src/components/transition/transition-bounce.story.vue
  app/src/components/transition/transition-dialog.story.vue
  app/src/components/transition/transition-expand.story.vue
  app/src/components/v-avatar.story.vue
  app/src/components/v-button.story.vue
  app/src/components/v-card.story.vue
  app/src/components/v-chip.story.vue
  app/src/components/v-divider.story.vue
  app/src/components/v-emoji-picker.story.vue
  app/src/components/v-hover.story.vue
  app/src/components/v-input.story.vue
  app/src/components/v-item-group.story.vue
  app/src/components/v-list-group.story.vue
  app/src/components/v-list-item.story.vue
  app/src/components/v-list.story.vue
  app/src/components/v-menu.story.vue
  app/src/components/v-notice.story.vue
  app/src/components/v-sheet.story.vue
  app/src/components/v-skeleton-loader.story.vue
  app/src/components/v-slider.story.vue
  app/src/components/v-tabs.story.vue
  app/src/components/v-textarea.story.vue
  packages/components/package.json
  pnpm-lock.yaml
Labels: :cake: Bug, :file_folder: Documentation

#21803 SDK relational field type validation fails
  .changeset/gentle-carrots-attend.md
  sdk/package.json
  sdk/src/client.test.ts
  sdk/src/types/fields.ts
  sdk/tests/fields.test.ts
  sdk/tests/schema.ts
  sdk/tsconfig.json
  sdk/vitest.config.ts
Labels: :cake: Bug, :file_folder: SDK

#21894 v-image rate-limiting and lazy loading
  .changeset/rare-cameras-swim.md
  app/src/api.ts
  app/src/components/v-image.vue
Labels: :cake: Bug, :warning: Enterprise

#21904 Simplify v-image component
  .changeset/khaki-clouds-tease.md
  app/src/components/v-image.vue
Labels: :cake: Improvement

#21905 Docs update content version description
  docs/guides/headless-cms/content-versioning.md
Labels: :file_folder: Documentation

#21935 Add new acronyms and duplicates clean-up
  .changeset/tidy-fireants-dream.md
  packages/format-title/src/constants/acronyms.ts
  packages/format-title/src/constants/constants.test.ts
  packages/format-title/src/constants/special-case.ts
Labels: :cake: Improvement

#21908 Notify other instances when extension is updated
  .changeset/curvy-horses-invite.md
  api/src/extensions/manager.ts
  api/src/services/extensions.ts
Labels: :cake: Bug, :file_folder: Extensions, :warning: Enterprise

#21956 SDK websocket handshake messages not emitted
  .changeset/fair-horses-deliver.md
  sdk/src/realtime/composable.ts
Labels: :cake: Bug, :file_folder: WebSockets, :file_folder: SDK

#21874 Hiding non session SSO providers from the app
  .changeset/polite-islands-collect.md
  api/src/controllers/auth.ts
  api/src/utils/get-auth-providers.ts
  app/src/stores/server.test.ts
  app/src/stores/server.ts
  sdk/src/rest/commands/auth/providers.ts
Labels: :cake: Improvement, :warning: Enterprise, :file_folder: Authentication

#21687 Truncate User-Agent to 1024 Chars and Migrate DB Column
  .changeset/poor-garlics-behave.md
  api/src/auth/drivers/ldap.ts
  api/src/auth/drivers/local.ts
  api/src/auth/drivers/oauth2.ts
  api/src/auth/drivers/openid.ts
  api/src/controllers/activity.ts
  api/src/controllers/auth.ts
  api/src/database/migrations/20240305A-change-useragent-type.ts
  api/src/middleware/authenticate.ts
Labels: :cake: Bug, :file_folder: REST

#21190 Add onUpdate constraint to relations service
  .changeset/empty-garlics-float.md
  api/src/services/relations.ts
Labels: :cake: Bug, :file_folder: Data Modeling

#21983 Docs / SSO: Fix docs about session cookie on Seamless mode
  docs/self-hosted/sso.md
Labels: :file_folder: Documentation

#21986 Add autocomplete for 2FA input
  .changeset/stupid-avocados-tan.md
  .github/workflows/stale-issues.yml
  app/src/routes/login/components/login-form/ldap-form.vue
  app/src/routes/login/components/login-form/login-form.vue
  contributors.yml
Labels: :cake: Optimization, :file_folder: Authentication

#21808 Fix 15553 remove webhooks (1/2)
  .changeset/healthy-horses-trade.md
  api/src/app.ts
  api/src/controllers/webhooks.ts
  api/src/database/migrations/20240311A-deprecate-webhooks.ts
  api/src/services/webhooks.test.ts
  api/src/services/webhooks.ts
  api/src/webhooks.ts
  app/src/lang/translations/en-US.yaml
  app/src/modules/settings/components/navigation.vue
  app/src/modules/settings/routes/webhooks/collection.vue
  app/src/modules/settings/routes/webhooks/item.vue
  packages/system-data/src/fields/webhooks.yaml
Labels: :cake: Improvement

#22011 Update copyright year
  directus/readme.md
  license
  sdk/license
Labels: :cake: Chore

#22019 Update migrations to fix initialization on MS SQL and CockroachDB
  .changeset/silly-coins-dress.md
  api/src/database/migrations/20240204A-marketplace.ts
Labels: :cake: Bug, :kaaba: MS SQL Server, :kaaba: CockroachDB

#22022 Update docs Email Template sample path
  docs/self-hosted/email-templates.md
Labels: :cake: Bug, :file_folder: Documentation

#21969 Remove or re-install missing extensions
  .changeset/giant-yaks-hug.md
  api/src/controllers/extensions.ts
  api/src/services/extensions.ts
  app/src/constants/extension-type-icon-map.ts
  app/src/lang/translations/en-US.yaml
  app/src/modules/settings/routes/extensions/components/extension-group-divider.vue
  app/src/modules/settings/routes/extensions/components/extension-item-options.vue
  app/src/modules/settings/routes/extensions/components/extension-item.vue
  app/src/modules/settings/routes/extensions/constants.ts
  app/src/modules/settings/routes/extensions/extensions.vue
  app/src/modules/settings/routes/extensions/types.ts
  app/src/stores/extensions.ts
Labels: :cake: Improvement, :warning: Enterprise, :file_folder: Marketplace

#21938 [App] Migrate authentication and refreshing to the SDK
  .changeset/brave-shrimps-ring.md
  app/package.json
  app/src/api.ts
  app/src/auth.ts
  app/src/components/v-upload.vue
  app/src/events.ts
  app/src/idle.test.ts
  app/src/idle.ts
  app/src/modules/files/routes/collection.vue
  app/src/routes/login/components/login-form/ldap-form.vue
  app/src/routes/login/components/login-form/login-form.vue
  app/src/sdk.ts
  app/src/utils/upload-file.ts
  docs/guides/sdk/authentication.md
  docs/reference/authentication.md
  docs/reference/system/shares.md
  pnpm-lock.yaml
  sdk/src/auth/composable.ts
  sdk/src/auth/types.ts
  sdk/src/rest/commands/auth/login.ts
  sdk/src/rest/commands/utils/shares.ts
  sdk/src/rest/utils/get-auth-endpoint.ts
  sdk/src/rest/utils/index.ts
  sdk/src/utils/request.ts
Labels: :cake: Feature, :file_folder: SDK, :file_folder: Authentication

#21896 Fix Save As Copy when duplicating M2M/O2M fields
  .changeset/tasty-penguins-glow.md
  app/src/composables/use-item.ts
Labels: :cake: Bug, :warning: Enterprise, :file_folder: Data Modeling

#22024 Pause "Auto Refresh" when page is idle
  .changeset/tasty-squids-hope.md
  app/src/views/private/components/refresh-sidebar-detail.vue
Labels: :cake: Bug, :file_folder: Authentication

#22030 Update copyright year in remaining licenses
  api/license
  app/license
  directus/license
  packages/components/license
  packages/composables/license
  packages/constants/license
  packages/create-directus-extension/license
  packages/create-directus-project/license
  packages/data-driver-postgres/license
  packages/data-sql/license
  packages/data/license
  packages/env/license
  packages/errors/license
  packages/extensions-registry/license
  packages/extensions-sdk/license
  packages/extensions/license
  packages/memory/license
  packages/pressure/license
  packages/random/license
  packages/release-notes-generator/license
  packages/schema/license
  packages/specs/license
  packages/storage-driver-azure/license
  packages/storage-driver-cloudinary/license
  packages/storage-driver-gcs/license
  packages/storage-driver-local/license
  packages/storage-driver-s3/license
  packages/storage-driver-supabase/license
  packages/storage/license
  packages/stores/license
  packages/themes/license
  packages/tsconfig/license
  packages/types/license
  packages/update-check/license
  packages/utils/license
  packages/validation/license
Labels: :cake: Chore
