Repository directus/directus, pull requests merged in 2024-09, with the labels that each got.

#23428 Enhancements to the notifications drawer
  .changeset/heavy-ties-return.md
  app/src/views/private/components/notifications-drawer.vue
Labels: Improvement

#23100 reload npm extensions when watch is enabled
  .changeset/sharp-gorillas-hunt.md
  api/src/extensions/manager.ts
  contributors.yml
Labels: Improvement

#21488 Docs: Give a little example about how to use extensions with Docker
  docs/extensions/creating-extensions.md
Labels: Improvement

#23512 Fix `MariaDB` erroring on column info introspection
  packages/schema/src/dialects/mysql.ts
Labels: Regression

#23436 Fix error on nullable update within Oracle DB
  .changeset/brave-snails-smell.md
  api/src/database/helpers/index.ts
  api/src/database/helpers/nullable-update/dialects/default.ts
  api/src/database/helpers/nullable-update/dialects/oracle.ts
  api/src/database/helpers/nullable-update/index.ts
  api/src/database/helpers/nullable-update/types.ts
  api/src/services/fields.ts
Labels: Bug, Regression

#23518 Fix sorting for nested queries with permissions / filters
  .changeset/gorgeous-fans-rule.md
  api/src/database/helpers/schema/dialects/cockroachdb.ts
  api/src/database/helpers/schema/dialects/mssql.ts
  api/src/database/helpers/schema/dialects/mysql.ts
  api/src/database/helpers/schema/dialects/oracle.ts
  api/src/database/helpers/schema/dialects/postgres.ts
  api/src/database/helpers/schema/dialects/sqlite.ts
  api/src/database/helpers/schema/types.ts
  api/src/database/run-ast/lib/get-db-query.ts
Labels: Bug, MS SQL Server

#23465 Adds ignore rules to Schema Apply CLI
  .changeset/trams-rijden.md
  api/src/cli/commands/schema/apply.ts
  api/src/cli/index.ts
  contributors.yml
Labels: Feature

#23574 Adjust labels for Crowdin PRs
  crowdin.yml
Labels: 🍰 Chore

#23581 Fix spacing of expand collapse button (data model view)
  .changeset/chilled-readers-talk.md
  app/src/modules/settings/routes/data-model/collections/collections.vue
Labels: Bug

#23583 Fix `get-address` util tests
  .changeset/cuddly-lizards-prove.md
  api/src/utils/get-address.test.ts
Labels: 🍰 Optimization

#23584 Fix format warnings
  .changeset/six-glasses-warn.md
  api/src/request/is-denied-ip.ts
  app/src/interfaces/input-rich-text-html/input-rich-text-html.vue
Labels: 🍰 Chore

#23585 Fix typo in docs
  .changeset/silver-chairs-tan.md
  docs/reference/system/users.md
Labels: Bug

#23569 Add missing call to getRootPath() in /routes/system-logs/logs.vue
  .changeset/small-bags-listen.md
  app/src/modules/settings/routes/system-logs/logs.vue
Labels: Bug

#23392 Drop SendGrid email transport support
  .changeset/hot-actors-lay.md
  api/package.json
  api/src/cli/utils/create-env/env-stub.liquid
  api/src/mailer.ts
  docs/releases/breaking-changes.md
  docs/self-hosted/config-options.md
  packages/env/src/constants/directus-variables.ts
  pnpm-lock.yaml
Labels: Improvement, :robot: Dependency

#22295 Extract comments to a separate table
  .changeset/blue-pets-beam.md
  api/src/app.ts
  api/src/controllers/activity.ts
  api/src/controllers/comments.ts
  api/src/database/migrations/20240818A-separate-comments.ts
  api/src/permissions/modules/validate-access/validate-access.test.ts
  api/src/permissions/modules/validate-access/validate-access.ts
  api/src/services/activity.ts
  api/src/services/comments.ts
  api/src/services/graphql/index.ts
  api/src/services/index.ts
  api/src/services/users.test.ts
  api/src/services/users.ts
  api/src/utils/get-service.ts
  app/src/app-permissions.ts
  app/src/lang/translations/en-US.yaml
  app/src/views/private/components/comment-input.vue
  app/src/views/private/components/comment-item-header.vue
  app/src/views/private/components/comment-item.vue
  app/src/views/private/components/comments-sidebar-detail.vue
  packages/specs/src/components/comment.yaml
  packages/specs/src/openapi.yaml
  packages/specs/src/paths/activity/activity-comment.yaml
  packages/specs/src/paths/activity/activity-comments.yaml
  packages/specs/src/paths/comments/comment.yaml
  packages/specs/src/paths/comments/comments.yaml
  packages/system-data/src/app-access-permissions/app-access-permissions.yaml
  packages/system-data/src/collections/collections.yaml
  packages/system-data/src/fields/comments.yaml
  packages/system-data/src/fields/index.ts
  packages/system-data/src/relations/relations.yaml
  packages/types/src/comments.ts
  packages/types/src/index.ts
  sdk/src/rest/commands/create/activity.ts
  sdk/src/rest/commands/create/comments.ts
  sdk/src/rest/commands/create/index.ts
  sdk/src/rest/commands/delete/activity.ts
  sdk/src/rest/commands/delete/comments.ts
  sdk/src/rest/commands/delete/index.ts
  sdk/src/rest/commands/read/comments.ts
  sdk/src/rest/commands/read/index.ts
  sdk/src/rest/commands/update/activity.ts
  sdk/src/rest/commands/update/comments.ts
  sdk/src/rest/commands/update/index.ts
  sdk/src/schema/comment.ts
  sdk/src/schema/core.ts
Labels: Improvement

#23553 Fix sidebar-detail missing fetch data after navigation (#23520)
  .changeset/rich-rings-do.md
  app/src/modules/content/routes/item.vue
  app/src/modules/settings/routes/flows/components/logs-sidebar-detail.vue
  app/src/views/private/components/comments-sidebar-detail.vue
  app/src/views/private/components/revisions-drawer-detail.vue
  app/src/views/private/components/shares-sidebar-detail.vue
Labels: Bug

#22413 Consolidate content versioning
  .changeset/loud-avocados-serve.md
  api/src/controllers/versions.ts
  api/src/database/migrations/20240821A-consolidate-content-versioning.ts
  api/src/services/versions.ts
  docs/reference/system/versions.md
  packages/specs/src/components/version.yaml
  packages/system-data/src/fields/versions.yaml
  packages/types/src/versions.ts
  sdk/src/schema/version.ts
Labels: Improvement, Versioning

#23595 Sso update name and email
  .changeset/proud-moons-sell.md
  api/src/auth/drivers/ldap.ts
  api/src/auth/drivers/oauth2.ts
  api/src/auth/drivers/openid.ts
  contributors.yml
  docs/self-hosted/config-options.md
  packages/env/src/constants/directus-variables.ts
Labels: Feature

#23599 App: Fix Markdown preview
  .changeset/chatty-knives-shop.md
  app/src/interfaces/input-rich-text-md/input-rich-text-md.vue
Labels: Bug

#23505 Fix drawer order for the create bookmark dialog
  .changeset/curly-frogs-hide.md
  app/src/views/private/components/bookmark-add.vue
Labels: Bug

#23632 Bump pnpm to 9.10.0
  package.json
Labels: 🍰 Optimization

#23631 Clean-up CSS/Sass declarations below nested rules
  app/src/components/v-checkbox.vue
  app/src/interfaces/input-rich-text-md/input-rich-text-md.vue
  app/src/modules/content/components/live-preview.vue
  app/src/modules/insights/routes/panel-configuration.vue
  app/src/modules/settings/routes/data-model/field-detail/field-detail-simple/field-configuration.vue
  app/src/modules/settings/routes/data-model/field-detail/field-detail-simple/relationship-configuration.vue
  app/src/panels/variable/panel-variable.vue
  app/src/styles/lib/_mapbox.scss
  app/src/views/private/components/render-template.vue
Labels: 🍰 Optimization

#23597 Fix translations interfaces default language used on secondary lang (#23590)
  .changeset/lovely-pillows-sort.md
  app/src/interfaces/translations/translations.vue
Labels: Bug

#23663 Prevent nesting bundle extensions via the `extensions-sdk` add command
  .changeset/great-planets-move.md
  packages/extensions-sdk/src/cli/commands/add.ts
Labels: Bug

#23665 Fix variable scoping in `Displays To Summarize Relational Items` guide
  docs/guides/extensions/displays-relational-summaries.md
Labels: Bug

#23654 Fix Color Select Interface
  .changeset/small-bees-shave.md
  app/src/interfaces/select-color/select-color.vue
  app/src/utils/is-css-var.test.ts
  app/src/utils/is-css-var.ts
Labels: Bug, Improvement

#23389 Fix image display truncated in file image interface (#20035)
  .changeset/five-pens-press.md
  app/src/interfaces/file-image/file-image.vue
  app/src/interfaces/file-image/index.ts
  app/src/lang/translations/en-US.yaml
Labels: Bug

#23723 Fix `select-color` interface
  app/src/interfaces/select-color/select-color.vue
Labels: Bug

#23700 Fix truncation of long collection names
  .changeset/wicked-poems-tell.md
  app/src/interfaces/_system/system-permissions/permissions-row.vue
Labels: Improvement, ⭐️ Good First Issue, ⚠️ Enterprise

#23728 Fix injection of `$CURRENT_POLICIES` into permissions
  .changeset/eleven-roses-compete.md
  api/src/permissions/utils/fetch-dynamic-variable-context.test.ts
  api/src/permissions/utils/fetch-dynamic-variable-context.ts
  api/src/permissions/utils/process-permissions.ts
Labels: Bug, Permissions

#23730 Fix dynamic variable placeholder detection in filter input validation
  .changeset/twenty-frogs-watch.md
  app/src/interfaces/_system/system-filter/input-component.vue
Labels: Bug, Permissions

#23714 Update typings for `defineInterface`, etc
  .changeset/gold-comics-travel.md
  .changeset/tender-parents-confess.md
  packages/extensions/src/shared/types/displays.ts
  packages/extensions/src/shared/types/interfaces.ts
  packages/extensions/src/shared/types/operations.ts
  packages/extensions/src/shared/types/panels.ts
  packages/extensions/src/shared/utils/define-extension.ts
  packages/types/src/misc.ts
Labels: Improvement, Extensibility

#23739 Fix `withToken` precedence if a token is already saved in SDK client
  .changeset/eight-pugs-crash.md
  sdk/src/rest/composable.ts
Labels: Improvement

#23550 Improve calendar layout
  .changeset/perfect-dogs-hope.md
  app/src/layouts/calendar/index.ts
  app/src/styles/lib/_fullcalendar.scss
Labels: Improvement
