Repository directus/directus, pull requests merged in 2024-06, with the labels that each got.

#22633 Include import use-directus-token and component navigation
  contributors.yml
  docs/guides/extensions/modules-build-landing-page.md
Labels: :file_folder: Documentation

#22337 Improve telemetry with deeper insights into system usage
  .changeset/fluffy-zebras-buy.md
  api/src/database/helpers/schema/dialects/cockroachdb.ts
  api/src/database/helpers/schema/dialects/mssql.ts
  api/src/database/helpers/schema/dialects/mysql.ts
  api/src/database/helpers/schema/dialects/oracle.ts
  api/src/database/helpers/schema/dialects/postgres.ts
  api/src/database/helpers/schema/dialects/sqlite.ts
  api/src/database/helpers/schema/index.ts
  api/src/database/helpers/schema/types.ts
  api/src/telemetry/lib/get-report.test.ts
  api/src/telemetry/lib/get-report.ts
  api/src/telemetry/lib/init-telemetry.test.ts
  api/src/telemetry/lib/track.test.ts
  api/src/telemetry/types/report.ts
  api/src/telemetry/utils/get-extension-count.test.ts
  api/src/telemetry/utils/get-extension-count.ts
  api/src/telemetry/utils/get-field-count.ts
  api/src/telemetry/utils/get-item-count.test.ts
  api/src/telemetry/utils/get-item-count.ts
  api/src/telemetry/utils/get-user-count.test.ts
  api/src/telemetry/utils/get-user-count.ts
  api/src/telemetry/utils/get-user-item-count.test.ts
  api/src/telemetry/utils/get-user-item-count.ts
Labels: :cake: Improvement

#22641 Align response when updating inexistent role
  .changeset/angry-bobcats-join.md
  api/src/services/roles.ts
Labels: :cake: Optimization

#22646 App: Omit fake fields from requests
  .changeset/lucky-badgers-crash.md
  app/src/composables/use-template-data.ts
  app/src/modules/content/routes/item.vue
  app/src/modules/content/routes/preview.vue
  app/src/views/private/components/drawer-item.vue
  app/src/views/private/components/render-template.vue
Labels: :warning: Enterprise

#22522 Fix for slow query on MS SQL
  .changeset/proud-games-explain.md
  contributors.yml
  packages/schema/src/dialects/mssql.ts
Labels: :kaaba: MS SQL Server, :cake: Optimization

#22702 Skip user limits check if no limit is set
  .changeset/thick-carrots-jam.md
  api/src/services/roles.test.ts
  api/src/services/roles.ts
  api/src/services/users.test.ts
  api/src/services/users.ts
  api/src/telemetry/utils/should-check-user-limits.test.ts
  api/src/telemetry/utils/should-check-user-limits.ts
Labels: :cake: Optimization

#22713 Fix email templates path in docs
  contributors.yml
  docs/guides/extensions/email-template.md
Labels: :file_folder: Documentation

#22744 Fix cloudinary resource type guessing to consider case insensitive extension
  .changeset/new-squids-argue.md
  packages/storage-driver-cloudinary/src/constants.ts
  packages/storage-driver-cloudinary/src/index.ts
Labels: :cake: Bug, :file_folder: Storage Driver

#22750 Run fields CRUD blackbox test sequentially
  tests/blackbox/setup/sequential-tests.ts
Labels: :cake: Chore

#22721 API / CORS: Use coalesce operator because of falsy values
  .changeset/witty-papayas-promise.md
  api/src/middleware/cors.ts
Labels: :cake: Bug

#22738 Ensure service integrity
  .changeset/hot-cherries-tap.md
  api/src/services/files.ts
  api/src/services/flows.ts
  api/src/services/import-export.ts
  api/src/services/items.ts
  api/src/services/notifications.ts
  api/src/services/operations.ts
  api/src/services/payload.ts
  api/src/services/roles.ts
  api/src/services/users.test.ts
  api/src/services/users.ts
  api/src/utils/get-service.ts
  api/src/websocket/utils/items.ts
Labels: :cake: Bug

#22699 Add a default preset for bookmarks
  .changeset/dry-shrimps-reply.md
  app/src/stores/presets.ts
  packages/system-data/src/fields/presets.yaml
Labels: :cake: Improvement, :file_folder: Bookmarks & Presets

#22701 Improve field arrangement in bookmark edit view
  .changeset/nine-weeks-pay.md
  app/src/modules/settings/routes/presets/item.vue
Labels: :cake: Optimization, :file_folder: Bookmarks & Presets

#22726 API / Graphql: Handle `time` type as `Date` scalar
  .changeset/strong-otters-bake.md
  api/src/utils/get-graphql-type.ts
Labels: :warning: Enterprise

#22697 Fix pattern check in filter component
  .changeset/silly-emus-kick.md
  app/src/interfaces/_system/system-filter/input-component.vue
Labels: :cake: Bug

#22672 SDK Custom Storage async setters
  .changeset/popular-bees-press.md
  sdk/src/auth/composable.ts
  sdk/src/auth/static.ts
  sdk/src/auth/types.ts
Labels: :cake: Bug, :file_folder: SDK

#22534 Replace `mysql` client with `mysql2`
  .changeset/famous-candles-camp.md
  api/package.json
  api/src/database/index.ts
  docker-compose.yml
  docs/releases/breaking-changes.md
  docs/self-hosted/config-options.md
  pnpm-lock.yaml
  tests/blackbox/common/config.ts
  tests/blackbox/docker-compose.yml
  tests/blackbox/package.json
Labels: :kaaba: MySQL, :warning: Breaking Change, :kaaba: MariaDB

#22434 Fix primary key unique constraint error extraction for MySQL
  .changeset/slimy-jeans-shout.md
  .changeset/twenty-seahorses-drop.md
  api/src/database/errors/dialects/mysql.ts
  api/src/services/items.ts
  packages/errors/src/errors/record-not-unique.ts
Labels: :cake: Bug, :kaaba: MySQL, :kaaba: MariaDB

#22762 Add `translate` option to the formatted value display
  app/src/displays/formatted-value/formatted-value.vue
Labels: :cake: Improvement, :file_folder: Forms

#22759 Fix remaining blackbox test issues
  pnpm-lock.yaml
  tests/blackbox/common/functions.ts
  tests/blackbox/package.json
  tests/blackbox/setup/sequencer.ts
  tests/blackbox/setup/sequential-tests.ts
  tests/blackbox/tests/common/assets/read.test.ts
  tests/blackbox/tests/common/flows/schedule-hook.test.ts
  tests/blackbox/tests/common/logger/redact.test.ts
  tests/blackbox/tests/db/app/cache.test.ts
  tests/blackbox/tests/db/routes/collections/schema-cache.test.ts
  tests/blackbox/tests/db/routes/flows/webhook.test.ts
  tests/blackbox/tests/db/routes/permissions/cache-purge.test.ts
  tests/blackbox/tests/db/routes/server/health.test.ts
  tests/blackbox/tests/db/schema/timezone/timezone-changed-node-tz-america.test.ts
  tests/blackbox/tests/db/schema/timezone/timezone-changed-node-tz-asia.test.ts
  tests/blackbox/tests/db/websocket/auth.test.ts
  tests/blackbox/tests/db/websocket/general.test.ts
  tests/blackbox/vitest.config.ts
Labels: :cake: Chore

#22797 Fix clipboard copy notification for blocked environments
  .changeset/selfish-countries-check.md
  app/src/composables/use-clipboard.ts
Labels: :cake: Bug

#22729 Policies Documentation
  docs/.vitepress/data/sidebar.ts
  docs/.vitepress/theme/overrides.css
  docs/contributing/codebase-overview.md
  docs/extensions/introduction.md
  docs/guides/headless-cms/approval-workflows.md
  docs/guides/headless-cms/reusable-components.md
  docs/guides/headless-cms/schedule-content/dynamic-sites.md
  docs/reference/authentication.md
  docs/reference/files.md
  docs/reference/filter-rules.md
  docs/reference/system/activity.md
  docs/reference/system/collections.md
  docs/reference/system/extensions.md
  docs/reference/system/fields.md
  docs/reference/system/flows.md
  docs/reference/system/permissions.md
  docs/reference/system/policies.md
  docs/reference/system/roles.md
  docs/reference/system/server.md
  docs/reference/system/settings.md
  docs/reference/system/users.md
  docs/reference/system/webhooks.md
  docs/releases/breaking-changes.md
  docs/self-hosted/config-options.md
  docs/use-cases/headless-cms/security.md
  docs/user-guide/content-module/filters.md
  docs/user-guide/overview/glossary.md
  docs/user-guide/user-management/permissions.md
  docs/user-guide/user-management/roles.md
  docs/user-guide/user-management/users-roles-permissions.md
  docs/user-guide/user-management/users.md
Labels: :file_folder: Documentation, :file_folder: Access Control

#22811 Fix policies migration for public role permissions
  .changeset/thick-dingos-film.md
  api/src/database/migrations/20240619A-permissions-policies.ts
Labels: :cake: Bug, :file_folder: Access Control, :star2: v11 RC

#22789 Include image extension in image URL when uploading image through WYSIWYG
  .changeset/seven-ties-rhyme.md
  app/src/interfaces/input-rich-text-html/useImage.test.ts
  app/src/interfaces/input-rich-text-html/useImage.ts
Labels: :cake: Bug

#22840 Fix default query for table layout
  .changeset/poor-ladybugs-help.md
  app/src/layouts/tabular/index.ts
  app/src/modules/users/routes/collection.vue
Labels: :cake: Bug, :file_folder: Forms, :star2: V11 RC

#22842 Bump pnpm to 9.4.0 & relax engine check to v9
  package.json
Labels: :cake: Chore

#22844 Added missing relations to `system-data`
  .changeset/young-jeans-deliver.md
  packages/system-data/src/relations/relations.yaml
Labels: :cake: Bug, :file_folder: Data Modeling

#22780 collapse/expand all collections
  .changeset/clean-buses-know.md
  app/src/lang/translations/en-US.yaml
  app/src/lang/translations/fr-FR.yaml
  app/src/modules/settings/routes/data-model/collections/collections.vue
  app/src/modules/settings/routes/data-model/collections/components/collection-item.vue
  contributors.yml
Labels: :cake: Improvement

#22848 Only set default filename disk if none is provided
  .changeset/stale-falcons-clean.md
  api/src/services/files.ts
Labels: :cake: Bug, :file_folder: Data Modeling

#22867 Account for share when updating stateful sessions
  .changeset/shaggy-bees-search.md
  api/src/services/authentication.ts
Labels: :cake: Bug, :file_folder: Access Control

#22864 Docs: Fix code issue in Interactive Panel Guide
  contributors.yml
  docs/guides/extensions/panels-create-items.md
Labels: :file_folder: Documentation

#22865 Fix session verification for shares
  .changeset/kind-olives-drum.md
  api/src/utils/verify-session-jwt.ts
  contributors.yml
Labels: :cake: Bug, :file_folder: Access Control
