Repository directus/directus, pull requests merged in 2024-08, with the labels that each got.

#23146 SDK remove dependency on system-data package
  .changeset/cool-peaches-enjoy.md
  packages/system-data/src/collections/index.ts
  pnpm-lock.yaml
  sdk/package.json
  sdk/src/rest/commands/create/items.ts
  sdk/src/rest/commands/read/aggregate.ts
  sdk/src/rest/utils/is-system-collection.ts
  sdk/src/rest/utils/throw-core-collection.ts
  sdk/tsup.config.js
Labels: :cake: Improvement, :file_folder: SDK, :elevator: Web, :fire:

#23163 Add null filtering to equality operators
  .changeset/fifty-shirts-wait.md
  api/src/utils/apply-query.test.ts
  api/src/utils/apply-query.ts
  packages/types/src/filter.ts
Labels: :cake: Bug, :elevator: Server, :file_folder: Querying, :fire::fire:

#23162 Fix versioning dropdown squashed display (#21109)
  .changeset/green-pumas-perform.md
  app/src/modules/content/components/version-menu.vue
  app/src/views/private/components/header-bar.vue
Labels: :cake: Bug, :elevator: Web, :fire::fire:, :file_folder: Versioning

#23097 Fix `down` migration for `v11` erroring on permissions
  .changeset/serious-rings-carry.md
  api/src/database/migrations/20240710A-permissions-policies.ts
Labels: :cake: Bug, :file_folder: Access Control, :star2: V11 RC, :elevator: Server, :fire::fire:

#23178 Bypass dynamic variable processing when migrating down
  api/src/database/migrations/20240710A-permissions-policies.ts
  api/src/permissions/lib/fetch-permissions.ts
Labels: :cake: Bug, :file_folder: Access Control, :star2: V11 RC, :elevator: Server

#23148 Docs: Enhance docker compose example to wait for dependent services
  docs/self-hosted/docker-guide.md
Labels: :cake: Bug, :file_folder: Documentation, :file_folder: Docker, :elevator: Infra, :fire::fire:

#23140 Explicit headings in CSV export
  .changeset/rude-peas-confess.md
  api/src/database/get-ast-from-query/lib/parse-fields.ts
  api/src/services/import-export.test.ts
  api/src/services/import-export.ts
Labels: :cake: Bug, :elevator: Server, :file_folder: Querying, :fire::fire:

#23127 Update filename_disk extension when mimetype changes on overwrite
  .changeset/dull-ducks-shake.md
  api/src/services/files.test.ts
  api/src/services/files.ts
Labels: :cake: Bug, :warning: Enterprise, :file_folder: Assets, :elevator: Server, :fire::fire::fire:

#23181 Fix server error on root m2a query
  .changeset/dull-spies-worry.md
  api/src/database/get-ast-from-query/lib/parse-fields.ts
Labels: :cake: Bug, :star2: V11 RC, :elevator: Server, :fire::fire::fire::fire:

#23192 Fix missing policies in public role policy selection
  .changeset/red-buckets-wink.md
  app/src/modules/settings/routes/roles/public-item.vue
Labels: :cake: Bug, :file_folder: Access Control, :star2: V11 RC, :elevator: Web, :fire::fire::fire:

#23193 Fix sorting of aggregated result
  .changeset/two-items-joke.md
  api/src/permissions/modules/process-ast/utils/extract-paths-from-query.ts
Labels: :cake: Bug, :file_folder: Access Control, :star2: V11 RC, :elevator: Server, :fire::fire::fire:

#23195 Fix M2A query regression from #23181
  api/src/database/get-ast-from-query/lib/parse-fields.ts
Labels: :cake: Bug, :file_folder: Access Control, :star2: V11 RC, :elevator: Server, :fire::fire::fire::fire:

#23198 Add missing changeset for #22947
  .changeset/curly-moons-jam.md
Labels: :cake: Bug, :elevator: Infra, :fire:

#23184 Fix user count
  .changeset/fuzzy-news-drop.md
  api/src/utils/fetch-user-count/fetch-access-lookup.ts
  api/src/utils/fetch-user-count/fetch-user-count.test.ts
  api/src/utils/fetch-user-count/fetch-user-count.ts
  api/src/utils/fetch-user-count/get-user-count-query.ts
Labels: :cake: Bug, :file_folder: Access Control, :star2: V11 RC, :fire::fire::fire::fire:

#23199 Fix related field permissions
  .changeset/slow-rats-smoke.md
  api/src/permissions/modules/process-ast/lib/inject-cases.ts
Labels: :cake: Bug, :file_folder: Access Control, :star2: V11 RC, :elevator: Server, :fire::fire::fire::fire:

#23213 Adding new tiers to rate limiting docs
  docs/user-guide/cloud/glossary.md
Labels: :file_folder: Documentation, :elevator: DX, :fire::fire:

#23214 Rename policies migration to most recent date
  api/src/database/migrations/20240806A-permissions-policies.ts
Labels: :file_folder: Access Control, :cake: Chore, :star2: V11 RC, :elevator: Server, :fire::fire::fire::fire:

#23185 Fix `groupBy` behavior with relational permissions
  .changeset/afraid-trainers-brush.md
  api/src/database/helpers/schema/dialects/cockroachdb.ts
  api/src/database/helpers/schema/dialects/mssql.ts
  api/src/database/helpers/schema/dialects/oracle.ts
  api/src/database/helpers/schema/dialects/postgres.ts
  api/src/database/helpers/schema/types.ts
  api/src/database/helpers/schema/utils/preprocess-bindings.test.ts
  api/src/database/helpers/schema/utils/preprocess-bindings.ts
  api/src/database/run-ast/lib/get-db-query.ts
  api/src/database/run-ast/utils/apply-case-when.ts
  api/src/database/run-ast/utils/with-preprocess-bindings.ts
  api/src/utils/apply-query.ts
Labels: :cake: Bug, :file_folder: Access Control, :star2: V11 RC, :elevator: Server, :fire::fire::fire::fire:

#23231 Adjust the init CLI command for new `mysql2` package
  .changeset/nervous-ladybugs-sell.md
  api/src/cli/commands/init/questions.ts
  api/src/cli/utils/drivers.ts
  api/src/types/database.ts
Labels: :cake: Bug, :kaaba: MySQL, :elevator: Server, :file_folder: Engine Misc., :fire::fire::fire:

#23233 Fix the "add-system-fk-triggers" migration for mysql2
  .changeset/curvy-bears-smile.md
  api/src/database/migrations/20210519A-add-system-fk-triggers.ts
  api/src/database/migrations/20230721A-require-shares-fields.ts
  api/src/database/migrations/20240716A-update-files-date-fields.ts
Labels: :cake: Bug, :kaaba: MySQL, :elevator: Server, :file_folder: Engine Misc., :fire::fire::fire:

#23116 Remove extra div insdie ul element
  .changeset/rich-seals-type.md
  app/src/interfaces/_system/system-fields/system-fields.vue
  app/src/interfaces/_system/system-modules/system-modules.vue
  app/src/interfaces/files/files.vue
  app/src/interfaces/list-m2a/list-m2a.vue
  app/src/interfaces/list-m2m/list-m2m.vue
  app/src/interfaces/list-o2m/list-o2m.vue
  app/src/interfaces/list/list.vue
  app/src/modules/settings/routes/data-model/collections/collections.vue
Labels: :cake: Improvement, :elevator: Web, :file_folder: Studio Misc., :fire::fire:

#23240 Respect system language on display translations
  .changeset/short-bats-grab.md
  app/src/displays/translations/translations.vue
  contributors.yml
Labels: :cake: Bug, :elevator: Web, :star: Good First Issue, :fire::fire:

#23150 Add unix socket support
  .changeset/tiny-humans-draw.md
  api/src/server.ts
  api/src/utils/get-address.test.ts
  api/src/utils/get-address.ts
  api/src/websocket/controllers/graphql.ts
  api/src/websocket/controllers/rest.ts
  contributors.yml
  docs/self-hosted/config-options.md
  packages/env/src/constants/defaults.ts
Labels: :cake: Feature, :elevator: Server, :file_folder: Engine Misc., :fire::fire:

#22164 Packages/Env: Allow casting when reading config value from a file
  .changeset/moody-ants-march.md
  docs/self-hosted/config-options.md
  packages/env/src/constants/type-map.ts
  packages/env/src/lib/cast.test.ts
  packages/env/src/lib/cast.ts
  packages/env/src/lib/create-env.int.test.ts
  packages/env/src/lib/create-env.test.ts
  packages/env/src/lib/create-env.ts
  packages/env/src/utils/get-default-type.test.ts
  packages/env/src/utils/get-default-type.ts
  packages/env/src/utils/is-directus-variable.ts
Labels: :cake: Improvement, :warning: Enterprise, :elevator: Server, :file_folder: Engine Misc., :fire::fire::fire:

#23251 Ignore missing foreign key constraint in policies migration
  .changeset/afraid-berries-nail.md
  api/src/database/migrations/20240806A-permissions-policies.ts
Labels: :cake: Bug, :file_folder: Access Control, :elevator: Server, :fire::fire::fire:

#23115 Fix block editor not real time change
  .changeset/little-parents-shake.md
  app/src/interfaces/input-block-editor/input-block-editor.vue
Labels: :cake: Improvement, :file_folder: Forms, :elevator: Web, :fire::fire:

#23243 Retry transaction also for SQLITE_BUSY
  .changeset/stale-eyes-complain.md
  api/src/utils/transaction.ts
  contributors.yml
Labels: :kaaba: SQLite, :cake: Feature, :elevator: Server, :file_folder: Engine Misc., :fire::fire:

#23253 API / Migrations: Fix drop foreign key if have a different name
  .changeset/eleven-mails-walk.md
  api/src/database/migrations/20240806A-permissions-policies.ts
Labels: :cake: Improvement, :file_folder: Access Control, :elevator: Server, :fire:

#23256 Fix `DB_CLIENT` expected before project initialized
  .changeset/tender-dragons-teach.md
  api/src/database/index.ts
  api/src/database/migrations/20240806A-permissions-policies.ts
Labels: :cake: Bug, :cake: Regression, :elevator: Server, :fire::fire:

#22519 Enhance item count
  .changeset/mean-singers-raise.md
  app/src/interfaces/list-m2m/list-m2m.vue
  app/src/interfaces/list-o2m/list-o2m.vue
  app/src/lang/translations/en-US.yaml
  app/src/layouts/calendar/actions.vue
  app/src/layouts/calendar/index.ts
  app/src/layouts/cards/actions.vue
  app/src/layouts/cards/cards.vue
  app/src/layouts/cards/index.ts
  app/src/layouts/kanban/actions.vue
  app/src/layouts/kanban/index.ts
  app/src/layouts/kanban/kanban.vue
  app/src/layouts/map/actions.vue
  app/src/layouts/map/index.ts
  app/src/layouts/map/map.vue
  app/src/layouts/tabular/actions.vue
  app/src/layouts/tabular/index.ts
  app/src/modules/settings/routes/marketplace/routes/registry/components/inline-filter.vue
  app/src/utils/format-collection-items-count.ts
  app/src/utils/format-items-count.ts
  packages/composables/src/use-items.test.ts
  packages/composables/src/use-items.ts
Labels: :cake: Improvement, :elevator: Web, :file_folder: Studio Misc., :fire:

#23271 Removed RC mentions in docs
  docs/reference/system/permissions.md
  docs/reference/system/policies.md
  docs/reference/system/roles.md
  docs/reference/system/users.md
  docs/releases/breaking-changes.md
  docs/user-guide/user-management/roles.md
  docs/user-guide/user-management/users.md
Labels: :file_folder: Documentation, :cake: Chore, :elevator: DX, :fire::fire:

#23269 Fix singleton permissions structure
  .changeset/shiny-waves-attack.md
  api/src/services/permissions.ts
Labels: :cake: Regression, :file_folder: Access Control, :elevator: Server, :fire::fire::fire:

#23277 Fix readonly mutation to fields in the store via item drawer
  .changeset/eight-fishes-scream.md
  app/src/composables/use-permissions/item/lib/get-fields.ts
Labels: :cake: Bug, :file_folder: Forms, :elevator: Web, :fire::fire:

#23302 Change get-address test port
  api/package.json
  api/src/utils/get-address.test.ts
  pnpm-lock.yaml
Labels: :cake: Chore

#23279 Fix deep `groupBy` behavior for O2M relations
  .changeset/rich-ears-bathe.md
  api/src/database/get-ast-from-query/lib/parse-fields.ts
Labels: :cake: Bug, :elevator: Server, :file_folder: Querying, :fire::fire:

#23310 Hide WYSIWYG toolbar if no items are selected
  .changeset/silent-gifts-pay.md
  app/src/interfaces/input-rich-text-html/input-rich-text-html.vue
Labels: :cake: Improvement, :file_folder: Forms, :elevator: Web, :fire:

#23272 Fixed the permission application for relational `_some` and `_none` filters
  .changeset/four-mails-tan.md
  api/src/database/helpers/fn/types.ts
  api/src/database/run-ast/lib/get-db-query.ts
  api/src/database/run-ast/run-ast.ts
  api/src/database/run-ast/utils/apply-case-when.ts
  api/src/database/run-ast/utils/get-column-pre-processor.ts
  api/src/database/run-ast/utils/get-inner-query-column-pre-processor.ts
  api/src/permissions/modules/process-ast/lib/get-cases.ts
  api/src/permissions/modules/process-ast/lib/inject-cases.ts
  api/src/permissions/modules/validate-access/lib/validate-item-access.ts
  api/src/services/items.ts
  api/src/services/meta.ts
  api/src/utils/apply-query.ts
  api/src/utils/get-column.ts
Labels: :cake: Regression, :warning: Enterprise, :file_folder: Access Control, :elevator: Server, :fire::fire::fire::fire:

#23300 Improved querying of `languages` collection in translations interface
  .changeset/chilly-ladybugs-cough.md
  app/src/interfaces/translations/translations.vue
Labels: :cake: Improvement, :file_folder: Forms, :elevator: Web, :fire::fire:

#23267 Fix sort field defaulting for related o2m collections
  .changeset/lazy-goats-jog.md
  api/src/database/get-ast-from-query/get-ast-from-query.ts
  api/src/database/get-ast-from-query/lib/parse-fields.ts
  api/src/database/get-ast-from-query/utils/get-allowed-sort.test.ts
  api/src/database/get-ast-from-query/utils/get-allowed-sort.ts
Labels: :cake: Regression, :file_folder: Access Control, :elevator: Server, :fire::fire::fire::fire:

#23324 Fix bookmark incorrect save on debounce in collection route change (#18318)
  .changeset/chatty-lions-grab.md
  app/src/composables/use-preset.ts
Labels: :cake: Bug, :file_folder: Bookmarks & Presets, :elevator: Web, :fire::fire:

#23327 Adjust permissions migration to work with more MySQL flavors
  .changeset/swift-sloths-reply.md
  api/src/database/migrations/20240806A-permissions-policies.ts
Labels: :cake: Bug, :file_folder: Access Control, :elevator: Server, :fire::fire::fire:

#23343 Ensured that WYSIWYG uses the correct CSS var to display fonts correctly
  .changeset/wet-onions-grab.md
  app/src/interfaces/input-rich-text-html/get-editor-styles.ts
Labels: :cake: Bug, :file_folder: Forms, :elevator: Web, :fire:

#23336 Fix file export is ready notification for user without `create` permission to `directus_notifications`
  .changeset/shiny-tips-sell.md
  api/src/services/import-export.ts
Labels: :cake: Improvement, :elevator: Server, :file_folder: Engine Misc., :fire:

#23019 Add default sort field to o2m interface
  .changeset/great-lizards-confess.md
  app/src/interfaces/list-o2m/index.ts
  app/src/interfaces/list-o2m/list-o2m.vue
Labels: :cake: Feature, :warning: Enterprise, :file_folder: Forms, :elevator: Web, :fire::fire::fire:

#23321 Fix caching for dynamic variables
  .changeset/famous-tables-reflect.md
  api/src/permissions/lib/fetch-permissions.test.ts
  api/src/permissions/lib/fetch-permissions.ts
  api/src/permissions/modules/fetch-allowed-collections/fetch-allowed-collections.ts
  api/src/permissions/modules/fetch-allowed-field-map/fetch-allowed-field-map.test.ts
  api/src/permissions/modules/fetch-allowed-field-map/fetch-allowed-field-map.ts
  api/src/permissions/modules/fetch-allowed-fields/fetch-allowed-fields.test.ts
  api/src/permissions/modules/fetch-allowed-fields/fetch-allowed-fields.ts
  api/src/permissions/modules/fetch-inconsistent-field-map/fetch-inconsistent-field-map.test.ts
  api/src/permissions/modules/fetch-inconsistent-field-map/fetch-inconsistent-field-map.ts
  api/src/permissions/utils/fetch-dynamic-variable-context.test.ts
  api/src/permissions/utils/fetch-dynamic-variable-context.ts
  api/src/permissions/utils/fetch-raw-permissions.ts
Labels: :cake: Bug, :file_folder: Access Control, :elevator: Server, :fire::fire::fire::fire:

#23340 Fix filtering of M2A allowed collections in AST construction
  .changeset/three-adults-occur.md
  api/src/database/get-ast-from-query/lib/parse-fields.ts
Labels: :cake: Regression, :file_folder: Access Control, :elevator: Server, :fire::fire::fire:

#23348 Improve sorting in `useRelationMultiple` to work with string sort fields
  .changeset/light-hounds-dress.md
  app/src/composables/use-relation-multiple.ts
Labels: :cake: Bug, :cake: Improvement, :elevator: Web, :file_folder: Studio Misc., :fire:

#23322 Remove all mentions of `CACHE_PERMISSIONS`
  docs/self-hosted/config-options.md
  packages/env/src/constants/defaults.ts
  packages/env/src/constants/directus-variables.ts
Labels: :file_folder: Documentation, :cake: Chore, :elevator: DX, :elevator: Server, :file_folder: Engine Misc., :fire:

#23357 Fix system filter permission checking in `validateItemAccess`
  .changeset/pink-camels-press.md
  api/src/permissions/modules/validate-access/lib/validate-item-access.test.ts
  api/src/permissions/modules/validate-access/lib/validate-item-access.ts
Labels: :cake: Regression, :warning: Enterprise, :file_folder: Access Control, :file_folder: Assets, :elevator: Server, :fire::fire::fire:

#23284 Fix drop folder to file library with bad request
  app/src/modules/files/routes/collection.vue
Labels: :cake: Improvement, :elevator: Web, :file_folder: Studio Misc., :fire:

#23350 Added cloud callout in sidebar
  docs/.vitepress/components/Cloud.vue
  docs/.vitepress/components/Newsletter.vue
  docs/.vitepress/theme/Layout.vue
Labels: :file_folder: Documentation, :elevator: DX

#23353 Add markdown default view option
  .changeset/wise-bikes-suffer.md
  app/src/interfaces/input-rich-text-md/index.ts
  app/src/interfaces/input-rich-text-md/input-rich-text-md.vue
  app/src/lang/translations/en-US.yaml
Labels: :cake: Improvement, :file_folder: Forms, :elevator: Web, :fire:

#23369 Replace jboss/keycloak with quay.io/keycloak/keycloak
  contributors.yml
  docker-compose.yml
Labels: :cake: Improvement, :elevator: Infra, :fire:

#23380 fix: add policy property in DirectusPermission type
  .changeset/gentle-balloons-pretend.md
  contributors.yml
  sdk/src/schema/permission.ts
Labels: :cake: Bug, :file_folder: SDK, :elevator: Web, :fire::fire:

#23388 Auto-label Crowdin PRs
  crowdin.yml
Labels: :cake: Optimization, :cake: Chore, :elevator: Web, :elevator: Infra, :fire:

#23397 Tiny refactor of `parse-filter-key.ts`
  api/src/utils/parse-filter-key.ts
Labels: :cake: Chore, :elevator: Server, :file_folder: Engine Misc., :fire:

#23359 Enabled `gen_random_uuid()` to be used as default field value
  .changeset/quick-worms-kick.md
  api/src/constants.ts
  api/src/services/fields.ts
Labels: :cake: Improvement, :warning: Enterprise, :file_folder: Data Model, :elevator: Server

#23391 Fix icon field limit character size (#22411)
  .changeset/good-teachers-worry.md
  api/src/database/migrations/20240817A-update-icon-fields-length.ts
Labels: :cake: Bug, :elevator: Server, :file_folder: Engine Misc., :fire::fire:

#22986 User Invite Token TTL
  .changeset/wet-lemons-heal.md
  api/src/services/users.ts
  docs/self-hosted/config-options.md
  packages/env/src/constants/defaults.ts
  packages/env/src/constants/directus-variables.ts
Labels: :cake: Feature, :file_folder: Authentication, :elevator: Server, :fire:

#23384 Prevent crash when switching to Date type in Datetime interface
  .changeset/plenty-flies-yawn.md
  app/src/interfaces/datetime/index.ts
Labels: :cake: Bug, :file_folder: Data Model, :elevator: Web, :fire::fire:

#23383 Feat/persist sidebar detail group
  .changeset/breezy-pianos-wink.md
  app/src/views/private/components/sidebar-detail-group.vue
Labels: :cake: Improvement, :elevator: Web, :file_folder: Studio Misc., :fire:

#23358 Improve select radio grid layout (#20034)
  .changeset/smooth-trainers-occur.md
  app/package.json
  app/src/interfaces/select-multiple-checkbox/select-multiple-checkbox.vue
  app/src/interfaces/select-radio/select-radio.vue
  app/src/utils/get-minimal-grid-class.test.ts
  app/src/utils/get-minimal-grid-class.ts
  pnpm-lock.yaml
Labels: :cake: Bug, :file_folder: Forms, :elevator: Web, :fire::fire:

#23381 Feat/update notifications after flow
  .changeset/grumpy-eels-add.md
  app/src/views/private/components/flow-sidebar-detail.vue
  app/src/views/private/components/notifications-drawer.vue
Labels: :cake: Improvement, :file_folder: Flows, :elevator: Web, :fire:

#23149 Add index support
  .changeset/wise-buckets-raise.md
  api/src/services/fields.ts
  app/src/lang/translations/en-US.yaml
  app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-schema.vue
  docs/reference/system/fields.md
  packages/schema/src/dialects/cockroachdb.ts
  packages/schema/src/dialects/mssql.ts
  packages/schema/src/dialects/mysql.ts
  packages/schema/src/dialects/oracledb.ts
  packages/schema/src/dialects/postgres.ts
  packages/schema/src/dialects/sqlite.ts
  packages/schema/src/types/column.ts
Labels: :cake: Feature, :file_folder: Data Model, :elevator: Server, :fire:

#23405 Ensure DB queries in notifications service run in same transaction
  .changeset/yellow-comics-trade.md
  api/src/services/notifications.ts
Labels: :cake: Bug, :kaaba: SQLite, :elevator: Server, :file_folder: Engine Misc., :fire::fire:

#23407 Update notifications unread count when un-/archiving notifications
  .changeset/six-kings-switch.md
  app/src/stores/notifications.ts
  app/src/views/private/components/flow-sidebar-detail.vue
  app/src/views/private/components/notifications-drawer.vue
Labels: :cake: Improvement, :elevator: Web, :file_folder: Studio Misc., :fire:

#23414 Add item count to notification drawer
  .changeset/long-clouds-relate.md
  app/src/utils/format-items-count.ts
  app/src/views/private/components/notifications-drawer.vue
Labels: :cake: Improvement, :elevator: Web, :star: Good First Issue, :fire:

#23430 Switch to own stale issues action
  .github/workflows/stale-issues.yml
Labels: :cake: Bug, :elevator: Infra, :fire::fire:, :file_folder: CI/CD

#23442 Adding 'name' property to DirectusPolicy schema
  .changeset/lucky-files-prove.md
  contributors.yml
  sdk/src/schema/policy.ts
Labels: :cake: Bug, :file_folder: SDK, :elevator: Web, :fire::fire:

#23448 Fix typo in query for archiving notifications
  app/src/views/private/components/notifications-drawer.vue
Labels: :cake: Bug, :elevator: Web, :file_folder: Studio Misc., :fire::fire::fire:

#23449 Add missing breaking change to 11.0.0
  docs/releases/breaking-changes.md
Labels: :file_folder: Documentation, :file_folder: Access Control, :elevator: DX, :fire::fire::fire:

#23450 Fix for "OpenAPI spec has a duplicate operationId"
  contributors.yml
  packages/specs/src/paths/extensions/update-bundle.yaml
Labels: :cake: Bug, :file_folder: REST, :elevator: Server, :fire::fire:

#23454 docs: fix wrong word in 'Update Data' op
  contributors.yml
  docs/app/flows/operations.md
Labels: :cake: Improvement, :file_folder: Documentation, :file_folder: Flows, :elevator: DX

#23461 Env security table fix
  contributors.yml
  docs/self-hosted/config-options.md
Labels: :cake: Bug, :file_folder: Documentation, :elevator: DX, :fire::fire:

#23460 Separate schema needed for operations from schema used to generate api spec
  .changeset/tiny-jeans-matter.md
  api/src/services/specifications.ts
Labels: :cake: Bug, :file_folder: Access Control, :file_folder: REST, :elevator: Server, :fire::fire:

#23464 fix: update good first issue link
  contributors.yml
  docs/contributing/pull-request-process.md
Labels: :cake: Improvement, :file_folder: Documentation, :elevator: DX, :star: Good First Issue, :fire:

#23387 Add hide/show for public registration passwords
  .changeset/empty-geckos-sit.md
  app/src/interfaces/_system/system-input-password/index.ts
  app/src/interfaces/_system/system-input-password/input-password.vue
  app/src/lang/translations/en-US.yaml
  app/src/routes/login/components/login-form/login-form.vue
  app/src/routes/register/register-form.vue
Labels: :cake: Improvement, :file_folder: Public Registration, :elevator: Web, :fire:

#23490 Fix docs missing import
  .changeset/mighty-peaches-press.md
  docs/index.md
Labels: :cake: Bug, :file_folder: Documentation

#23488 Fix address undefined for `graphql` and `websocket` logs
  .changeset/heavy-frogs-think.md
  api/src/server.ts
  api/src/utils/get-address.test.ts
  api/src/utils/get-address.ts
  api/src/websocket/controllers/graphql.ts
  api/src/websocket/controllers/rest.ts
  packages/env/src/constants/defaults.ts
Labels: :cake: Bug, :file_folder: WebSockets, :elevator: Server

#23491 Run formatter on readme
  .changeset/smooth-turkeys-pull.md
  directus/readme.md
Labels: :cake: Optimization, :file_folder: Documentation

#23328 API: Compute schema once and share among other nodes
  .changeset/chatty-dogs-judge.md
  api/src/cache.ts
  api/src/utils/get-schema.ts
  docs/self-hosted/config-options.md
  packages/env/src/constants/defaults.ts
  packages/env/src/constants/directus-variables.ts
  packages/env/src/constants/type-map.ts
  packages/memory/src/bus/lib/local.ts
  packages/memory/src/bus/lib/redis.ts
  packages/memory/src/bus/types/class.ts
Labels: :warning: Enterprise, :fire::fire::fire::fire:

#23502 fix: rich text new tab label
  .changeset/heavy-peas-move.md
  app/src/interfaces/input-rich-text-html/input-rich-text-html.vue
  contributors.yml
Labels: :cake: Improvement, :elevator: Web, :fire:

#23503 Remove unused `current_tab` translation
  .changeset/polite-zoos-shop.md
  app/src/lang/translations/en-US.yaml
Labels: :cake: Chore, :elevator: Web, :file_folder: Studio Misc., :fire:

#23489 Add Kanban layout selection mode
  .changeset/mighty-spoons-collect.md
  app/src/composables/use-layout-click-handler.ts
  app/src/layouts/calendar/index.ts
  app/src/layouts/kanban/index.ts
  app/src/layouts/kanban/kanban.vue
  app/src/layouts/tabular/index.ts
  app/src/layouts/tabular/tabular.vue
Labels: Improvement, :warning: Enterprise, :elevator: Web, :file_folder: Studio Misc., :fire::fire::fire::fire:

#23453 API: Preprocess assigns wrong query bindings when there is more than one duplicated value
  .changeset/ninety-cougars-pull.md
  api/src/database/helpers/schema/utils/preprocess-bindings.test.ts
  api/src/database/helpers/schema/utils/preprocess-bindings.ts
Labels: Bug, :warning: Enterprise, :file_folder: Access Control, :elevator: Server, :fire::fire::fire::fire:

#23066 Add system logs to the app
  .changeset/honest-emus-swim.md
  app/package.json
  app/src/components/v-chip.vue
  app/src/components/v-select/v-select.vue
  app/src/lang/translations/en-US.yaml
  app/src/modules/settings/components/navigation.vue
  app/src/modules/settings/index.ts
  app/src/modules/settings/routes/system-logs/components/inline-filter.vue
  app/src/modules/settings/routes/system-logs/components/logs-display.vue
  app/src/modules/settings/routes/system-logs/components/system-logs-sidebar-detail.vue
  app/src/modules/settings/routes/system-logs/logs.vue
  app/src/modules/settings/routes/system-logs/types.ts
  app/src/shims.d.ts
  app/src/stores/server.ts
  app/vite.config.js
  pnpm-lock.yaml
Labels: Feature, :elevator: Web, :file_folder: Engine Misc., :fire::fire::fire:
