Repository directus/directus, pull requests merged in 2024-12, with the labels that each got.

#23996 Restrict comment create, update and delete to authenticated users
  .changeset/thick-timers-cough.md
  api/src/services/comments.ts
  docs/reference/system/comments.md
Labels: Bug

#24045 Fix item permissions not respected in `drawer-item`
  .changeset/three-ladybugs-jam.md
  app/src/views/private/components/drawer-item.vue
Labels: Bug

#24120 Fixed applying of snapshot changes to/from alias fields
  .changeset/tiny-deers-scream.md
  api/src/utils/apply-diff.ts
  api/src/utils/get-snapshot-diff.ts
Labels: Bug, Data Modeling

#24126 Do not re-parse already parsed version delta in migration
  .changeset/brave-buttons-tap.md
  api/src/database/migrations/20240924B-populate-versioning-deltas.ts
Labels: Bug, Core

#24028 Add select all and delete buttons for notifications drawer
  .changeset/seven-owls-refuse.md
  app/src/views/private/components/notifications-drawer.vue
  contributors.yml
Labels: Feature, Core

#24128 Clear system and local caches on apply snapshot
  .changeset/nasty-meals-melt.md
  api/src/utils/apply-snapshot.ts
Labels: Bug, Core

#24127 Install vue devtools through vite
  app/package.json
  app/vite.config.js
  pnpm-lock.yaml
Labels: 🍰 Chore

#23994 New Crowdin updates
  app/src/lang/translations/bn-IN.yaml
  app/src/lang/translations/de-DE.yaml
  app/src/lang/translations/es-419.yaml
  app/src/lang/translations/es-ES.yaml
  app/src/lang/translations/es-MX.yaml
  app/src/lang/translations/ja-JP.yaml
  app/src/lang/translations/mr-IN.yaml
  app/src/lang/translations/ru-RU.yaml
  app/src/lang/translations/sv-SE.yaml
Labels: 🍰 Chore

#23907 Optimization: make readByQuery able to handle thousands of nested items
  .changeset/nervous-carrots-look.md
  api/src/database/run-ast/utils/merge-with-parent-items.ts
  api/src/services/payload.ts
  contributors.yml
Labels: Improvement, Querying, Core

#23920 Ensure floating view will not scroll top after route change (#19394)
  .changeset/curly-baboons-confess.md
  app/src/modules/activity/index.ts
  app/src/modules/files/index.ts
  app/src/modules/insights/index.ts
  app/src/modules/settings/index.ts
  app/src/views/private/private-view.vue
Labels: Improvement, Core

#24137 Fix: #24023 - Ensure different language in translation split view
  app/src/interfaces/translations/translations.vue
  contributors.yml
Labels: Bug

#24022 Assign admin policy to a new role created via command line when needed
  .changeset/giant-lamps-brush.md
  api/src/cli/commands/roles/create.ts
  api/src/cli/index.ts
  docs/self-hosted/cli.md
Labels: Bug, Core

#23981 Align itemsService variable names
  api/src/permissions/utils/fetch-dynamic-variable-context.ts
  api/src/services/collections.ts
  api/src/services/files.ts
  api/src/services/roles.ts
  api/src/services/tus/data-store.ts
Labels: 🍰 Chore, Core

#24158 Fixed broken links on policies reference
  docs/reference/system/policies.md
Labels: Docs

#23708 feat: support discriminated unions
  .changeset/shaggy-rules-raise.md
  contributors.yml
  sdk/src/types/output.ts
Labels: Feature, SDK

#24170 New Crowdin updates
  app/src/lang/translations/es-CL.yaml
  app/src/lang/translations/es-MX.yaml
  app/src/lang/translations/mr-IN.yaml
Labels: 🍰 Chore

#24166 Added Redis Sentinel cluster example
  contributors.yml
  docs/self-hosted/config-options.md
Labels: Improvement, Docs

#24157 Add ability to map oidc groups to Directus roles
  .changeset/swift-grapes-pump.md
  api/src/auth/drivers/openid.ts
  api/src/types/rolemap.ts
  contributors.yml
  docs/dictionary.txt
  docs/self-hosted/config-options.md
Labels: Feature, Authentication, Core

#24087 App: Fix try load image before it's completely uploaded
  .changeset/stupid-socks-dance.md
  app/src/components/v-upload.vue
  app/src/modules/files/routes/collection.vue
  app/src/stores/files.ts
Labels: Bug

#24218 Add tip to enable System Logs
  .changeset/big-crabs-lick.md
  docs/user-guide/settings/system-logs.md
Labels: Docs

#24180 New Crowdin updates
  app/src/lang/translations/mr-IN.yaml
Labels: 🍰 Chore

#24179 Fix retention time based query not being database agnostic
  .changeset/lemon-beers-tap.md
  api/src/database/helpers/date/dialects/oracle.ts
  api/src/database/index.ts
  api/src/schedules/retention.ts
Labels: Bug

#24208 Fix SDK policy type and updateRole function
  .changeset/breezy-pans-kneel.md
  sdk/src/rest/commands/update/roles.ts
  sdk/src/schema/access.ts
  sdk/src/schema/index.ts
  sdk/src/schema/role.ts
  sdk/src/types/utils.ts
Labels: Bug, SDK

#24234 Make the Add Collection Button for Policies More Visible
  app/src/components/v-select/v-select.vue
  app/src/interfaces/_system/system-permissions/add-collection.vue
  app/src/interfaces/_system/system-permissions/system-permissions.vue
Labels: Improvement
