Repository directus/directus, pull requests merged in 2024-11, with the labels that each got.

#23897 Add TUS support to the GCS storage driver
  .changeset/soft-spies-peel.md
  docs/self-hosted/config-options.md
  packages/storage-driver-gcs/src/index.ts
Labels: :cake: Improvement

#23716 Fix permission generation for Shares 📰
  .changeset/tidy-chicken-chew.md
  api/src/controllers/permissions.ts
  api/src/controllers/users.ts
  api/src/database/migrations/20240806A-permissions-policies.ts
  api/src/database/run-ast/utils/apply-case-when.ts
  api/src/middleware/authenticate.test.ts
  api/src/permissions/lib/fetch-permissions.ts
  api/src/permissions/utils/fetch-share-info.ts
  api/src/permissions/utils/get-permissions-for-share.test.ts
  api/src/permissions/utils/get-permissions-for-share.ts
  api/src/permissions/utils/merge-permissions.test.ts
  api/src/permissions/utils/merge-permissions.ts
  api/src/services/authentication.ts
  api/src/services/shares.ts
  api/src/types/auth.ts
  api/src/utils/get-accountability-for-token.test.ts
  api/src/utils/get-accountability-for-token.ts
  app/src/routes/shared/shared.vue
  packages/system-data/src/app-access-permissions/schema-access-permissions.yaml
  packages/system-data/src/fields/shares.yaml
  packages/types/src/accountability.ts
Labels: Bug, ⚠️ Enterprise, Permissions, :cake: Improvement

#23871 Fix M2O sort field SQL generation
  .changeset/smooth-dolphins-worry.md
  api/src/database/helpers/schema/dialects/cockroachdb.ts
  api/src/database/helpers/schema/dialects/mssql.ts
  api/src/database/helpers/schema/dialects/mysql.ts
  api/src/database/helpers/schema/dialects/oracle.ts
  api/src/database/helpers/schema/dialects/postgres.ts
  api/src/database/helpers/schema/types.ts
  api/src/database/run-ast/lib/get-db-query.ts
Labels: Bug

#23972 Fix invalid legacy permission fetching for comment mentions
  .changeset/tough-snails-accept.md
  api/src/services/comments.ts
Labels: Bug, Regression

#23410 Add retention support for `directus_activity` and `directus_revisions`
  .changeset/perfect-pens-laugh.md
  api/src/app.ts
  api/src/controllers/tus.ts
  api/src/schedules/retention.test.ts
  api/src/schedules/retention.ts
  api/src/schedules/telemetry.test.ts
  api/src/schedules/telemetry.ts
  api/src/schedules/tus.test.ts
  api/src/schedules/tus.ts
  api/src/telemetry/index.ts
  docs/self-hosted/config-options.md
  packages/env/src/constants/defaults.ts
Labels: Feature

#23956 Fix Cloudinary image preview in the File Library
  .changeset/cold-chairs-fry.md
  api/src/services/assets.ts
  packages/storage-driver-cloudinary/src/index.ts
Labels: Bug

#23904 Add TUS support to the Azure storage driver
  .changeset/gentle-walls-joke.md
  packages/storage-driver-azure/src/index.ts
Labels: :cake: Improvement

#23943 Add TUS support to the Cloudinary storage driver
  .changeset/honest-masks-turn.md
  packages/storage-driver-cloudinary/src/constants.ts
  packages/storage-driver-cloudinary/src/index.ts
Labels: :cake: Improvement

#23958 Add TUS support to the Supabase storage driver
  .changeset/clever-moose-pay.md
  packages/storage-driver-supabase/package.json
  packages/storage-driver-supabase/src/index.ts
  pnpm-lock.yaml
Labels: :cake: Improvement

#24026 Convert item field in `validateItemAccess` to boolean
  .changeset/proud-deers-kneel.md
  api/src/permissions/modules/validate-access/lib/validate-item-access.ts
Labels: Bug

#22392 Fix collection sorting for grouped collections
  .changeset/shy-taxis-fly.md
  app/src/interfaces/_system/system-collection/system-collection.vue
  app/src/interfaces/_system/system-collections/system-collections.vue
  app/src/modules/content/components/navigation-item.vue
  app/src/modules/content/composables/use-navigation.ts
  app/src/modules/content/index.ts
  app/src/modules/settings/routes/data-model/collections/collections.vue
  app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-relationship-m2a.vue
  app/src/modules/settings/routes/data-model/field-detail/field-detail-simple/relationship-configuration.vue
  app/src/modules/settings/routes/data-model/field-detail/shared/related-collection-select.vue
  app/src/modules/settings/routes/presets/item.vue
  app/src/stores/collections.ts
  app/src/utils/flatten-grouped-collection.test.ts
  app/src/utils/flatten-grouped-collections.ts
Labels: Improvement

#23997 App / M2O: Add option to navigate to related item
  .changeset/itchy-bulldogs-tan.md
  app/src/interfaces/select-dropdown-m2o/index.ts
  app/src/interfaces/select-dropdown-m2o/select-dropdown-m2o.vue
Labels: :cake: Improvement

#24027 Transform OracleDB query bindings to named parameters
  .changeset/afraid-brooms-hug.md
  api/src/database/helpers/schema/dialects/cockroachdb.ts
  api/src/database/helpers/schema/dialects/mssql.ts
  api/src/database/helpers/schema/dialects/oracle.ts
  api/src/database/helpers/schema/dialects/postgres.ts
  api/src/database/helpers/schema/types.ts
  api/src/database/helpers/schema/utils/prep-query-params.test.ts
  api/src/database/helpers/schema/utils/prep-query-params.ts
  api/src/database/index.ts
  api/src/database/run-ast/utils/with-preprocess-bindings.ts
Labels: Bug

#24040 Fix content version usage with SEARCH method
  .changeset/fresh-tables-check.md
  api/src/controllers/items.ts
Labels: Bug

#23749 Removed outdated logic for versioning
  .changeset/metal-rules-pretend.md
  api/src/controllers/versions.ts
  api/src/database/migrations/20240924B-populate-versioning-deltas.ts
  api/src/services/versions.ts
Labels: :cake: Improvement

#24002 Fix enforcing `chunkSize` when TUS is not enabled and update the default `TUS_CHUNK_SIZE` to `8mb`
  .changeset/cyan-sloths-appear.md
  api/src/storage/register-locations.ts
  app/src/utils/upload-file.ts
  docs/self-hosted/config-options.md
  packages/constants/src/files.ts
  packages/env/src/constants/defaults.ts
  packages/storage-driver-azure/src/index.ts
  packages/storage-driver-cloudinary/src/index.ts
  packages/storage-driver-gcs/package.json
  packages/storage-driver-gcs/src/index.ts
  packages/storage-driver-supabase/package.json
  packages/storage-driver-supabase/src/index.ts
  pnpm-lock.yaml
Labels: Bug

#23748 Removed outdated logic for comments
  .changeset/silver-comics-arrive.md
  api/src/controllers/activity.ts
  api/src/controllers/comments.ts
  api/src/database/migrations/20240924A-migrate-legacy-comments.ts
  api/src/services/comments.ts
  api/src/services/graphql/index.ts
  api/src/utils/get-service.ts
  packages/system-data/src/app-access-permissions/app-access-permissions.yaml
  packages/system-data/src/fields/activity.yaml
  sdk/src/schema/activity.ts
Labels: :cake: Improvement

#24036 Storage / S3: Make connection settings configurable
  .changeset/angry-frogs-beam.md
  packages/storage-driver-s3/package.json
  packages/storage-driver-s3/src/index.ts
  pnpm-lock.yaml
Labels: S3

#24096 Cast versioning item key to string
  .changeset/tame-peaches-exist.md
  app/src/modules/content/components/version-menu.vue
Labels: Bug, Versioning, Core

#24093 v-table html specs issue #24091
  .changeset/odd-seas-lick.md
  app/src/components/v-table/v-table.vue
  contributors.yml
Labels: Improvement, Core

#24003 Allow the login timeout for OpenID SSO login to be adjusted
  .changeset/violet-drinks-jump.md
  api/src/auth/drivers/openid.ts
  contributors.yml
  docs/self-hosted/config-options.md
Labels: Feature, Authentication, Core

#20271 Prefill sort field on relational interfaces
  .changeset/sweet-steaks-film.md
  app/src/composables/use-relation-multiple.test.ts
  app/src/composables/use-relation-multiple.ts
Labels: Bug

#24108 Merge commit from fork
  .changeset/healthy-crews-cover.md
  api/src/websocket/controllers/base.ts
  api/src/websocket/controllers/graphql.ts
Labels: Bug
