Repository directus/directus, pull requests merged in 2024-05, with the labels that each got.

#22352 App: Fix rate limit when having much relationships
  .changeset/stupid-dingos-drop.md
  app/src/api.ts
  app/src/stores/requests.ts
  app/src/stores/server.test.ts
  app/src/stores/server.ts
  app/src/stores/user.test.ts
  app/src/stores/user.ts
Labels: :warning: Enterprise, :file_folder: REST

#22349 Change `guessType` to retain value types if they are known
  .changeset/good-elephants-knock.md
  packages/env/src/lib/cast.test.ts
  packages/env/src/utils/guess-type.test.ts
  packages/env/src/utils/guess-type.ts
  packages/utils/shared/to-boolean.test.ts
Labels: :cake: Bug, :file_folder: Environment Variables

#22350 Fix arrow misalignment in M2A relation settings
  .changeset/unlucky-bugs-refuse.md
  app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-relationship-m2a.vue
Labels: :cake: Bug, :cake: Improvement

#22353 Improved session token validation
  .changeset/late-lions-pump.md
  api/src/utils/get-accountability-for-token.ts
  api/src/utils/verify-session-jwt.ts
Labels: :cake: Bug, :cake: Improvement

#22332 Improved values redacting
  .changeset/purple-shirts-care.md
  api/src/database/run-ast.ts
  api/src/services/payload.test.ts
  api/src/services/payload.ts
Labels: :cake: Bug, :file_folder: Access Control

#22375 Fix `system-filter` wrap behavior
  app/src/interfaces/_system/system-filter/system-filter.vue
Labels: :cake: Bug

#22346 Specific error type mapping in `isDirectusError` function
  .changeset/smooth-games-hug.md
  packages/errors/package.json
  packages/errors/src/errors/contains-null-values.ts
  packages/errors/src/errors/range-not-satisfiable.ts
  packages/errors/src/errors/service-unavailable.ts
  packages/errors/src/errors/unprocessable-content.ts
  packages/errors/src/is-directus-error.test-d.ts
  packages/errors/src/is-directus-error.ts
  packages/errors/src/types.ts
Labels: :cake: Improvement

#22378 Fix default naming of related collection junction field for translations
  .changeset/fluffy-walls-destroy.md
  app/src/modules/settings/routes/data-model/field-detail/store/alterations/translations.ts
Labels: :cake: Bug, :cake: Improvement, :file_folder: Data Modeling

#22318 App: Allow interpolation string as the only value on `input-code` interface
  .changeset/wise-donuts-sit.md
  app/src/interfaces/input-code/input-code.vue
Labels: :warning: Enterprise, :file_folder: Flows

#22288 [SDK] Fix inferred partial field types, when using _and/_or filters in queries
  .changeset/rotten-colts-divide.md
  sdk/package.json
  sdk/src/types/filters.ts
  sdk/src/types/utils.ts
  sdk/tests/fields.test-d.ts
  sdk/tests/filters.test-d.ts
  sdk/tests/no-schema.test-d.ts
  sdk/vitest.config.ts
Labels: :cake: Bug, :file_folder: SDK

#22382 Replace deprecated `--primary` and `--secondary` CSS vars and fix conditional panel styling
  .changeset/bright-buttons-develop.md
  app/src/interfaces/map/style.ts
  app/src/lang/translations/en-US.yaml
  app/src/layouts/map/style.ts
  app/src/panels/bar-chart/index.ts
  app/src/panels/bar-chart/panel-bar-chart.vue
  app/src/panels/meter/index.ts
  app/src/panels/meter/panel-meter.vue
  app/src/panels/metric-list/panel-metric-list.vue
  app/src/panels/metric/panel-metric.vue
  app/src/panels/pie-chart/index.ts
  app/src/panels/pie-chart/panel-pie-chart.vue
  app/src/panels/time-series/panel-time-series.vue
  app/src/utils/generate-favicon.ts
Labels: :cake: Bug, :file_folder: Insights

#22320 Don't require `KEY` or `SECRET` to be set on startup
  .changeset/weak-chefs-sniff.md
  api/src/app.test.ts
  api/src/app.ts
  api/src/auth/drivers/oauth2.ts
  api/src/auth/drivers/openid.ts
  api/src/cli/utils/create-env/env-stub.liquid
  api/src/cli/utils/create-env/index.ts
  api/src/controllers/auth.ts
  api/src/services/authentication.ts
  api/src/services/graphql/index.ts
  api/src/services/server.ts
  api/src/services/shares.ts
  api/src/services/users.ts
  api/src/utils/get-accountability-for-token.ts
  api/src/utils/get-secret.ts
  docs/contributing/running-locally.md
  docs/getting-started/quickstart.md
  docs/reference/system/server.md
  docs/self-hosted/config-options.md
  docs/self-hosted/docker-guide.md
  docs/self-hosted/quickstart.md
  packages/env/src/constants/directus-variables.ts
  tests/blackbox/common/config.ts
Labels: :cake: Optimization

#22227 Consolidate content versioning
  .changeset/loud-avocados-serve.md
  api/src/controllers/versions.ts
  api/src/database/migrations/20240415A-consolidate-content-versioning.ts
  api/src/services/versions.ts
  packages/system-data/src/fields/versions.yaml
  packages/types/src/versions.ts
  sdk/src/schema/version.ts
Labels: :cake: Optimization

#22048 Fix handling of invalid and empty filter queries
  .changeset/three-dolls-ring.md
  api/src/utils/apply-query.ts
  api/src/utils/sanitize-query.test.ts
  api/src/utils/sanitize-query.ts
  api/src/utils/validate-query.ts
  packages/utils/shared/parse-filter.test.ts
Labels: :cake: Bug, :file_folder: REST

#22013 Fix bundle (re-)loading
  .changeset/hot-dolphins-shop.md
  api/src/extensions/lib/get-extensions-settings.ts
Labels: :cake: Bug, :file_folder: Extensions, :warning: Enterprise

#22125 Add public registration
  .changeset/dry-otters-attend.md
  api/src/controllers/users.ts
  api/src/database/migrations/20240422A-public-registration.ts
  api/src/middleware/rate-limiter-global.ts
  api/src/middleware/rate-limiter-registration.ts
  api/src/services/graphql/index.ts
  api/src/services/mail/templates/user-registration.liquid
  api/src/services/server.ts
  api/src/services/users.ts
  app/package.json
  app/src/lang/translations/en-US.yaml
  app/src/router.ts
  app/src/routes/login/login.vue
  app/src/routes/register/register-form.vue
  app/src/routes/register/register.vue
  app/src/stores/server.ts
  docs/reference/system/users.md
  docs/self-hosted/config-options.md
  packages/env/src/constants/defaults.ts
  packages/env/src/constants/directus-variables.ts
  packages/system-data/src/fields/settings.yaml
  packages/system-data/src/fields/users.yaml
  packages/types/src/users.ts
  pnpm-lock.yaml
  sdk/src/rest/commands/server/info.ts
  sdk/src/rest/commands/utils/users.ts
Labels: :cake: Improvement, :cake: Feature, :file_folder: Authentication

#22421 Confirm label
  .changeset/brown-cobras-roll.md
  app/src/lang/translations/en-US.yaml
  app/src/routes/register/register-form.vue
Labels: :cake: Improvement

#22425 Add maildev container for debugging emails
  docker-compose.yml
  docs/contributing/running-locally.md
Labels: :cake: Chore

#22409 Fix the failing auto-creation of default languages in translation field setup
  .changeset/curvy-houses-grin.md
  app/src/modules/settings/routes/data-model/field-detail/store/index.ts
Labels: :cake: Bug, :file_folder: Data Modeling

#22426 `system-filter`: Prevent text wrap, and keep field list dropdown for functions
  .changeset/yellow-frogs-warn.md
  app/src/interfaces/_system/system-filter/nodes.vue
  app/src/interfaces/_system/system-filter/utils.ts
Labels: :cake: Improvement

#22431 Added session token note to sso docs.
  docs/self-hosted/sso.md
Labels: :file_folder: Documentation

#22432 Fix running SDK in dev mode
  .changeset/empty-baboons-wave.md
  sdk/tsup.config.js
Labels: :cake: Improvement, :file_folder: SDK

#22450 Add missing `mailService` in Stripe Hook extension guide
  contributors.yml
  docs/guides/extensions/hooks-add-stripe-customer.md
Labels: :file_folder: Documentation

#22458 Add focal point translations
  .changeset/fresh-garlics-cheer.md
  app/src/lang/translations/en-US.yaml
Labels: :cake: Bug

#22471 Update glossary docs: Fix item description
  contributors.yml
  docs/user-guide/overview/glossary.md
Labels: :file_folder: Documentation

#22475 add templates directory as volume in docker compose file
  contributors.yml
  docs/self-hosted/docker-guide.md
Labels: :file_folder: Documentation

#22463 Fix error message in Hook Twilio guide
  docs/guides/extensions/hooks-validate-number-twilio.md
Labels: :file_folder: Documentation

#22448 Fix regression in `count` database helper when counting filtered related fields
  .changeset/plenty-trees-draw.md
  api/src/database/helpers/fn/types.ts
  api/src/utils/apply-query.ts
Labels: :cake: Bug, :cake: Regression, :file_folder: Data Modeling

#22480 Add database info to bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: :cake: Chore

#22462 Add reload button when the app errors out
  .changeset/old-lizards-sleep.md
  app/src/app.vue
  app/src/lang/translations/en-US.yaml
Labels: :cake: Improvement

#22464 Reduce access token refreshing if it is still fresh
  .changeset/bright-trains-greet.md
  app/src/auth.ts
  app/src/constants.ts
  app/src/sdk.ts
Labels: :cake: Improvement, :file_folder: Authentication

#22459 Prevent "invalid token" from being blocking
  api/src/middleware/authenticate.test.ts
  api/src/middleware/authenticate.ts
  api/src/utils/verify-session-jwt.ts
Labels: :cake: Improvement, :warning: Enterprise, :file_folder: Authentication

#22501 Fix database session duration
  .changeset/dry-carrots-sin.md
  api/src/services/authentication.ts
Labels: :cake: Bug, :file_folder: Authentication

#22511 Improve changeset clarity
  .changeset/dry-carrots-sin.md
Labels: :cake: Chore

#22529 Adjust "refresh" blackbox test
  tests/blackbox/tests/common/logger/redact.test.ts
  tests/blackbox/tests/db/routes/auth/refresh.test.ts
Labels: :cake: Chore

#22517 Fix item fetching in calendar layout when switching view
  .changeset/strong-garlics-visit.md
  app/src/layouts/calendar/index.ts
Labels: :cake: Bug, :warning: Enterprise

#22530 Fix file selection drawer failing when some files fail loading
  .changeset/brave-students-tap.md
  .changeset/nice-pans-applaud.md
  app/src/layouts/cards/components/card.vue
Labels: :cake: Bug, :file_folder: Forms

#22503 Session token "safety window" when refreshing
  .changeset/five-moons-complain.md
  api/src/database/migrations/20240515A-add-session-window.ts
  api/src/services/authentication.ts
  docs/self-hosted/config-options.md
  packages/env/src/constants/defaults.ts
  packages/env/src/constants/directus-variables.ts
Labels: :cake: Improvement, :warning: Enterprise, :file_folder: Authentication

#22531 Adjust SAML blackbox test
  tests/blackbox/common/config.ts
  tests/blackbox/tests/db/routes/auth/saml.test.ts
Labels: :cake: Chore

#22551 Packages / Cloudinary Storage: Fix move file when ROOT is defined
  .changeset/plenty-boxes-appear.md
  packages/storage-driver-cloudinary/src/index.test.ts
  packages/storage-driver-cloudinary/src/index.ts
Labels: :warning: Enterprise

#22587 Fix logic to update parent bundles enabled status
  .changeset/two-walls-deliver.md
  api/src/services/extensions.ts
Labels: :cake: Bug, :file_folder: Extensions

#22565 Add support for custom URLs for email verification
  .changeset/stale-donuts-whisper.md
  api/src/controllers/users.ts
  api/src/services/graphql/index.ts
  api/src/services/users.ts
  docs/self-hosted/config-options.md
  packages/env/src/constants/directus-variables.ts
  packages/types/src/users.ts
  sdk/src/rest/commands/utils/users.ts
Labels: :cake: Improvement, :file_folder: Public Registration

#22599 Fix sdk api endpoint for registration verification
  .changeset/rancher-booker-minnie.md
  contributors.yml
  sdk/src/rest/commands/utils/users.ts
Labels: :cake: Bug, :file_folder: SDK, :file_folder: Public Registration

#22567 Document public registration
  docs/reference/authentication.md
  docs/user-guide/user-management/users.md
Labels: :file_folder: Documentation, :file_folder: Public Registration

#22604 Implemented random string command in the SDK
  .changeset/orange-donkeys-flow.md
  docs/reference/system/utilities.md
  sdk/src/rest/commands/utils/index.ts
  sdk/src/rest/commands/utils/random.ts
Labels: :cake: Bug, :file_folder: SDK

#22605 Added session next_token to system-data
  .changeset/calm-boats-tie.md
  packages/system-data/src/fields/sessions.yaml
Labels: :cake: Bug

#22564 Implement missing batch functions SDK
  .changeset/silly-melons-smoke.md
  sdk/src/rest/commands/update/collections.ts
  sdk/src/rest/commands/update/dashboards.ts
  sdk/src/rest/commands/update/files.ts
  sdk/src/rest/commands/update/flows.ts
  sdk/src/rest/commands/update/folders.ts
  sdk/src/rest/commands/update/items.ts
  sdk/src/rest/commands/update/notifications.ts
  sdk/src/rest/commands/update/operations.ts
  sdk/src/rest/commands/update/panels.ts
  sdk/src/rest/commands/update/permissions.ts
  sdk/src/rest/commands/update/presets.ts
  sdk/src/rest/commands/update/roles.ts
  sdk/src/rest/commands/update/shares.ts
  sdk/src/rest/commands/update/translations.ts
  sdk/src/rest/commands/update/users.ts
  sdk/src/rest/commands/update/versions.ts
  sdk/src/rest/utils/throw-if-empty.ts
Labels: :cake: Improvement, :file_folder: SDK

#22607 Fix links & typo in docs issue template
  .github/ISSUE_TEMPLATE/docs_problem.yml
  .github/ISSUE_TEMPLATE/docs_suggestions.yml
Labels: :cake: Chore
