Repository directus/directus, pull requests merged in 2025-07, with the labels that each got.

#25139 Fix parsing functions in aliases
  .changeset/easy-pandas-sin.md
  api/src/database/get-ast-from-query/lib/parse-fields.test.ts
  api/src/database/get-ast-from-query/lib/parse-fields.ts
  api/src/database/run-ast/utils/apply-parent-filters.ts
  api/src/database/run-ast/utils/get-field-alias.ts
  api/src/database/run-ast/utils/remove-temporary-fields.ts
  api/src/permissions/modules/validate-access/lib/validate-item-access.ts
  api/src/types/ast.ts
Labels: Run Blackbox

#25458 Fix missing Netlify redirection for links without `.html`
  docs/_redirects
  docs/netlify.toml
Labels: Docs

#25486 Update deps in @directus/extensions
  .changeset/cruel-chairs-cut.md
  packages/extensions-sdk/package.json
  pnpm-lock.yaml
Labels: Run Blackbox

#25504 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Chore

#25344 Add `authenticate` hook to websockets
  .changeset/hip-jokes-cheat.md
  api/src/websocket/authenticate.test.ts
  api/src/websocket/authenticate.ts
  api/src/websocket/controllers/base.ts
  api/src/websocket/controllers/graphql.ts
  contributors.yml
Labels: Improvement, Run Blackbox

#25509 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Chore

#25317 Add support for bundling with Rolldown and improve app extensions loading by streaming from disk
  .changeset/violet-sloths-shine.md
  api/package.json
  api/src/controllers/extensions.ts
  api/src/extensions/manager.ts
  packages/env/src/constants/defaults.ts
  packages/env/src/constants/directus-variables.ts
  packages/env/src/constants/type-map.ts
  pnpm-lock.yaml
Labels: Improvement, Engine, Extensions

#25452 Sort weights when constructing google font ID
  .changeset/social-queens-like.md
  packages/themes/package.json
  packages/themes/src/composables/use-fonts.test.ts
  packages/themes/src/composables/use-fonts.ts
  pnpm-lock.yaml
Labels: Bug, Med Impact, Low Reach
