Repository directus/directus, pull requests merged in 2025-09, with the labels that each got.

#25801 Fix constraint errors not being propagated in `MSSQL`
  .changeset/slimy-laws-relate.md
  api/src/database/errors/dialects/mssql.ts
Labels: Bug, Validation, MS SQL Server, Run Blackbox

#25744 Fix `USER_CREATED`, `USER_UPDATED`, `DATE_CREATED`, and `DATE_UPDATED` values in content versioning
  .changeset/itchy-trams-follow.md
  api/src/controllers/versions.ts
  api/src/services/items.ts
  api/src/services/payload.ts
  api/src/services/versions.ts
  api/src/utils/versioning/deep-map-with-schema.test.ts
  api/src/utils/versioning/deep-map-with-schema.ts
  api/src/utils/versioning/handle-version.ts
  api/src/utils/versioning/split-recursive.test.ts
  api/src/utils/versioning/split-recursive.ts
  app/src/modules/content/components/version-promote-drawer.vue
  app/src/modules/content/routes/item.vue
  packages/types/src/items.ts
  packages/types/src/services.ts
  pnpm-lock.yaml
Labels: Bug, Versioning, Run Blackbox, Engine

#25845 Remove marketplace beta chips on route and nav
  app/src/modules/settings/components/navigation.vue
  app/src/modules/settings/routes/marketplace/routes/registry/registry.vue
Labels: No Changeset

#25771 New Crowdin updates
  app/src/lang/translations/ar-SA.yaml
  app/src/lang/translations/az-AZ.yaml
  app/src/lang/translations/bg-BG.yaml
  app/src/lang/translations/br-FR.yaml
  app/src/lang/translations/bs-BA.yaml
  app/src/lang/translations/ca-ES.yaml
  app/src/lang/translations/ckb-IR.yaml
  app/src/lang/translations/cs-CZ.yaml
  app/src/lang/translations/da-DK.yaml
  app/src/lang/translations/de-DE.yaml
  app/src/lang/translations/en-CA.yaml
  app/src/lang/translations/en-GB.yaml
  app/src/lang/translations/eo-UY.yaml
  app/src/lang/translations/es-419.yaml
  app/src/lang/translations/es-CL.yaml
  app/src/lang/translations/es-ES.yaml
  app/src/lang/translations/es-MX.yaml
  app/src/lang/translations/et-EE.yaml
  app/src/lang/translations/fa-IR.yaml
  app/src/lang/translations/fi-FI.yaml
  app/src/lang/translations/fr-CA.yaml
  app/src/lang/translations/fr-FR.yaml
  app/src/lang/translations/he-IL.yaml
  app/src/lang/translations/hi-IN.yaml
  app/src/lang/translations/hr-HR.yaml
  app/src/lang/translations/hu-HU.yaml
  app/src/lang/translations/id-ID.yaml
  app/src/lang/translations/is-IS.yaml
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/ja-JP.yaml
  app/src/lang/translations/ka-GE.yaml
  app/src/lang/translations/kmr-TR.yaml
  app/src/lang/translations/ko-KR.yaml
  app/src/lang/translations/lt-LT.yaml
  app/src/lang/translations/mn-MN.yaml
  app/src/lang/translations/mr-IN.yaml
  app/src/lang/translations/ne-NP.yaml
  app/src/lang/translations/nl-NL.yaml
  app/src/lang/translations/pl-PL.yaml
  app/src/lang/translations/pt-BR.yaml
  app/src/lang/translations/pt-PT.yaml
  app/src/lang/translations/ro-RO.yaml
  app/src/lang/translations/ru-RU.yaml
  app/src/lang/translations/sk-SK.yaml
  app/src/lang/translations/sl-SI.yaml
  app/src/lang/translations/sq-AL.yaml
  app/src/lang/translations/sr-CS.yaml
  app/src/lang/translations/sv-SE.yaml
  app/src/lang/translations/th-TH.yaml
  app/src/lang/translations/tr-TR.yaml
  app/src/lang/translations/uk-UA.yaml
  app/src/lang/translations/vi-VN.yaml
  app/src/lang/translations/zh-CN.yaml
  app/src/lang/translations/zh-TW.yaml
Labels: Chore, No Changeset

#25849 Use release PAT to trigger workflows
  .github/workflows/prepare-release.yml
Labels: No Changeset

#25854 Revert release workflow for v11.12.0
  .github/workflows/release.yml
Labels: No Changeset
