Repository directus/directus, pull requests merged in 2025-05, with the labels that each got.

#25129 Fix seeding on blackbox tests for existing db
  .changeset/empty-papayas-raise.md
  api/package.json
  package.json
  pnpm-lock.yaml
  tests/blackbox/setup/seeds/02_tests_flow.js
Labels: Chore, Run Blackbox

#25220 Add changesets
  .changeset/soft-hoops-slide.md
  .changeset/tired-corners-pick.md
Labels: Chore

#25128 Fix including aliases in wildcard selection
  .changeset/mean-bottles-brush.md
  api/src/database/get-ast-from-query/lib/convert-wildcards.test.ts
  api/src/database/get-ast-from-query/lib/convert-wildcards.ts
  api/src/database/get-ast-from-query/lib/parse-fields.ts
Labels: Bug, Engine

#25114 Add `ip`, `userAgent` and `origin` for ws activity
  .changeset/three-doodles-marry.md
  api/package.json
  api/src/app.test.ts
  api/src/middleware/authenticate.test.ts
  api/src/utils/get-ip-from-req.test.ts
  api/src/utils/get-ip-from-req.ts
  api/src/websocket/controllers/base.ts
  api/src/websocket/types.ts
  pnpm-lock.yaml
Labels: Bug, Run Blackbox

#25204 Fix cache skipping for getSchema
  .changeset/smart-shoes-tap.md
  api/src/services/relations.ts
  api/src/utils/get-schema.ts
  tests/blackbox/tests/db/routes/schema/schema.test.ts
Labels: Run Blackbox
