Repository directus/directus, pull requests merged in 2025-06, with the labels that each got.

#25216 Replace mapValuesDeep with deepMap
  .changeset/fine-boats-brush.md
  api/src/flows.ts
  api/src/utils/map-values-deep.test.ts
  api/src/utils/map-values-deep.ts
  packages/utils/shared/deep-map.test.ts
  packages/utils/shared/deep-map.ts
Labels: Run Blackbox

#24830 Fix translating m2a filters on GQL only when applicable
  .changeset/petite-symbols-drum.md
  api/src/services/graphql/resolvers/mutation.ts
  api/src/services/graphql/resolvers/query.ts
  api/src/services/graphql/resolvers/system.ts
  api/src/services/graphql/schema/parse-query.ts
  api/src/services/graphql/schema/read.ts
  api/src/services/graphql/subscription.ts
  api/src/services/graphql/utils/filter-replace-m2a.test.ts
  api/src/services/graphql/utils/filter-replace-m2a.ts
  packages/schema-builder/src/index.ts
  packages/utils/shared/parse-filter.ts
Labels: Improvement, GraphQL, Run Blackbox, Engine

#25132 Add ldap support for sdk login and improve refresh/logout consistency
  .changeset/gold-frogs-yell.md
  app/src/auth.ts
  sdk/src/auth/composable.ts
  sdk/src/auth/types.ts
  sdk/src/rest/commands/auth/login.ts
  sdk/src/rest/commands/auth/logout.ts
  sdk/src/rest/commands/auth/refresh.ts
Labels: Bug, SDK

#25356 Remove unnecessary redacting of env for log operation
  api/src/flows.ts
Labels: Run Blackbox

#25360 New Crowdin updates
  app/src/lang/translations/ar-SA.yaml
  app/src/lang/translations/th-TH.yaml
  app/src/lang/translations/zh-CN.yaml
Labels: Chore
