Repository directus/directus, pull requests merged in 2025-03, with the labels that each got.

#24725 Add implicit _some behavior in applyFilter for missing operators
  .changeset/grumpy-lobsters-sort.md
  api/src/utils/apply-query.ts
  contributors.yml
Labels: Querying, Run Blackbox, Engine

#24640 Additional integration test for case when queries
  tests/blackbox/common/functions.ts
  tests/blackbox/setup/sequential-tests.ts
  tests/blackbox/tests/db/routes/items/case-when.seed.ts
  tests/blackbox/tests/db/routes/items/case-when.test.ts
Labels: Querying, Run Blackbox

#24770 Enabled deduplication of parameters again for certain DBs
  api/src/database/helpers/capabilities/dialects/postgres.ts
  api/src/database/helpers/capabilities/types.ts
  api/src/database/helpers/schema/dialects/mssql.ts
  api/src/database/helpers/schema/dialects/oracle.ts
  api/src/database/helpers/schema/types.ts
  api/src/database/helpers/schema/utils/prep-query-params.ts
  api/src/database/helpers/schema/utils/prep-query-parms.test.ts
  api/src/database/run-ast/lib/get-db-query.ts
  api/src/database/run-ast/utils/with-preprocess-bindings.ts
Labels: Run Blackbox

#24776 Error handling in bb test utility
  tests/blackbox/common/functions.ts
  tests/blackbox/setup/sequential-tests.ts
Labels: Run Blackbox

#24764 Add `isDirectusError` type guard to the SDK
  .changeset/early-cougars-turn.md
  sdk/src/index.ts
  sdk/src/types/error.ts
  sdk/src/types/index.ts
  sdk/src/utils/is-directus-error.ts
Labels: Improvement, SDK

#24772 Do not throw unhandled error on passing a null query
  .changeset/cuddly-dragons-flow.md
  api/src/websocket/handlers/subscribe.ts
  api/src/websocket/messages.ts
Labels: Bug, Engine

#24791 Updated policy type definition
  .changeset/four-hotels-repair.md
  packages/types/src/policies.ts
Labels: Improvement, Permissions

#24788 Improve error handling for `/utils/hash/verify`
  .changeset/odd-months-see.md
  api/src/controllers/utils.ts
Labels: Bug, CRUD

#24604 Fix broken query binding de-duplication
  .changeset/empty-spoons-walk.md
  api/src/database/helpers/capabilities/dialects/default.ts
  api/src/database/helpers/capabilities/dialects/mysql.ts
  api/src/database/helpers/capabilities/dialects/postgres.ts
  api/src/database/helpers/capabilities/index.ts
  api/src/database/helpers/capabilities/types.ts
  api/src/database/helpers/index.ts
  api/src/database/helpers/schema/dialects/cockroachdb.ts
  api/src/database/helpers/schema/dialects/postgres.ts
  api/src/database/run-ast/lib/get-db-query.ts
  api/src/utils/apply-query.ts
  tests/blackbox/common/functions.ts
  tests/blackbox/tests/db/routes/items/case-when.seed.ts
  tests/blackbox/tests/db/routes/items/case-when.test.ts
Labels: Run Blackbox

#24609 Fix relational updates payload generation
  .changeset/tricky-bobcats-fail.md
  api/src/services/payload.ts
Labels: Permissions, Run Blackbox, Engine

#24817 Improve invalid asset transformation parameter value error handling
  .changeset/green-areas-design.md
  api/src/services/assets.ts
  contributors.yml
Labels: Improvement, Assets, Run Blackbox

#24790 Fix re-linking new pointer references to existing links
  .changeset/swift-glasses-lick.md
  app/src/modules/settings/routes/flows/flow.vue
Labels: Bug, Studio, Flows

#24751 Add path information to validation errors
  .changeset/loud-carrots-jam.md
  api/src/permissions/modules/process-payload/process-payload.ts
  api/src/services/items.ts
  api/src/services/payload.ts
  api/src/services/users.ts
  api/src/types/services.ts
  packages/validation/src/errors/failed-validation.test.ts
  packages/validation/src/errors/failed-validation.ts
  packages/validation/src/utils/joi-to-error-extensions.ts
Labels: Run Blackbox

#24826 Add `omitKey` option to `getConfigFromEnv`
  .changeset/tasty-zebras-enjoy.md
  api/src/app.ts
  api/src/auth/drivers/oauth2.ts
  api/src/auth/drivers/openid.ts
  api/src/database/index.ts
  api/src/logger/index.ts
  api/src/rate-limiter.ts
  api/src/utils/generate-hash.ts
  api/src/utils/get-config-from-env.test.ts
  api/src/utils/get-config-from-env.ts
Labels: Bug, Authentication, Run Blackbox, Engine

#24836 Add error logging for invalid `PUBLIC_URL` on SSO redirection
  .changeset/some-pigs-greet.md
  api/src/utils/is-login-redirect-allowed.test.ts
  api/src/utils/is-login-redirect-allowed.ts
Labels: Improvement, Authentication

#24555 Fix keys being optional on writes
  .changeset/pink-wolves-sleep.md
  api/src/services/graphql/resolvers/get-collection-type.ts
  api/src/services/graphql/resolvers/get-field-type.ts
  api/src/services/graphql/resolvers/get-relation-type.ts
  api/src/services/graphql/resolvers/system-admin.ts
  api/src/services/graphql/resolvers/system.ts
Labels: GraphQL, Run Blackbox

#24812 Fix filter hook altered payload not passed to action hook on `create`
  .changeset/good-colts-own.md
  api/src/services/items.ts
Labels: Bug, Engine, Flows

#24644 Add _some and _none support to GQL.
  .changeset/wet-lizards-run.md
  api/src/services/graphql/schema/read.ts
Labels: GraphQL, Querying, Run Blackbox

#24558 Add OAuth role mapping support
  .changeset/six-bees-grab.md
  api/src/auth/drivers/oauth2.ts
  contributors.yml
Labels: Feature, Run Blackbox, Auth

#24635 Allow for dynamic variable paths in filters
  .changeset/slimy-lions-call.md
  api/src/app.ts
  api/src/controllers/access.ts
  api/src/controllers/comments.ts
  api/src/controllers/dashboards.ts
  api/src/controllers/files.ts
  api/src/controllers/flows.ts
  api/src/controllers/folders.ts
  api/src/controllers/items.ts
  api/src/controllers/notifications.ts
  api/src/controllers/operations.ts
  api/src/controllers/panels.ts
  api/src/controllers/permissions.ts
  api/src/controllers/policies.ts
  api/src/controllers/presets.ts
  api/src/controllers/roles.ts
  api/src/controllers/shares.ts
  api/src/controllers/translations.ts
  api/src/controllers/users.ts
  api/src/controllers/utils.ts
  api/src/controllers/versions.ts
  api/src/controllers/webhooks.ts
  api/src/middleware/sanitize-query.ts
  api/src/middleware/validate-batch.ts
  api/src/operations/item-delete/index.ts
  api/src/operations/item-read/index.ts
  api/src/operations/item-update/index.ts
  api/src/permissions/modules/process-ast/utils/context-has-dynamic-variables.test.ts
  api/src/permissions/modules/process-ast/utils/context-has-dynamic-variables.ts
  api/src/permissions/types.ts
  api/src/services/graphql/resolvers/mutation.ts
  api/src/services/graphql/resolvers/query.ts
  api/src/services/graphql/resolvers/system.ts
  api/src/services/graphql/schema/index.ts
  api/src/services/graphql/schema/parse-query.ts
  api/src/services/graphql/schema/read.ts
  api/src/services/graphql/subscription.ts
  api/src/services/graphql/utils/aggregate-query.ts
  api/src/utils/sanitize-query.test.ts
  api/src/utils/sanitize-query.ts
  api/src/websocket/handlers/items.ts
  api/src/websocket/handlers/subscribe.ts
Labels: Improvement, Run Blackbox

#24746 New Crowdin updates
  app/src/lang/translations/et-EE.yaml
  app/src/lang/translations/fr-CA.yaml
  app/src/lang/translations/it-IT.yaml
  app/src/lang/translations/pt-PT.yaml
  app/src/lang/translations/vi-VN.yaml
Labels: Chore

#24996 Revert adding of implicit _some in #24725 due to regressions
  .changeset/loose-experts-own.md
  api/src/utils/apply-query.ts
Labels: Regression, Run Blackbox, Patch

#24975 Skip unnecessary fetching of dynamic variables
  .changeset/wet-ads-sniff.md
  api/src/permissions/modules/process-payload/process-payload.ts
Labels: Optimization, Run Blackbox, Patch

#24988 Fix search applying minimum app permissions when full access is allowed
  .changeset/busy-sloths-draw.md
  api/src/utils/apply-query.test.ts
  api/src/utils/apply-query.ts
Labels: Bug, Regression, Querying, Run Blackbox, Engine, Patch

#24977 Fix requiring roles and/or policies for admin accountability
  .changeset/shiny-forks-leave.md
  api/src/permissions/modules/process-payload/process-payload.test.ts
  api/src/permissions/modules/process-payload/process-payload.ts
  api/src/permissions/utils/fetch-dynamic-variable-data.ts
Labels: Bug, Regression, Permissions, Run Blackbox, Patch
