Repository directus/directus, pull requests merged in 2025-01, with the labels that each got.

#24188 Add activity tracking for field deletion
  .changeset/weak-queens-count.md
  api/src/services/fields.ts
Labels: Bug, Core

#24311 Update copyright year to 2025
  api/license
  app/license
  directus/license
  directus/readme.md
  license
  packages/components/license
  packages/composables/license
  packages/constants/license
  packages/create-directus-extension/license
  packages/create-directus-project/license
  packages/env/license
  packages/errors/license
  packages/extensions-registry/license
  packages/extensions-sdk/license
  packages/extensions/license
  packages/format-title/license
  packages/memory/license
  packages/pressure/license
  packages/random/license
  packages/release-notes-generator/license
  packages/schema/license
  packages/specs/license
  packages/storage-driver-azure/license
  packages/storage-driver-cloudinary/license
  packages/storage-driver-gcs/license
  packages/storage-driver-local/license
  packages/storage-driver-s3/license
  packages/storage-driver-supabase/license
  packages/storage/license
  packages/stores/license
  packages/system-data/license
  packages/themes/license
  packages/tsconfig/license
  packages/types/license
  packages/update-check/license
  packages/utils/license
  packages/validation/license
  sdk/license
Labels: 🍰 Chore

#24275 Fixed the sdk not returning `null` on 204 response
  .changeset/wild-seas-rule.md
  sdk/src/utils/extract-data.ts
Labels: Bug

#23837 Update Editor.js to 2.30+
  app/package.json
  app/src/interfaces/input-block-editor/editorjs-overrides.css
  app/src/interfaces/input-block-editor/input-block-editor.vue
  app/src/interfaces/input-block-editor/plugins.ts
  app/src/shims.d.ts
  pnpm-lock.yaml
Labels: Chore, Core

#24329 Update renovate to include security patches & ignore tinymce v7
  .github/renovate.json
Labels: Chore

#24369 Enable renovate updates for blackbox tests
  .github/renovate.json
Labels: Chore

#24374 Remove/replace obsoelete dependencies
  .changeset/little-pumpkins-yawn.md
  api/package.json
  app/package.json
  docs/.vitepress/data/packages.data.ts
  docs/package.json
  packages/extensions-registry/package.json
  packages/extensions/package.json
  packages/release-notes-generator/package.json
  packages/release-notes-generator/src/utils/process-packages.test.ts
  packages/release-notes-generator/src/utils/process-packages.ts
  packages/stores/package.json
  pnpm-lock.yaml
  sdk/tsup.config.js
Labels: :robot: Dependency, Chore

#24394 Enhance translation interface loading state
  app/src/interfaces/translations/translation-form.vue
  app/src/interfaces/translations/translations.vue
Labels: Optimization

#24316 Fix O2M/M2O node merging with parent
  .changeset/young-papayas-deny.md
  api/src/database/run-ast/utils/merge-with-parent-items.test.ts
  api/src/database/run-ast/utils/merge-with-parent-items.ts
Labels: Bug

#24266 New Crowdin updates
  app/src/lang/translations/de-DE.yaml
  app/src/lang/translations/mr-IN.yaml
  app/src/lang/translations/tr-TR.yaml
  app/src/lang/translations/uk-UA.yaml
Labels: Chore

#24424 Fix SDK policy type for createRole(s)
  .changeset/wet-days-joke.md
  sdk/src/rest/commands/create/roles.ts
Labels: Bug, SDK

#23223 Add social icons in select-icon interface (#23134)
  app/src/components/v-icon/social-icons.ts
  app/src/components/v-icon/v-icon.vue
  app/src/interfaces/select-icon/select-icon.vue
Labels: Improvement
