Repository directus/directus, pull requests merged in 2025-08, with the labels that each got.

#25338 Update tar-fs dependency
  .changeset/cool-pants-eat.md
  package.json
  pnpm-lock.yaml
Labels: ⚠️ Enterprise, Chore, Run Blackbox, Dependency

#25579 Update dependency form-data
  .changeset/ten-news-repair.md
  api/package.json
  app/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Run Blackbox, Dependency

#25459 Add the ability to override the email `from` property
  .changeset/tricky-pans-know.md
  api/src/services/mail/index.test.ts
  api/src/services/mail/index.ts
  contributors.yml
Labels: Run Blackbox

#25636 Fixed RTL empty state center positioning
  .changeset/forty-turtles-peel.md
  app/src/components/v-info.vue
Labels: Bug

#25558 Add new error operation to Flows
  .changeset/unlucky-countries-punch.md
  api/src/operations/error/index.test.ts
  api/src/operations/error/index.ts
  app/src/lang/translations/en-US.yaml
  app/src/operations/error/index.ts
Labels: Improvement, Flows

#25644 Add support for `private_key_jwt` auth method in OpenID driver
  .changeset/five-shrimps-tell.md
  api/src/auth/drivers/openid.ts
Labels: Improvement, ⚠️ Enterprise, Auth

#25681 Update community platform
  directus/readme.md
Labels: Chore

#25765 Release 11.11.0
  .changeset/common-trees-film.md
  .changeset/great-experts-clap.md
  .changeset/khaki-carrots-tie.md
  .changeset/kind-ducks-pay.md
  .changeset/mighty-yaks-spend.md
  .changeset/moody-facts-kick.md
  .changeset/nasty-cooks-smell.md
  .changeset/rare-icons-check.md
  .changeset/real-kings-learn.md
  .changeset/salty-guests-trade.md
  .changeset/sour-nails-study.md
  .changeset/tangy-beans-check.md
  .changeset/yummy-tools-decide.md
  api/package.json
  app/package.json
  directus/package.json
  packages/create-directus-extension/package.json
  packages/extensions-registry/package.json
  packages/extensions-sdk/package.json
  packages/extensions/package.json
  packages/schema-builder/package.json
  packages/types/package.json
  sdk/package.json
Labels: No Changeset
