Repository directus/directus, pull requests merged in 2025-02, with the labels that each got.

#23948 Fix multiple nested aliases
  .changeset/proud-comics-smash.md
  api/src/database/get-ast-from-query/lib/parse-fields.ts
Labels: Bug

#24386 Fix `default_value` dropped on field schema change
  .changeset/purple-pugs-count.md
  api/src/database/helpers/index.ts
  api/src/database/helpers/nullable-update/dialects/default.ts
  api/src/database/helpers/nullable-update/dialects/oracle.ts
  api/src/database/helpers/nullable-update/index.ts
  api/src/database/helpers/nullable-update/types.ts
  api/src/database/helpers/schema/dialects/oracle.ts
  api/src/database/helpers/schema/types.ts
  api/src/services/fields.ts
Labels: Bug, ⚠️ Enterprise

#24529 Add Option handling Missing Data in Time Series Panel
  .changeset/popular-comics-sit.md
  app/src/lang/translations/en-US.yaml
  app/src/panels/time-series/index.ts
  app/src/panels/time-series/panel-time-series.vue
Labels: Improvement

#24574 Add `required` to fields meta docs
  docs/reference/system/fields.md
Labels: Docs

#24569 Add Integer Prop to v-input and prevent non numeric characters
  .changeset/orange-beds-reply.md
  app/src/components/v-input.vue
  app/src/interfaces/input/input.vue
Labels: Bug

#24595 Update default report feature url
  .github/DISCUSSION_TEMPLATE/draft-feature-requests.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  app/src/constants.ts
Labels: Chore

#24543 Don't cache permissions with $NOW
  .changeset/nice-icons-clean.md
  api/src/middleware/respond.ts
  api/src/utils/permissions-cachable.test.ts
  api/src/utils/permissions-cachable.ts
Labels: Bug, Permissions, Core, Run Blackbox

#24233 Add Prometheus support
  .changeset/strange-coins-play.md
  api/package.json
  api/src/app.ts
  api/src/controllers/metrics.ts
  api/src/controllers/server.ts
  api/src/database/index.ts
  api/src/metrics/index.ts
  api/src/metrics/lib/create-metrics.ts
  api/src/metrics/lib/use-metrics.test.ts
  api/src/metrics/lib/use-metrics.ts
  api/src/metrics/types/metric.ts
  api/src/schedules/metrics.test.ts
  api/src/schedules/metrics.ts
  docs/reference/system/metrics.md
  docs/self-hosted/config-options.md
  packages/env/src/constants/defaults.ts
  packages/env/src/constants/directus-variables.ts
  packages/env/src/constants/type-map.ts
  pnpm-lock.yaml
Labels: Feature

#24643 Dependabot: Update Vitest 🧹
  api/package.json
  app/package.json
  packages/components/package.json
  packages/composables/package.json
  packages/env/package.json
  packages/errors/package.json
  packages/extensions-registry/package.json
  packages/extensions-sdk/package.json
  packages/extensions/package.json
  packages/format-title/package.json
  packages/memory/package.json
  packages/pressure/package.json
  packages/random/package.json
  packages/release-notes-generator/package.json
  packages/storage-driver-azure/package.json
  packages/storage-driver-cloudinary/package.json
  packages/storage-driver-gcs/package.json
  packages/storage-driver-local/package.json
  packages/storage-driver-s3/package.json
  packages/storage-driver-supabase/package.json
  packages/storage/package.json
  packages/update-check/package.json
  packages/utils/package.json
  packages/validation/package.json
  pnpm-lock.yaml
  sdk/package.json
  tests/blackbox/package.json
Labels: Chore

#24667 Add semaphore to GraphQL schema generation
  .changeset/great-apes-look.md
  api/package.json
  api/src/services/graphql/schema/index.ts
  docs/self-hosted/config-options.md
  packages/env/src/constants/defaults.ts
  packages/env/src/constants/directus-variables.ts
  packages/env/src/constants/type-map.ts
  pnpm-lock.yaml
Labels: Run Blackbox

#24654 Remove invalid `item_duplication_fields` paths on field delete
  .changeset/cuddly-kings-kick.md
  api/src/services/collections.ts
  api/src/services/fields.ts
  api/src/services/fields/build-collection-and-field-relations.test.ts
  api/src/services/fields/build-collection-and-field-relations.ts
  api/src/services/fields/get-collection-meta-updates.test.ts
  api/src/services/fields/get-collection-meta-updates.ts
  api/src/services/fields/get-collection-relation-list.test.ts
  api/src/services/fields/get-collection-relation-list.ts
  packages/system-data/src/collections/index.ts
Labels: Bug, Run Blackbox

#24728 Fix sqlite in docker image
  .changeset/friendly-rats-kick.md
  Dockerfile
Labels: Bug
